// Generated by scripts/gen-routes.mjs
import ViewHost from '@/components/ViewHost';

export const metadata = { title: "Aircraft" };

export default async function Page({ params }: { params: Promise<Record<string, string>> }) {
  const p = await params;
  return <ViewHost view="Aircraft" {...{ id: decodeURIComponent(p.id).toUpperCase() }} />;
}
