// Generated by scripts/gen-routes.mjs
import ViewHost from '@/components/ViewHost';

export const metadata = { title: "Request access" };

export default function Page() {
  return <ViewHost view="Access" {...{ variant: 'request' }} />;
}
