// Generated by scripts/gen-routes.mjs
import ViewHost from '@/components/ViewHost';

export const metadata = { title: "Reset password" };

export default function Page() {
  return <ViewHost view="Access" {...{ variant: 'forgot' }} />;
}
