// Generated by scripts/gen-routes.mjs
import ViewHost from '@/components/ViewHost';

export const metadata = { title: "About" };

export default function Page() {
  return <ViewHost view="Company" {...{ variant: 'about' }} />;
}
