services:
  - type: web
    name: aerolytics-api
    env: docker
    rootDir: .
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    plan: free
    region: singapore
    envVars:
      - key: AERO_CORS_ORIGINS
        value: "*"
      - key: AERO_PRELOAD
        value: "1"
      - key: AERO_CONF
        value: "0.25"

