// Generated by scripts/gen-routes.mjs
import ViewHost from '@/components/ViewHost';

export const metadata = { title: "Mission log" };

export default function Page() {
  return <ViewHost view="MissionsLog" {...{}} />;
}
