// Generated by scripts/gen-routes.mjs
import ViewHost from '@/components/ViewHost';

export const metadata = { title: "Live ops" };

export default function Page() {
  return <ViewHost view="LiveOps" {...{}} />;
}
