// Generated by scripts/gen-routes.mjs
import ViewHost from '@/components/ViewHost';

export const metadata = { title: "New inspection" };

export default function Page() {
  return <ViewHost view="NewInspection" {...{}} />;
}
