// Writes one App Router page per route. Each page renders <ViewHost view="…" /> with route props.
//   node scripts/gen-routes.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const APP = path.join(path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..'), 'src', 'app');

// [route, view, title, props (JS object literal source using `p` = awaited params)]
const ROUTES = [
  ['/', 'Landing', null, '{}'],
  ['/login', 'Login', 'Sign in', '{}'],
  ['/request-access', 'Access', 'Request access', "{ variant: 'request' }"],
  ['/forgot-password', 'Access', 'Reset password', "{ variant: 'forgot' }"],
  ['/demo', 'Demo', 'Public demo', '{}'],
  ['/platform', 'Platform', 'Platform', '{}'],
  ['/solutions/[pillar]', 'Solutions', 'Solutions', "{ pillar: ['energy', 'agri', 'rescue'].includes(p.pillar) ? p.pillar : 'energy' }"],
  ['/about', 'Company', 'About', "{ variant: 'about' }"],
  ['/contact', 'Company', 'Contact', "{ variant: 'contact' }"],
  ['/dashboard', 'Dashboard', 'Mission overview', '{}'],
  ['/missions', 'MissionsLog', 'Mission log', '{}'],
  ['/missions/new', 'NewInspection', 'New inspection', '{}'],
  ['/missions/[id]', 'MissionTwin', 'Mission twin', '{ id: p.id, pillar: pillarOf(p.id) }'],
  ['/missions/[id]/detections/[detectionId]', 'MissionTwin', 'Inspection dossier', '{ id: p.id, detectionId: p.detectionId, pillar: pillarOf(p.id) }'],
  ['/missions/[id]/report', 'MissionReport', 'Mission report', '{ id: p.id, pillar: pillarOf(p.id) }'],
  ['/missions/[id]/frames', 'Frames', 'Frame gallery', '{ id: p.id, pillar: pillarOf(p.id) }'],
  ['/live', 'LiveOps', 'Live ops', '{}'],
  ['/analytics', 'Analytics', 'Analytics', '{}'],
  ['/sites', 'Sites', 'Sites', '{}'],
  ['/sites/[id]', 'SiteDetail', 'Site detail', '{ id: p.id, pillar: sitePillar(p.id) }'],
  ['/fleet', 'Fleet', 'Fleet', '{}'],
  ['/fleet/[id]', 'Aircraft', 'Aircraft', '{ id: decodeURIComponent(p.id).toUpperCase() }'],
  ['/mission-planner', 'MissionPlanner', 'Mission planner', '{}'],
  ['/reports', 'Reports', 'Reports', '{}'],
  ['/status', 'Status', 'System status', '{}'],
  ['/settings/profile', 'SettingsProfile', 'Profile', '{}'],
  ['/settings/organization', 'SettingsOrganization', 'Organization', '{}'],
  ['/settings/team', 'SettingsTeam', 'Team & roles', '{}'],
  ['/settings/api-keys', 'SettingsApiKeys', 'API keys', '{}'],
  ['/settings/models', 'SettingsModels', 'Models', '{}'],
  ['/audit-log', 'AuditLog', 'Audit log', '{}'],
];

for (const [route, view, title, props] of ROUTES) {
  const dir = path.join(APP, ...route.split('/').filter(Boolean));
  fs.mkdirSync(dir, { recursive: true });
  const dynamic = route.includes('[');
  const needsHelpers = /pillarOf|sitePillar/.test(props);
  const src = [
    '// Generated by scripts/gen-routes.mjs',
    "import ViewHost from '@/components/ViewHost';",
    needsHelpers ? "import { pillarOf, sitePillar } from '@/lib/routes';" : null,
    title ? `\nexport const metadata = { title: ${JSON.stringify(title)} };` : '',
    '',
    dynamic
      ? `export default async function Page({ params }: { params: Promise<Record<string, string>> }) {\n  const p = await params;\n  return <ViewHost view="${view}" {...${props}} />;\n}`
      : `export default function Page() {\n  return <ViewHost view="${view}" {...${props}} />;\n}`,
    '',
  ].filter((l) => l !== null).join('\n');
  fs.writeFileSync(path.join(dir, 'page.tsx'), src);
}
console.log('wrote ' + ROUTES.length + ' routes');
