// Generated by scripts/gen-routes.mjs
import ViewHost from '@/components/ViewHost';

export const metadata = { title: "Team & roles" };

export default function Page() {
  return <ViewHost view="SettingsTeam" {...{}} />;
}
