// Generated by scripts/gen-routes.mjs
import ViewHost from '@/components/ViewHost';
import { pillarOf, sitePillar } from '@/lib/routes';

export const metadata = { title: "Mission twin" };

export default async function Page({ params }: { params: Promise<Record<string, string>> }) {
  const p = await params;
  return <ViewHost view="MissionTwin" {...{ id: p.id, pillar: pillarOf(p.id) }} />;
}
