// Generated by scripts/gen-routes.mjs
import ViewHost from '@/components/ViewHost';

export const metadata = { title: "API keys" };

export default function Page() {
  return <ViewHost view="SettingsApiKeys" {...{}} />;
}
