// Generated by scripts/gen-routes.mjs
import ViewHost from '@/components/ViewHost';

export const metadata = { title: "Solutions" };

export default async function Page({ params }: { params: Promise<Record<string, string>> }) {
  const p = await params;
  return <ViewHost view="Solutions" {...{ pillar: ['energy', 'agri', 'rescue'].includes(p.pillar) ? p.pillar : 'energy' }} />;
}
