// Generated by scripts/gen-routes.mjs
import ViewHost from '@/components/ViewHost';

export const metadata = { title: "Public demo" };

export default function Page() {
  return <ViewHost view="Demo" {...{}} />;
}
