'use client';
/* eslint-disable */
// Generated by scripts/convert-designs.mjs from design/landing-page/Aircraft.template.html — edit the design or the patches, then re-run.
import React from 'react';
import Base from './_base';
import { AppRail, TopBar } from '@/components/chrome';
import { getPillar, setPillar, readJSON, writeJSON, signIn, signOut, saveSession, downloadFile } from '@/lib/store';
import { API_URL, pingApi, inferFile, submitRequest } from '@/lib/api';
import { sessionData } from '@/lib/session';
import './css/Aircraft.css';

class View extends Base {
  constructor(props) {
    super(props);
    this.state = { 
      pillar: 'energy', 
      sel: props.id || 'QUAD-02', 
      view: 'exploded',
      activeModal: null,
      customLogs: [],
      assignMissionId: 'SOLAR-PERIMETER-01',
      toastMessage: '',
      // Log entry form
      entryWork: '',
      entryBy: 'Tech-1',
      entryStatus: 'Planned'
    };
    this._sel = props.id || 'QUAD-02';
    this._view = 'exploded';
  }

  renderVals() {
    const D = this._data();
    const { pillar, sel, view } = this.state;
    const a0 = D.fleet.find((a) => a.id === sel) || D.fleet[0];
    this._sel = a0.id;
    this._view = view;
    const cur = Object.assign({}, a0, { pillarName: D.P[a0.pillar].name, linkCls: a0.sim ? 'b-sim' : 'b-man', maintCls: a0.maint === 'Due now' ? 'amber' : '' });
    const LIMIT = 150;
    return {
      pillars: this._pillarTabs(pillar, (k) => { const a = D.fleet.find((x) => x.pillar === k && !x.sim) || D.fleet[0]; this.setState({ pillar: k, sel: a.id }); }),
      cur,
      picker: D.fleet.map((a) => ({ id: a.id, cls: a.id === cur.id ? 'on' : '', pick: () => this.setState({ sel: a.id }) })),
      views: [['assembled', 'Assembled'], ['exploded', 'Exploded']].map(([k, name]) => ({ name, cls: view === k ? 'on' : '', pick: () => this.setState({ view: k }) })),
      motors: cur.motors.map((h, i) => ({
        n: i + 1, w: Math.min(100, (h / LIMIT) * 100) + '%', color: h > 130 ? '#FFB547' : '#3FB3E0',
        label: cur.sim ? 'sim' : h + ' h', cls: h > 130 ? 'amber' : '',
      })),
      sensors: [
        ['Primary camera', cur.payload],
        ['Gimbal', '[GIMBAL MODEL] · 3-axis'],
        ['GNSS', cur.sim ? 'None · manifest positions' : '[GNSS MODULE] · RTK not fitted'],
        ['Remote ID', cur.sim ? 'n/a · simulated' : '[REMOTE ID NUMBER]'],
        ['Telemetry link', cur.sim ? 'WebSocket demo stream' : 'Not linked · MQTT planned'],
      ].map(([k, v]) => ({ k, v })),
      log: [
        ...(this.state.customLogs || []),
        ...(cur.sim ? [['14 Sep 2026', 'Simulator reset', 'System', 'Done', 'st-resolved']] : [
          [cur.maint === 'Due now' ? 'Due now' : '—', 'Motor 3 inspection / replace', 'Tech-1', cur.status === 'Maintenance' ? 'Open' : 'Planned', cur.status === 'Maintenance' ? 'st-warn' : 'st-off'],
          [cur.maint === 'Due now' ? '21 Aug 2026' : cur.maint, 'Propeller set replaced', 'Tech-2', 'Done', 'st-resolved'],
          ['02 Jul 2026', 'Compass & IMU calibration', 'Tech-1', 'Done', 'st-resolved'],
        ])
      ].map(([date, work, by, status, cls]) => ({ date, work, by, status, cls })),
    };
  }

  componentDidMount() {
    this._syncPillar();
    this._alive = true;
    this._startClock();
    this._boot(0);
  }

  componentWillUnmount() {
    this._alive = false;
    this._stopClock();
    if (this._raf) cancelAnimationFrame(this._raf);
    if (this._model) this._model.destroy();
  }

  _boot(tries) {
    if (!this._alive) return;
    const canvas = document.querySelector('[data-gl="model"]');
    if (!canvas) { if (tries < 120) requestAnimationFrame(() => this._boot(tries + 1)); return; }
    this._model = this._modelScene(this._engine(), canvas, document.querySelector('[data-gl-labels="model"]'));
    this._loop([this._model]);
  }

  // Turntable airframe with explode animation and component callouts.
  _modelScene(K, canvas, labelsEl) {
    const R = K.renderer(canvas, [0.016, 0.043, 0.11]);
    if (!R) return null;
    const { Batch, COL, a, lerp, clamp } = K;
    const self = this;
    const D = this._data();
    const PARTS = ['body', 'battery', 'camera', 'm1', 'm2', 'm3', 'm4'];
    const els = {};
    PARTS.forEach((p) => {
      if (!labelsEl) return;
      const el = document.createElement('div');
      el.className = 'callout';
      labelsEl.appendChild(el);
      els[p] = el;
    });
    const grid = new Batch();
    for (let g = -60; g <= 60; g += 5) { grid.line(g, -12, -60, g, -12, 60, [0.3, 0.55, 1, 0.07]); grid.line(-60, -12, g, 60, -12, g, [0.3, 0.55, 1, 0.07]); }
    grid.ring(0, -11.9, 0, 26, 72, [0.36, 0.88, 1, 0.3], true);
    const gridArr = new Float32Array(grid.a);
    let ex = 0, drag = null, yaw = 0.7, pitch = 0.42;
    const onDown = (e) => { drag = { x: e.clientX, y: e.clientY, yaw, pitch }; };
    const onMove = (e) => { if (!drag) return; yaw = drag.yaw - (e.clientX - drag.x) * 0.006; pitch = clamp(drag.pitch + (e.clientY - drag.y) * 0.004, -0.2, 1.3); };
    const onUp = () => { drag = null; };
    canvas.addEventListener('pointerdown', onDown);
    window.addEventListener('pointermove', onMove);
    window.addEventListener('pointerup', onUp);

    return {
      destroy() { canvas.removeEventListener('pointerdown', onDown); window.removeEventListener('pointermove', onMove); window.removeEventListener('pointerup', onUp); },
      frame(t, dt) {
        const asp = R.resize();
        const air = D.fleet.find((f) => f.id === self._sel) || D.fleet[0];
        ex = lerp(ex, self._view === 'exploded' ? 1 : 0, Math.min(1, dt * 2.2));
        const cy = yaw + (drag ? 0 : t * 0.25), rad = 60 * Math.max(1, 1.3 / asp);
        const eye = [rad * Math.cos(pitch) * Math.sin(cy), 2 + rad * Math.sin(pitch), rad * Math.cos(pitch) * Math.cos(cy)];
        const M = K.camera(asp, eye, [0, 1, 0], 0.7);
        R.begin(M, eye, 40, 160);
        R.draw(gridArr, 'lines', 'add');
        const ln = new Batch(), SC = 6, spin = air.status === 'Offline' ? 0 : t * 0.3;
        self._drawDrone(K, ln, 0, 0, 0, 0, SC, spin, { explode: ex, legs: true, rotor: air.status === 'Maintenance' ? COL.warn : COL.blue });
        const P = (lx, ly, lz) => [lx * SC, ly * SC, lz * SC];
        const o = 2.6 + ex * 1.3;
        const anchors = {
          body: [P(0, 0.3, -1.0), 'Flight controller', air.firmware, false],
          battery: [P(0, 0.7 + ex * 1.6, 0), 'Battery', air.sim ? 'simulated' : air.batt + '% · ' + air.cycles + ' cycles', air.batt < 30 && !air.sim],
          camera: [P(1.1 + ex * 0.8, -0.9 - ex * 1.4, 0), 'Payload', air.payload.split(' ·')[0], false],
        };
        [[1, 1], [1, -1], [-1, -1], [-1, 1]].forEach(([sx, sz], i) => {
          const h = air.motors[i];
          anchors['m' + (i + 1)] = [P(sx * o, 0.9 + ex * 1.2, sz * o), 'Motor ' + (i + 1), air.sim ? 'simulated' : h + ' h', h > 130];
        });
        Object.keys(anchors).forEach((k) => {
          const [p, name, val, warn] = anchors[k];
          const lift = [p[0] + (p[0] >= 0 ? 6 : -6), p[1] + 7, p[2]];
          ln.line(p[0], p[1], p[2], lift[0], lift[1], lift[2], warn ? a(COL.warn, 0.9) : a(COL.cyan, 0.5));
          const sp = K.project(M, lift[0], lift[1], lift[2], R.w, R.h);
          const el = els[k];
          if (!el) return;
          if (sp) {
            el.style.opacity = '1';
            el.className = warn ? 'callout warn' : 'callout';
            el.innerHTML = name + '<b>' + val + '</b>';
            el.style.transform = 'translate(' + sp[0].toFixed(1) + 'px,' + sp[1].toFixed(1) + 'px) translate(' + (p[0] >= 0 ? '0' : '-100%') + ',-100%)';
          } else el.style.opacity = '0';
        });
        R.draw(ln, 'lines', 'add');
      },
    };
  }



  render() {
    const v = this.renderVals();
    return (
      <div className="pg-aircraft ds">
        <div className="app">
          <AppRail active="fleet" />
          <TopBar crumbs={["Fleet","Aircraft"]} pillars={v.pillars} />
          <main className="main">
            <div className="page">
              <div className="page-head">
                <div>
                  <div className="kicker">
                    <i></i>
                    {"Aircraft · "}{v.cur?.payload}
                  </div>
                  <h1 className="h1" style={{ marginTop: "10px" }}>
                    {v.cur?.id}{" · "}{v.cur?.name}
                  </h1>
                </div>
                <div className="acts">
                  <div className="segs">
                    {(v.picker || []).map((p, $index) => (
                      <React.Fragment key={$index}>
                      <button className={p?.cls} onClick={p?.pick}>
                        {p?.id}
                      </button>
                      </React.Fragment>
                    ))}
                  </div>
                  <button className="btn btn-ghost" onClick={() => this.setState({ activeModal: 'log' })}>
                    {"Log maintenance"}
                  </button>
                  <button className="btn btn-primary" onClick={() => this.setState({ activeModal: 'assign' })}>
                    {"Assign to mission"}
                  </button>
                </div>
              </div>
              <div className="cols">
                <section className="panel">
                  <div className="ph">
                    <div className="ph-l">
                      <span className="lbl strong">
                        {"Airframe model"}
                      </span>
                      <span className="badge b-sim">
                        {"Generic quad · not to scale"}
                      </span>
                    </div>
                    <div className="segs">
                      {(v.views || []).map((v, $index) => (
                        <React.Fragment key={$index}>
                        <button className={v?.cls} onClick={v?.pick}>
                          {v?.name}
                        </button>
                        </React.Fragment>
                      ))}
                    </div>
                  </div>
                  <div className="view3d">
                    <canvas className="gl" data-gl="model"></canvas>
                    <div className="gl-labels" data-gl-labels="model"></div>
                    <div className="ov ov-bl glass dims">
                      <span className="lbl">
                        {"Wheelbase"}
                      </span>
                      {" "}
                      <span className="mono" style={{ fontSize: "12px", color: "#fff" }}>
                        {"[DIAGONAL WHEELBASE] mm"}
                      </span>
                    </div>
                    <div className="ov ov-br readout">
                      {"Drag to rotate · callouts follow components"}
                    </div>
                  </div>
                </section>
                <div className="scroll stack">
                  <section className="panel">
                    <div className="ph">
                      <div className="ph-l">
                        <span className={`chip ${v.cur?.scls ?? ""}`}>
                          {v.cur?.status}
                        </span>
                        <span className={`badge ${v.cur?.linkCls ?? ""}`}>
                          {v.cur?.link}
                        </span>
                      </div>
                      <span className="lbl">
                        {v.cur?.model}
                      </span>
                    </div>
                    <div className="pad">
                      <div className="kvg c3">
                        <div>
                          <span className="lbl">
                            {"Battery"}
                          </span>
                          <b>
                            {v.cur?.batt}{"%"}
                          </b>
                        </div>
                        <div>
                          <span className="lbl">
                            {"Flight hours"}
                          </span>
                          <b>
                            {v.cur?.hours}
                          </b>
                        </div>
                        <div>
                          <span className="lbl">
                            {"Cycles"}
                          </span>
                          <b>
                            {v.cur?.cycles}
                          </b>
                        </div>
                        <div>
                          <span className="lbl">
                            {"Firmware"}
                          </span>
                          <b>
                            {v.cur?.firmware}
                          </b>
                        </div>
                        <div>
                          <span className="lbl">
                            {"Last service"}
                          </span>
                          <b className={v.cur?.maintCls}>
                            {v.cur?.maint}
                          </b>
                        </div>
                        <div>
                          <span className="lbl">
                            {"Home pillar"}
                          </span>
                          <b>
                            {v.cur?.pillarName}
                          </b>
                        </div>
                      </div>
                    </div>
                  </section>
                  <section className="panel">
                    <div className="ph">
                      <span className="lbl strong">
                        {"Motor hours"}
                      </span>
                      <span className="lbl">
                        <span className="amber">
                          {"|"}
                        </span>
                        {" Service at 130 h · sample"}
                      </span>
                    </div>
                    <div className="motors">
                      {(v.motors || []).map((m, $index) => (
                        <React.Fragment key={$index}>
                        <div className="motor">
                          <span>
                            {"Motor "}{m?.n}
                          </span>
                          <div className="mtrack">
                            <b style={{ width: `${m?.w ?? ""}`, background: `${m?.color ?? ""}` }}></b>
                            <i></i>
                          </div>
                          <b className={m?.cls}>
                            {m?.label}
                          </b>
                        </div>
                        </React.Fragment>
                      ))}
                    </div>
                  </section>
                  <section className="panel">
                    <div className="ph">
                      <span className="lbl strong">
                        {"Payload & sensors"}
                      </span>
                    </div>
                    {(v.sensors || []).map((s, $index) => (
                      <React.Fragment key={$index}>
                      <div className="kvl-row">
                        <span>
                          {s?.k}
                        </span>
                        <b>
                          {s?.v}
                        </b>
                        <i></i>
                      </div>
                      </React.Fragment>
                    ))}
                  </section>
                  <section className="panel">
                    <div className="ph">
                      <span className="lbl strong">
                        {"Maintenance log"}
                      </span>
                      <button className="btn btn-ghost btn-sm" onClick={() => this.setState({ activeModal: 'log' })}>
                        {"+ Entry"}
                      </button>
                    </div>
                    <table className="tbl">
                      <thead>
                        <tr>
                          <th>
                            {"Date"}
                          </th>
                          <th>
                            {"Work"}
                          </th>
                          <th>
                            {"By"}
                          </th>
                          <th>
                            {"Status"}
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        {(v.log || []).map((l, $index) => (
                          <React.Fragment key={$index}>
                          <tr>
                            <td>
                              {l?.date}
                            </td>
                            <td style={{ color: "#fff" }}>
                              {l?.work}
                            </td>
                            <td>
                              {l?.by}
                            </td>
                            <td>
                              <span className={`chip ${l?.cls ?? ""}`}>
                                {l?.status}
                              </span>
                            </td>
                          </tr>
                          </React.Fragment>
                        ))}
                      </tbody>
                    </table>
                  </section>
                </div>
              </div>
            </div>
          </main>
        </div>

        {/* Modal overlays */}
        {this.state.activeModal === 'assign' && (
          <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.75)', backdropFilter: 'blur(4px)', zIndex: 999, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '20px' }}>
            <div style={{ background: '#121824', border: '1px solid #2A364F', borderRadius: '12px', width: '100%', maxWidth: '440px', padding: '24px', boxShadow: '0 20px 40px rgba(0,0,0,0.5)' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
                <h3 style={{ margin: 0, fontSize: '18px', fontWeight: 600, color: '#fff' }}>Assign to Mission</h3>
                <button onClick={() => this.setState({ activeModal: null })} style={{ background: 'none', border: 'none', color: '#8F9BBA', cursor: 'pointer', fontSize: '18px' }}>✕</button>
              </div>
              <p style={{ color: '#8F9BBA', fontSize: '13px', marginBottom: '20px' }}>Select an active or upcoming mission for <strong>{v.cur?.id}</strong>.</p>
              <div style={{ marginBottom: '20px' }}>
                <label style={{ display: 'block', color: '#CBD5E1', fontSize: '12px', marginBottom: '8px' }}>Target Mission</label>
                <select 
                  value={this.state.assignMissionId}
                  onChange={(e) => this.setState({ assignMissionId: e.target.value })}
                  style={{ width: '100%', background: '#0B0F17', border: '1px solid #2A364F', borderRadius: '6px', color: '#fff', padding: '10px 12px', fontSize: '13px', outline: 'none' }}
                >
                  <option value="SOLAR-PERIMETER-01">SOLAR-PERIMETER-01 (Energy · Thermal)</option>
                  <option value="MINE-STOCKPILE-04">MINE-STOCKPILE-04 (Mining · Volumetric)</option>
                  <option value="INFRA-BRIDGE-02">INFRA-BRIDGE-02 (Infra · Crack Detection)</option>
                </select>
              </div>
              <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '10px' }}>
                <button className="btn btn-ghost" onClick={() => this.setState({ activeModal: null })}>Cancel</button>
                <button className="btn btn-primary" onClick={() => {
                  this.setState({ 
                    activeModal: null, 
                    toastMessage: `Successfully assigned ${v.cur?.id} to ${this.state.assignMissionId}` 
                  });
                  setTimeout(() => this.setState({ toastMessage: '' }), 4000);
                }}>Confirm Assignment</button>
              </div>
            </div>
          </div>
        )}

        {this.state.activeModal === 'log' && (
          <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.75)', backdropFilter: 'blur(4px)', zIndex: 999, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '20px' }}>
            <div style={{ background: '#121824', border: '1px solid #2A364F', borderRadius: '12px', width: '100%', maxWidth: '480px', padding: '24px', boxShadow: '0 20px 40px rgba(0,0,0,0.5)' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
                <h3 style={{ margin: 0, fontSize: '18px', fontWeight: 600, color: '#fff' }}>Log Maintenance Activity</h3>
                <button onClick={() => this.setState({ activeModal: null })} style={{ background: 'none', border: 'none', color: '#8F9BBA', cursor: 'pointer', fontSize: '18px' }}>✕</button>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '14px', marginBottom: '20px' }}>
                <div>
                  <label style={{ display: 'block', color: '#CBD5E1', fontSize: '12px', marginBottom: '6px' }}>Work Performed</label>
                  <input 
                    type="text" 
                    placeholder="e.g. Battery pack replacement & test"
                    value={this.state.entryWork}
                    onChange={(e) => this.setState({ entryWork: e.target.value })}
                    style={{ width: '100%', background: '#0B0F17', border: '1px solid #2A364F', borderRadius: '6px', color: '#fff', padding: '10px 12px', fontSize: '13px', outline: 'none' }}
                  />
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
                  <div>
                    <label style={{ display: 'block', color: '#CBD5E1', fontSize: '12px', marginBottom: '6px' }}>Technician</label>
                    <input 
                      type="text" 
                      value={this.state.entryBy}
                      onChange={(e) => this.setState({ entryBy: e.target.value })}
                      style={{ width: '100%', background: '#0B0F17', border: '1px solid #2A364F', borderRadius: '6px', color: '#fff', padding: '10px 12px', fontSize: '13px', outline: 'none' }}
                    />
                  </div>
                  <div>
                    <label style={{ display: 'block', color: '#CBD5E1', fontSize: '12px', marginBottom: '6px' }}>Status</label>
                    <select 
                      value={this.state.entryStatus}
                      onChange={(e) => this.setState({ entryStatus: e.target.value })}
                      style={{ width: '100%', background: '#0B0F17', border: '1px solid #2A364F', borderRadius: '6px', color: '#fff', padding: '10px 12px', fontSize: '13px', outline: 'none' }}
                    >
                      <option value="Done">Done</option>
                      <option value="Open">Open</option>
                      <option value="Planned">Planned</option>
                    </select>
                  </div>
                </div>
              </div>
              <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '10px' }}>
                <button className="btn btn-ghost" onClick={() => this.setState({ activeModal: null })}>Cancel</button>
                <button className="btn btn-primary" onClick={() => {
                  if (!this.state.entryWork.trim()) return;
                  const newEntry = [
                    new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }),
                    this.state.entryWork,
                    this.state.entryBy,
                    this.state.entryStatus,
                    this.state.entryStatus === 'Done' ? 'st-resolved' : this.state.entryStatus === 'Open' ? 'st-warn' : 'st-off'
                  ];
                  this.setState({
                    customLogs: [newEntry, ...this.state.customLogs],
                    activeModal: null,
                    entryWork: '',
                    toastMessage: 'Maintenance log entry added successfully'
                  });
                  setTimeout(() => this.setState({ toastMessage: '' }), 4000);
                }}>Save Log Entry</button>
              </div>
            </div>
          </div>
        )}

        {/* Toast Alert */}
        {this.state.toastMessage && (
          <div style={{ position: 'fixed', bottom: '24px', right: '24px', background: '#38BDF8', color: '#090D16', padding: '12px 20px', borderRadius: '8px', fontWeight: 600, fontSize: '13px', boxShadow: '0 10px 30px rgba(56,189,248,0.3)', zIndex: 1000, display: 'flex', alignItems: 'center', gap: '8px' }}>
            <span>✓</span> {this.state.toastMessage}
          </div>
        )}
      </div>
    );
  }
}

export default View;
