'use client';
/* eslint-disable */
// Generated by scripts/convert-designs.mjs from design/landing-page/Company.template.html — edit the design or the patches, then re-run.
import React from 'react';
import Base from './_base';
import { MkNav, MkFoot } from '@/components/chrome';
import { getPillar, setPillar, readJSON, writeJSON, signIn, signOut, saveSession, downloadFile } from '@/lib/store';
import { API_URL, pingApi, inferFile, submitRequest } from '@/lib/api';
import { sessionData } from '@/lib/session';
import './css/Company.css';

class View extends Base {
  constructor(props) {
    super(props);
    this.state = { page: props.variant === 'contact' ? 'contact' : 'about', sent: false, name: '', email: '', interest: 'energy', size: 'm', error: '', open: 0 };
    this._selSite = 'rsp';
    this._onAoPick = (key) => { this._selSite = key; };
  }

  renderVals() {
    const D = this._data();
    const s = this.state;
    const about = s.page === 'about';
    const seg = (key, opts) => opts.map(([v, name]) => ({ name, cls: s[key] === v ? 'on' : '', pick: () => this.setState({ [key]: v }) }));
    return {
      navKey: s.page,
      isAbout: about, isContact: !about,
      v: about
        ? { kicker: 'About', h1a: 'Drone intelligence,', h1b: 'honestly labelled.', lede: 'Aerolytics turns drone imagery into geolocated findings for energy, agriculture and emergency response, starting from Rajkot, Gujarat.' }
        : { kicker: 'Contact', h1a: 'Plan a pilot', h1b: 'over your site.', lede: 'Tell us what you need to inspect. We will come back with a flight plan, a timeline and what the pilot will measure.' },
      variants: [['about', 'About'], ['contact', 'Contact']].map(([k, name]) => ({ name, cls: s.page === k ? 'on' : '', pick: () => { this.setState({ page: k }); window.history.replaceState(null, '', '/' + k); } })),
      principles: [
        ['Label every number', 'Simulated, manifest and EXIF data carry their source on screen and in every export.', '#FFB547'],
        ['Show uncertainty', 'Positions are marked approximate until RTK is fitted; model scores come with their validation split.', '#5CE1FF'],
        ['Keep people in charge', 'Detections are leads. Crews and responders confirm, assign and close them.', '#7BE3A0'],
        ['Build for the field', 'Works from a manifest when GPS is missing, and from a laptop when the network is thin.', '#9BE15D'],
      ].map(([t, b, color]) => ({ t, b, color })),
      milestones: [
        ['Sep 2026', 'Golden demo', 'Command center, twins and reports over a simulated Rajkot mission.', '#5CE1FF'],
        ['Q4 2026', 'Validation sets', 'Labelled field data to measure accuracy beyond the training splits.', '#FFB547'],
        ['2027', 'Live telemetry', 'WebSocket and MQTT streams from registered aircraft.', '#9BE15D'],
        ['Later', 'Fleet & mapping', 'RTK positions, orthomosaics and mission plans sent to aircraft.', '#7F90AD'],
      ].map(([when, t, b, color]) => ({ when, t, b, color })),
      team: [['[FOUNDER NAME]', '[ROLE] · product & operations'], ['[ENGINEER NAME]', '[ROLE] · computer vision'], ['[ENGINEER NAME]', '[ROLE] · platform & 3D']].map(([name, role]) => ({ name, role })),
      notSent: !s.sent, isSent: s.sent,
      setName: (e) => this.setState({ name: (e && e.target && e.target.value) || '' }),
      setEmail: (e) => this.setState({ email: (e && e.target && e.target.value) || '', error: '' }),
      pillarOpts: seg('interest', [['energy', 'Energy'], ['agri', 'Agri'], ['rescue', 'Rescue']]),
      sizeOpts: seg('size', [['s', '< 10 ha'], ['m', '10–100 ha'], ['l', '100 ha +']]),
      hasError: !!s.error, error: s.error,
      send: () => {
        if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(this.state.email)) { this.setState({ error: 'Enter a valid work email' }); return; }
        this.setState({ sent: true, error: '' });
        submitRequest({ type: 'contact', email: this.state.email, name: this.state.name, interest: this.state.interest, size: this.state.size });
      },
      nameSuffix: s.name ? ', ' + s.name : '',
      email: s.email || 'your email', pillarName: D.P[s.interest].name, ref: 'REQ-' + String(4000 + s.email.length * 37).slice(-4),
      reset: () => this.setState({ sent: false }),
      faq: [
        ['What does a pilot include?', 'One site, one pillar, planned flights, processed detections in the command center, and a report built from the mission data.'],
        ['Do we need our own drones?', 'Not at first. The platform accepts imagery from most survey drones; we can also plan flights with your operator.'],
        ['How accurate are the positions?', 'As accurate as the telemetry source. Manifest positions are approximate; RTK-equipped aircraft give survey-grade results.'],
      ].map(([q, a], i) => ({ q, a, open: s.open === i, sign: s.open === i ? '−' : '+', toggle: () => this.setState({ open: this.state.open === i ? -1 : i }) })),
    };
  }

  componentDidMount() {
    this._syncPillar(); this._alive = true; this._boot(0); }
  componentWillUnmount() { this._alive = false; if (this._raf) cancelAnimationFrame(this._raf); if (this._ao) this._ao.destroy(); }

  _boot(tries) {
    if (!this._alive) return;
    const canvas = document.querySelector('[data-gl="ao"]');
    if (!canvas) { if (tries < 120) requestAnimationFrame(() => this._boot(tries + 1)); return; }
    this._ao = this._aoScene(this._engine(), canvas, document.querySelector('[data-gl-labels="ao"]'));
    this._loop([this._ao]);
  }



  render() {
    const v = this.renderVals();
    return (
      <div className="pg-company ds">
        <div className="mk">
          <MkNav active="about" />
          <section className="hero">
            <canvas className="gl" data-gl="ao"></canvas>
            <div className="gl-labels" data-gl-labels="ao"></div>
            <div className="mk-shade"></div>
            <div className="hero-copy">
              <div className="kicker">
                <i></i>
                {v.v?.kicker}
              </div>
              <h1 className="mk-h1">
                {v.v?.h1a}
                <br />
                <span>
                  {v.v?.h1b}
                </span>
              </h1>
              <p className="mk-lede">
                {v.v?.lede}
              </p>
            </div>
            <div className="variant">
              <span className="lbl">
                {"Page"}
              </span>
              <div className="segs">
                {(v.variants || []).map((o, $index) => (
                  <React.Fragment key={$index}>
                  <button className={o?.cls} onClick={o?.pick}>
                    {o?.name}
                  </button>
                  </React.Fragment>
                ))}
              </div>
            </div>
          </section>
          {v.isAbout ? (
            <>
            <div>
              <section className="mk-sec">
                <div className="kicker">
                  <i></i>
                  {"01 / Principles"}
                </div>
                <h2 className="mk-h2">
                  {"How we build."}
                </h2>
                <div className="principles">
                  {(v.principles || []).map((p, $index) => (
                    <React.Fragment key={$index}>
                    <div className="panel pr">
                      <i className="dia" style={{ background: `${p?.color ?? ""}` }}></i>
                      <h3>
                        {p?.t}
                      </h3>
                      <p>
                        {p?.b}
                      </p>
                    </div>
                    </React.Fragment>
                  ))}
                </div>
              </section>
              <section className="mk-sec">
                <div className="kicker">
                  <i></i>
                  {"02 / Milestones"}
                </div>
                <h2 className="mk-h2">
                  {"Where we are, and what is next."}
                </h2>
                <div className="timeline">
                  {(v.milestones || []).map((m, $index) => (
                    <React.Fragment key={$index}>
                    <div className="ms">
                      <i className="dia" style={{ background: `${m?.color ?? ""}` }}></i>
                      <div className="meta">
                        {m?.when}
                      </div>
                      <h3>
                        {m?.t}
                      </h3>
                      <p>
                        {m?.b}
                      </p>
                    </div>
                    </React.Fragment>
                  ))}
                </div>
              </section>
              <section className="mk-sec">
                <div className="kicker">
                  <i></i>
                  {"03 / Team"}
                </div>
                <h2 className="mk-h2">
                  {"The people behind the engine."}
                </h2>
                <div className="team">
                  {(v.team || []).map((t, $index) => (
                    <React.Fragment key={$index}>
                    <div className="panel tm">
                      <div className="tm-av">
                        {"[PHOTO]"}
                      </div>
                      <div>
                        <div className="li-t">
                          {t?.name}
                        </div>
                        <div className="li-s">
                          {t?.role}
                        </div>
                      </div>
                    </div>
                    </React.Fragment>
                  ))}
                </div>
              </section>
            </div>
            </>
          ) : null}
          {v.isContact ? (
            <>
            <section className="mk-sec">
              <div className="contact">
                {v.notSent ? (
                  <>
                  <div className="panel form">
                    <div className="lbl strong">
                      {"Tell us about your site"}
                    </div>
                    <div className="fgrid" style={{ marginTop: "16px" }}>
                      <label className="field">
                        <span className="lbl">
                          {"Name"}
                        </span>
                        <span className="input">
                          <input type="text" placeholder="Your name" onInput={v.setName} />
                        </span>
                      </label>
                      <label className="field">
                        <span className="lbl">
                          {"Work email"}
                        </span>
                        <span className="input">
                          <input type="email" placeholder="you@organization.com" onInput={v.setEmail} />
                        </span>
                      </label>
                      <label className="field full">
                        <span className="lbl">
                          {"Organization"}
                        </span>
                        <span className="input">
                          <input type="text" placeholder="Organization name" />
                        </span>
                      </label>
                      <div className="field">
                        <span className="lbl">
                          {"Interested in"}
                        </span>
                        <div className="segs">
                          {(v.pillarOpts || []).map((o, $index) => (
                            <React.Fragment key={$index}>
                            <button className={o?.cls} onClick={o?.pick}>
                              {o?.name}
                            </button>
                            </React.Fragment>
                          ))}
                        </div>
                      </div>
                      <div className="field">
                        <span className="lbl">
                          {"Site size"}
                        </span>
                        <div className="segs">
                          {(v.sizeOpts || []).map((o, $index) => (
                            <React.Fragment key={$index}>
                            <button className={o?.cls} onClick={o?.pick}>
                              {o?.name}
                            </button>
                            </React.Fragment>
                          ))}
                        </div>
                      </div>
                      <label className="field full">
                        <span className="lbl">
                          {"Message"}
                        </span>
                        <span className="ta">
                          <textarea placeholder="What would you like to inspect, and when?"></textarea>
                        </span>
                      </label>
                    </div>
                    <div style={{ display: "flex", alignItems: "center", gap: "16px", marginTop: "18px" }}>
                      <button className="btn btn-primary" onClick={v.send}>
                        {"Send request"}
                      </button>
                      {v.hasError ? (
                        <>
                        <span className="err">
                          {v.error}
                        </span>
                        </>
                      ) : null}
                    </div>
                  </div>
                  </>
                ) : null}
                {v.isSent ? (
                  <>
                  <div className="panel sent">
                    <i className="dia sev-ok" style={{ width: "18px", height: "18px" }}></i>
                    <h2 className="h2">
                      {"Request received"}
                    </h2>
                    <p>
                      {"Thanks"}{v.nameSuffix}{". We will reply to "}{v.email}{" about a "}{v.pillarName}{" pilot. Reference "}{v.ref}{"."}
                    </p>
                    <button className="btn btn-ghost" style={{ marginTop: "20px" }} onClick={v.reset}>
                      {"Send another"}
                    </button>
                  </div>
                  </>
                ) : null}
                <div className="side">
                  <section className="panel">
                    <div className="ph">
                      <span className="lbl strong">
                        {"Contact"}
                      </span>
                    </div>
                    <div className="kvl-row">
                      <span>
                        {"Email"}
                      </span>
                      <b>
                        {"[CONTACT EMAIL]"}
                      </b>
                      <i></i>
                    </div>
                    <div className="kvl-row">
                      <span>
                        {"Office"}
                      </span>
                      <b>
                        {"[OFFICE ADDRESS] · Rajkot, Gujarat"}
                      </b>
                      <i></i>
                    </div>
                    <div className="kvl-row">
                      <span>
                        {"Response time"}
                      </span>
                      <b>
                        {"[RESPONSE TIME]"}
                      </b>
                      <i></i>
                    </div>
                  </section>
                  <section className="panel faq">
                    {(v.faq || []).map((f, $index) => (
                      <React.Fragment key={$index}>
                      <div>
                        <button className="q" onClick={f?.toggle}>
                          {f?.q}
                          <em>
                            {f?.sign}
                          </em>
                        </button>
                        {f?.open ? (
                          <>
                          <div className="a">
                            {f?.a}
                          </div>
                          </>
                        ) : null}
                      </div>
                      </React.Fragment>
                    ))}
                  </section>
                </div>
              </div>
            </section>
            </>
          ) : null}
          <MkFoot />
        </div>
      </div>
    );
  }
}

export default View;
