'use client';
/* eslint-disable */
// Generated by scripts/convert-designs.mjs from design/landing-page/Dashboard.template.html — edit the design or the patches, then re-run.
import React from 'react';
import Link from 'next/link';
import Base from './_base';
import { AppRail, TopBar } from '@/components/chrome';
import { getPillar, setPillar, readJSON, writeJSON, signIn, signOut, saveSession, downloadFile } from '@/lib/store';
import { API_URL, pingApi, inferFile, submitRequest } from '@/lib/api';
import { sessionData } from '@/lib/session';
import './css/Dashboard.css';

class View extends Base {
  constructor(props) {
    super(props);
    this.state = { pillar: 'energy', tab: 'all', sel: null, view: 'orbit', selMission: 'AER-EN-0142', layers: { terrain: true, path: true, dets: true, overlay: true } };
  }

  renderVals() {
    const D = this._data();
    const { pillar, tab, sel, view, selMission, layers } = this.state;
    const pc = D.P[pillar];
    const all = pc.dets;
    const firstStatus = all.length ? (pillar === 'rescue' ? 'New' : 'New') : '';
    const list = tab === 'crit' ? all.filter((q) => q.sev === 'crit') : tab === 'open' ? all.filter((q) => q.status === firstStatus) : all;
    const HIST = [14, 22, 18, 30, 12, 26, 34, 20, 28, 16, 24, 38];
    const counts = pc.classes.map((c) => c[1]);
    const max = Math.max(1, ...counts);
    const pick = (k) => {
      this.setState({ pillar: k, sel: null, tab: 'all' });
      if (this._twin) { this._twin.setPillar(k); this._twin.select(null); }
    };
    return {
      pillars: this._pillarTabs(pillar, pick),
      pc,
      kpis: pc.kpis.map((k) => Object.assign({}, k, {
        bigCls: k.crit ? 'crit' : '',
        isBar: k.viz === 'bar', isHist: k.viz === 'hist', isDia: k.viz === 'dia', isRing: k.viz === 'ring', isNdvi: k.viz === 'ndvi',
        pctStr: (k.pct || 0) + '%',
        dash: ((k.pct || 0) * 1.005).toFixed(1) + ' 100.5',
        hist: HIST.map((h, i) => ({ h: h + 'px', o: i === HIST.length - 1 ? '1' : '0.5' })),
        dias: Array.from({ length: k.n || 0 }, (_, i) => ({ i })),
      })),
      tabs: [
        ['all', 'All', all.length],
        ['crit', 'Critical', all.filter((q) => q.sev === 'crit').length],
        ['open', pillar === 'rescue' ? 'Unconfirmed' : 'Unassigned', all.filter((q) => q.status === firstStatus).length],
      ].map(([key, name, n]) => ({ name, n, cls: tab === key ? 'on' : '', pick: () => this.setState({ tab: key }) })),
      alerts: list.map((q) => Object.assign({}, q, { thumb: pc.thumb, confStr: q.conf.toFixed(2), selCls: q.id === sel ? 'sel' : '', pick: () => this._select(q.id) })),
      noAlerts: list.length === 0,
      critCount: all.filter((q) => q.sev === 'crit').length,
      views: [['orbit', '3D'], ['top', 'Top'], ['follow', 'Follow drone']].map(([k, name]) => ({
        name, cls: view === k ? 'on' : '', pick: () => { this.setState({ view: k }); if (this._twin) this._twin.setView(k); },
      })),
      layerList: [['terrain', 'Terrain'], ['path', pillar === 'rescue' ? 'Search path' : 'Flight path'], ['dets', pillar === 'rescue' ? 'Heat signatures' : 'Detections'], ['overlay', pc.overlay]].map(([k, name]) => ({
        name, cls: layers[k] ? 'on' : '', toggle: () => {
          const next = Object.assign({}, this.state.layers, { [k]: !this.state.layers[k] });
          this.setState({ layers: next });
          if (this._twin) this._twin.setLayers(next);
        },
      })),
      zoomIn: () => this._twin && this._twin.zoom(0.8),
      zoomOut: () => this._twin && this._twin.zoom(1.25),
      resetView: () => { if (this._twin) this._twin.resetView(); this.setState({ view: 'orbit', sel: null }); },
      missions: D.missions.map((m) => Object.assign({}, m, {
        chip: D.P[m.pillar].chip, pillarName: D.P[m.pillar].name, selCls: m.id === selMission ? 'sel' : '',
        pick: () => this.setState({ selMission: m.id }),
        isProc: m.status === 'Processing', isDone: m.status === 'Complete', isFail: m.status === 'Failed', pctStr: m.pct + '%',
      })),
      classes: pc.classes.map(([name, n, sev]) => ({ name, n: n || '—', w: (n / max) * 100 + '%', color: sev === 'crit' ? '#FF6A3D' : '#FFB547' })),
      pipe: [
        ['Upload', '212 / 212 frames', 'done'],
        ['Telemetry', 'Manifest fallback', 'warn'],
        ['Inference', '38 ms / frame', 'live'],
        ['Normalize', 'Queued', 'pending'],
        ['Geo-map', 'Queued', 'pending'],
      ].map(([name, note, st]) => ({
        name, note,
        rowCls: st === 'pending' ? 'pending' : '',
        diaCls: st === 'pending' ? 'dia-off' : st === 'live' ? 'dia-live' : 'sev-info',
        noteCls: st === 'warn' ? 'amber' : '',
      })),
    };
  }

  _select(id) {
    const next = this.state.sel === id ? null : id;
    this.setState({ sel: next });
    if (this._twin) this._twin.select(next);
  }

  componentDidMount() {
    this._syncPillar();
    this._alive = true;
    this._startClock();
    this._boot(0);
  }

  componentWillUnmount() {
    this._alive = false;
    this._stopClock();
    if (this._raf) cancelAnimationFrame(this._raf);
    if (this._twin) this._twin.destroy();
  }

  _boot(tries) {
    if (!this._alive) return;
    const canvas = document.querySelector('[data-gl="twin"]');
    if (!canvas) { if (tries < 120) requestAnimationFrame(() => this._boot(tries + 1)); return; }
    const hud = {};
    ['lat', 'lon', 'hdg', 'lane'].forEach((k) => { hud[k] = document.querySelector('[data-hud="' + k + '"]'); });
    this._twin = this._twinScene(this._engine(), canvas, {
      pillar: this.state.pillar,
      mode: 'overview',
      labelsEl: document.querySelector('[data-gl-labels="twin"]'),
      onPick: (id) => { if (id) this._select(id); },
      onHud: (h) => { Object.keys(hud).forEach((k) => { if (hud[k]) hud[k].textContent = h[k]; }); },
    });
    this._loop([this._twin]);
  }



  render() {
    const v = this.renderVals();
    return (
      <div className="pg-dashboard ds">
        <div className="app">
          <AppRail active="dashboard" />
          <TopBar crumbs={["Command center","Dashboard"]} pillars={v.pillars} />
          <main className="main">
            <div className="dash">
              <div className="dash-head">
                <div>
                  <div className="kicker" style={{ color: `${v.pc?.color ?? ""}` }}>
                    <i></i>
                    {v.pc?.name}{" · "}{v.pc?.long}
                  </div>
                  <h1 className="h1" style={{ marginTop: "10px" }}>
                    {"Mission overview"}
                  </h1>
                </div>
                <div className="meta">
                  {"Site: "}{v.pc?.site}{" · AO 22.3000° N 70.8000° E · Last sync "}
                  <span data-clock="utc">
                    {"--:--:-- UTC"}
                  </span>
                </div>
                <Link className="btn btn-primary" href={'/missions/new'}>
                  {"+ New inspection"}
                </Link>
              </div>
              <div className="kpis">
                {(v.kpis || []).map((k, $index) => (
                  <React.Fragment key={$index}>
                  <div className="panel kpi">
                    <div className="kpi-top">
                      <span className="lbl">
                        {k?.k}
                      </span>
                      <span className={`badge ${k?.bcls ?? ""}`}>
                        {k?.badge}
                      </span>
                    </div>
                    <div className="kpi-mid">
                      <span className={`big ${k?.bigCls ?? ""}`}>
                        {k?.v}
                      </span>
                      <span className="kpi-of">
                        {k?.of}
                      </span>
                    </div>
                    <div className="kpi-note">
                      {k?.note}
                    </div>
                    <div className="kpi-viz">
                      {k?.isBar ? (
                        <>
                        <div className="bar3">
                          <b style={{ width: `${k?.pctStr ?? ""}` }}></b>
                        </div>
                        </>
                      ) : null}
                      {k?.isHist ? (
                        <>
                        <div className="hist">
                          {(k?.hist || []).map((h, $index) => (
                            <React.Fragment key={$index}>
                            <i style={{ height: `${h?.h ?? ""}`, opacity: `${h?.o ?? ""}` }}></i>
                            </React.Fragment>
                          ))}
                        </div>
                        </>
                      ) : null}
                      {k?.isDia ? (
                        <>
                        <div className="dias">
                          {(k?.dias || []).map((x, $index) => (
                            <React.Fragment key={$index}>
                            <i className="dia sev-crit"></i>
                            </React.Fragment>
                          ))}
                        </div>
                        </>
                      ) : null}
                      {k?.isRing ? (
                        <>
                        <svg width="46" height="46" viewBox="0 0 40 40">
                          <circle cx="20" cy="20" r="16" fill="none" stroke="rgba(120,170,255,.16)" strokeWidth="2"></circle>
                          <circle cx="20" cy="20" r="16" fill="none" stroke="#5CE1FF" strokeWidth="2" strokeDasharray={k?.dash} transform="rotate(-90 20 20)"></circle>
                          <circle cx="20" cy="20" r="11" fill="none" stroke="rgba(120,170,255,.2)" strokeWidth="1" strokeDasharray="1 5.9"></circle>
                        </svg>
                        </>
                      ) : null}
                      {k?.isNdvi ? (
                        <>
                        <div className="ndvi">
                          <div className="ndvi-tick">
                            <b></b>
                          </div>
                          <div className="ndvi-strip"></div>
                          <div className="ndvi-lbl">
                            <span>
                              {"Stress"}
                            </span>
                            <span>
                              {"Healthy"}
                            </span>
                          </div>
                        </div>
                        </>
                      ) : null}
                    </div>
                  </div>
                  </React.Fragment>
                ))}
              </div>
              <div className="row2">
                <section className="panel">
                  <div className="ph">
                    <div className="ph-l">
                      <span className="lbl strong">
                        {"Site digital twin"}
                      </span>
                      <span className="badge b-sim">
                        {"Simulated telemetry"}
                      </span>
                    </div>
                    <div className="ph-l">
                      <div className="segs">
                        {(v.views || []).map((v, $index) => (
                          <React.Fragment key={$index}>
                          <button className={v?.cls} onClick={v?.pick}>
                            {v?.name}
                          </button>
                          </React.Fragment>
                        ))}
                      </div>
                      <Link className="btn btn-ghost btn-sm" href={'/missions/' + (v.sessionId || (v.pc ? v.pc.mission : 'AER-EN-0142'))}>
                        {"Open mission twin →"}
                      </Link>
                    </div>
                  </div>
                  <div className="twin-view">
                    <canvas className="gl" data-gl="twin"></canvas>
                    <div className="gl-labels" data-gl-labels="twin"></div>
                    <div className="glass layers">
                      <span className="lbl">
                        {"Layers"}
                      </span>
                      {(v.layerList || []).map((l, $index) => (
                        <React.Fragment key={$index}>
                        <button className={`ck ${l?.cls ?? ""}`} onClick={l?.toggle}>
                          <i></i>
                          {l?.name}
                        </button>
                        </React.Fragment>
                      ))}
                    </div>
                    <div className="glass zoom">
                      <button onClick={v.zoomIn}>
                        {"+"}
                      </button>
                      <button onClick={v.zoomOut}>
                        {"−"}
                      </button>
                      <button onClick={v.resetView}>
                        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6">
                          <path d="M4 12a8 8 0 108-8H7"></path>
                          <path d="M9 1L6 4l3 3"></path>
                        </svg>
                      </button>
                    </div>
                    <div className="readout">
                      {"DRONE "}
                      <b data-hud="lat">
                        {"22.30000° N"}
                      </b>
                      {" "}
                      <b data-hud="lon">
                        {"70.80000° E"}
                      </b>
                      {" · HDG "}
                      <b data-hud="hdg">
                        {"090°"}
                      </b>
                      {" · LANE "}
                      <b data-hud="lane">
                        {"1 / 7"}
                      </b>
                      {" "}
                      <span className="amber">
                        {"±APPROX."}
                      </span>
                    </div>
                    <div className="glass legend">
                      <span>
                        <i className="dia sev-crit"></i>
                        {"Critical"}
                      </span>
                      <span>
                        <i className="dia sev-warn"></i>
                        {"Warning"}
                      </span>
                      <span>
                        <svg width="22" height="4">
                          <line x1="0" y1="2" x2="22" y2="2" stroke="#5CE1FF" strokeWidth="2"></line>
                        </svg>
                        {"Recorded"}
                      </span>
                      <span>
                        <svg width="22" height="4">
                          <line x1="0" y1="2" x2="22" y2="2" stroke="#FFB547" strokeWidth="2" strokeDasharray="4 3"></line>
                        </svg>
                        {"Simulated"}
                      </span>
                    </div>
                  </div>
                </section>
                <section className="panel">
                  <div className="ph">
                    <span className="lbl strong">
                      {"Priority alerts"}
                    </span>
                    <span className="badge b-crit">
                      {v.critCount}{" critical"}
                    </span>
                  </div>
                  <div className="tabs">
                    {(v.tabs || []).map((t, $index) => (
                      <React.Fragment key={$index}>
                      <button className={`tab ${t?.cls ?? ""}`} onClick={t?.pick}>
                        {t?.name}
                        <em>
                          {t?.n}
                        </em>
                      </button>
                      </React.Fragment>
                    ))}
                  </div>
                  <div className="scroll alert-list">
                    {(v.alerts || []).map((al, $index) => (
                      <React.Fragment key={$index}>
                      <button className={`alert ${al?.selCls ?? ""}`} onClick={al?.pick}>
                        <i className={`al-sev ${al?.sevCls ?? ""}`}></i>
                        <span className={`thumb ${al?.thumb ?? ""} al-thumb`}>
                          <span className="bbox"></span>
                        </span>
                        <span className="al-body">
                          <span className="al-cls">
                            {al?.cls}{" "}
                            <em>
                              {"· "}{al?.confStr}
                            </em>
                          </span>
                          <span className="al-loc">
                            {al?.loc}{" · "}{al?.lat}
                          </span>
                        </span>
                        <span className="al-right">
                          <span className={`chip ${al?.statusCls ?? ""}`}>
                            {al?.status}
                          </span>
                          <span className="al-ago">
                            {al?.ago}
                          </span>
                        </span>
                      </button>
                      </React.Fragment>
                    ))}
                    {v.noAlerts ? (
                      <>
                      <div className="empty">
                        {"No alerts in this view"}
                      </div>
                      </>
                    ) : null}
                  </div>
                  <Link className="panel-foot" href={'/missions/' + v.pc.mission}>
                    <span>
                      {"View all detections"}
                    </span>
                    <span>
                      {"→"}
                    </span>
                  </Link>
                </section>
              </div>
              <div className="row3">
                <section className="panel">
                  <div className="ph">
                    <span className="lbl strong">
                      {"Recent missions"}
                    </span>
                    <Link className="btn btn-ghost btn-sm" href={'/missions'}>
                      {"All missions →"}
                    </Link>
                  </div>
                  <div className="scroll tbl-wrap">
                    <table className="tbl">
                      <thead>
                        <tr>
                          <th>
                            {"Mission ID"}
                          </th>
                          <th>
                            {"Site"}
                          </th>
                          <th>
                            {"Pillar"}
                          </th>
                          <th>
                            {"Date (UTC)"}
                          </th>
                          <th>
                            {"Frames"}
                          </th>
                          <th>
                            {"Crit / Total"}
                          </th>
                          <th>
                            {"Telemetry"}
                          </th>
                          <th>
                            {"Status"}
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        {(v.missions || []).map((m, $index) => (
                          <React.Fragment key={$index}>
                          <tr className={m?.selCls} onClick={m?.pick}>
                            <td style={{ color: "#fff" }}>
                              {m?.id}
                            </td>
                            <td>
                              {m?.site}
                            </td>
                            <td>
                              <span className={`chip ${m?.chip ?? ""}`}>
                                {m?.pillarName}
                              </span>
                            </td>
                            <td>
                              {m?.date}
                            </td>
                            <td>
                              {m?.frames}
                            </td>
                            <td>
                              {m?.det}
                            </td>
                            <td>
                              <span className={`badge ${m?.tcls ?? ""}`}>
                                {m?.tele}
                              </span>
                            </td>
                            <td>
                              {m?.isProc ? (
                                <>
                                <span className="proc">
                                  <span className="stat" style={{ color: "#5CE1FF" }}>
                                    {m?.pctStr}
                                  </span>
                                  <span className="bar3">
                                    <b style={{ width: `${m?.pctStr ?? ""}` }}></b>
                                  </span>
                                </span>
                                </>
                              ) : null}
                              {m?.isDone ? (
                                <>
                                <span className="stat" style={{ color: "#7BE3A0" }}>
                                  <i className="dia sev-ok"></i>
                                  {"Complete"}
                                </span>
                                </>
                              ) : null}
                              {m?.isFail ? (
                                <>
                                <span className="stat" style={{ color: "#FF6A3D" }}>
                                  <i className="dia sev-crit"></i>
                                  {"Failed"}
                                  <Link className="retry" href={'/missions'}>
                                    {"Retry"}
                                  </Link>
                                </span>
                                </>
                              ) : null}
                            </td>
                          </tr>
                          </React.Fragment>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </section>
                <section className="panel">
                  <div className="ph">
                    <span className="lbl strong">
                      {v.pc?.classesLbl}
                    </span>
                  </div>
                  <div className="cls-list">
                    {(v.classes || []).map((c, $index) => (
                      <React.Fragment key={$index}>
                      <div className="cls-row">
                        <span>
                          {c?.name}
                        </span>
                        <span>
                          {c?.n}
                        </span>
                        <div className="cls-bar">
                          <b style={{ width: `${c?.w ?? ""}`, background: `${c?.color ?? ""}` }}></b>
                        </div>
                      </div>
                      </React.Fragment>
                    ))}
                  </div>
                  <div className="foot-note">
                    {"Model: "}{v.pc?.model}{" · demo"}
                  </div>
                </section>
                <section className="panel">
                  <div className="ph">
                    <span className="lbl strong">
                      {"Processing · AER-EN-0143"}
                    </span>
                    <span className="chip st-new">
                      {"64%"}
                    </span>
                  </div>
                  <div className="pipe">
                    {(v.pipe || []).map((s, $index) => (
                      <React.Fragment key={$index}>
                      <div className={`ps ${s?.rowCls ?? ""}`}>
                        <i className={`dia ${s?.diaCls ?? ""}`}></i>
                        <span>
                          {s?.name}
                        </span>
                        <em className={s?.noteCls}>
                          {s?.note}
                        </em>
                      </div>
                      </React.Fragment>
                    ))}
                  </div>
                  <div className="foot-note" style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                    <i className="dia sev-warn"></i>
                    {"API · demo mode · sample timings"}
                  </div>
                </section>
              </div>
            </div>
          </main>
        </div>
      </div>
    );
  }
}

export default View;
