'use client';
/* eslint-disable */
// Generated by scripts/convert-designs.mjs from design/landing-page/Fleet.template.html — edit the design or the patches, then re-run.
import React from 'react';
import Link from 'next/link';
import Base from './_base';
import { AppRail, TopBar } from '@/components/chrome';
import { getPillar, setPillar, readJSON, writeJSON, signIn, signOut, saveSession, downloadFile } from '@/lib/store';
import { API_URL, pingApi, inferFile, submitRequest } from '@/lib/api';
import { sessionData } from '@/lib/session';
import './css/Fleet.css';

class View extends Base {
  constructor(props) {
    super(props);
    this.state = { 
      pillar: 'energy', 
      sf: 'all', 
      sel: 'QUAD-01',
      activeModal: null,
      customFleet: [],
      toastMessage: '',
      // Register aircraft form
      newId: '',
      newModel: 'Generic Quad',
      newPayload: '4K RGB + Thermal',
      newPillar: 'energy',
      // Service form
      serviceDate: new Date().toISOString().split('T')[0],
      serviceNotes: ''
    };
    this._sel = 'QUAD-01';
  }

  renderVals() {
    const D = this._data();
    const { pillar, sf, sel } = this.state;
    const rows = D.fleet.filter((a) => sf === 'all' || a.status.toLowerCase().replace(' ', '') === sf);
    const cur0 = D.fleet.find((a) => a.id === sel) || D.fleet[0];
    this._sel = cur0.id;
    const cur = Object.assign({}, cur0, { chip: D.P[cur0.pillar].chip, pillarName: D.P[cur0.pillar].name });
    const linked = cur.sim;
    return {
      pillars: this._pillarTabs(pillar, (k) => {
        const a = D.fleet.find((x) => x.pillar === k && !x.sim) || D.fleet[0];
        this.setState({ pillar: k, sel: a.id });
      }),
      count: D.fleet.length,
      filters: [['all', 'All'], ['ready', 'Ready'], ['inflight', 'In flight'], ['maintenance', 'Service'], ['offline', 'Offline']].map(([k, name]) => ({ name, cls: sf === k ? 'on' : '', pick: () => this.setState({ sf: k }) })),
      rows: rows.map((a) => Object.assign({}, a, {
        battStr: a.batt + '%', battColor: a.batt < 30 ? '#FFB547' : '#3FB3E0',
        maintCls: a.maint === 'Due now' ? 'amber' : '',
        linkCls: a.sim ? 'b-sim' : 'b-man',
        selCls: a.id === cur.id ? 'sel' : '', pick: () => this.setState({ sel: a.id }),
      })),
      cur,
      checks: [
        ['Battery', linked ? cur.batt + '% · simulated' : 'Awaiting link'],
        ['Propellers & motors', cur.status === 'Maintenance' ? 'Motor 3 over hours' : linked ? 'Simulated' : 'Awaiting link'],
        ['GNSS lock', linked ? 'Not available · manifest' : 'Awaiting link'],
        ['Compass calibration', linked ? 'Simulated' : 'Awaiting link'],
        ['Payload · ' + cur.payload.split(' ·')[0], linked ? 'Simulated' : 'Awaiting link'],
        ['Firmware ' + cur.firmware, cur.firmware.charAt(0) === '[' ? 'Not registered' : 'Current'],
      ].map(([name, state]) => {
        const warn = /Awaiting|over hours|Not registered|Not available/.test(state);
        return { name, state, cls: warn ? 'amber' : 'ok', dia: warn ? 'sev-warn' : 'sev-ok' };
      }),
    };
  }

  componentDidMount() {
    this._syncPillar();
    this._alive = true;
    this._startClock();
    this._boot(0);
  }

  componentWillUnmount() {
    this._alive = false;
    this._stopClock();
    if (this._raf) cancelAnimationFrame(this._raf);
    if (this._hangar) this._hangar.destroy();
  }

  _boot(tries) {
    if (!this._alive) return;
    const canvas = document.querySelector('[data-gl="hangar"]');
    if (!canvas) { if (tries < 120) requestAnimationFrame(() => this._boot(tries + 1)); return; }
    this._hangar = this._hangarScene(this._engine(), canvas, document.querySelector('[data-gl-labels="hangar"]'));
    this._loop([this._hangar]);
  }

  // Four landing pads in a row; each aircraft drawn in its current state. Click picks.
  _hangarScene(K, canvas, labelsEl) {
    const R = K.renderer(canvas, [0.016, 0.043, 0.11]);
    if (!R) return null;
    const { Batch, COL, a, lerp, clamp } = K;
    const self = this;
    const D = this._data();
    const GAP = 26;
    const pads = D.fleet.map((f, i) => {
      const el = labelsEl ? document.createElement('div') : null;
      if (el) { el.className = 'gl-tag'; el.style.color = f.status === 'Maintenance' ? '#FFB547' : f.status === 'Offline' ? '#7F90AD' : '#5CE1FF'; el.innerHTML = f.id + '<i>' + f.status.toUpperCase() + '</i>'; labelsEl.appendChild(el); }
      return { f, x: (i - (D.fleet.length - 1) / 2) * GAP, el, sx: -1, sy: -1, lift: 0 };
    });
    const floor = new Batch();
    for (let g = -90; g <= 90; g += 6) {
      floor.line(g, 0, -40, g, 0, 40, [0.3, 0.55, 1, g % 30 === 0 ? 0.16 : 0.07]);
    }
    for (let g = -40; g <= 40; g += 6) floor.line(-90, 0, g, 90, 0, g, [0.3, 0.55, 1, 0.07]);
    const floorArr = new Float32Array(floor.a);
    let cx = 0, drag = null, yaw = 0.25, pitch = 0.38;
    const onDown = (e) => { drag = { x: e.clientX, y: e.clientY, yaw, pitch, moved: false }; };
    const onMove = (e) => { if (!drag) return; const dx = e.clientX - drag.x, dy = e.clientY - drag.y; if (Math.abs(dx) + Math.abs(dy) > 4) drag.moved = true; yaw = drag.yaw - dx * 0.005; pitch = clamp(drag.pitch + dy * 0.003, 0.12, 1.1); };
    const onUp = (e) => {
      if (drag && !drag.moved) {
        const r = canvas.getBoundingClientRect(), px = (e.clientX - r.left) * canvas.clientWidth / Math.max(1, r.width), py = (e.clientY - r.top) * canvas.clientHeight / Math.max(1, r.height);
        let best = null, bd = 60;
        pads.forEach((p) => { const d = Math.hypot(p.sx - px, p.sy - py); if (d < bd) { bd = d; best = p; } });
        if (best) self.setState({ sel: best.f.id });
      }
      drag = null;
    };
    canvas.addEventListener('pointerdown', onDown);
    window.addEventListener('pointermove', onMove);
    window.addEventListener('pointerup', onUp);

    return {
      destroy() { canvas.removeEventListener('pointerdown', onDown); window.removeEventListener('pointermove', onMove); window.removeEventListener('pointerup', onUp); },
      frame(t, dt) {
        const asp = R.resize();
        const cur = pads.find((p) => p.f.id === self._sel) || pads[0];
        cx = lerp(cx, cur.x * 0.6, Math.min(1, dt * 2.5));
        const cy = yaw + (drag ? 0 : Math.sin(t * 0.15) * 0.12), rad = 92 * Math.max(1, 2.2 / asp);
        const T = [cx, 6, 0];
        const eye = [T[0] + rad * Math.cos(pitch) * Math.sin(cy), T[1] + rad * Math.sin(pitch), T[2] + rad * Math.cos(pitch) * Math.cos(cy)];
        const M = K.camera(asp, eye, T, 0.62);
        R.begin(M, eye, 80, 260);
        R.draw(floorArr, 'lines', 'add');
        const ln = new Batch(), fill = new Batch(), pts = new Batch();
        pads.forEach((p) => {
          const st = p.f.status, on = p === cur;
          const tone = st === 'Maintenance' ? COL.warn : st === 'Offline' ? [0.5, 0.56, 0.68, 1] : COL.cyan;
          for (let k = 0; k < 6; k++) {
            const a1 = (k / 6) * Math.PI * 2 + Math.PI / 6, a2 = ((k + 1) / 6) * Math.PI * 2 + Math.PI / 6;
            ln.line(p.x + Math.cos(a1) * 9, 0.1, Math.sin(a1) * 9, p.x + Math.cos(a2) * 9, 0.1, Math.sin(a2) * 9, a(tone, on ? 0.95 : 0.45));
            fill.tri([p.x, 0.05, 0], [p.x + Math.cos(a1) * 9, 0.05, Math.sin(a1) * 9], [p.x + Math.cos(a2) * 9, 0.05, Math.sin(a2) * 9], a(tone, on ? 0.1 : 0.04));
          }
          if (on) {
            const ph = (t * 0.6) % 1;
            ln.ring(p.x, 0.1, 0, 9 + ph * 5, 36, a(tone, 0.7 * (1 - ph)));
            for (let k = 0; k < 10; k++) { const an = (k / 10) * Math.PI * 2; ln.line(p.x + Math.cos(an) * 6, 30, Math.sin(an) * 6, p.x + Math.cos(an) * 8, 0.2, Math.sin(an) * 8, a(tone, 0.07)); }
          }
          const flying = st === 'In flight', offline = st === 'Offline';
          p.lift = lerp(p.lift, flying ? 9 + Math.sin(t * 1.4) * 0.8 : 1.3, Math.min(1, dt * 2));
          const time = offline ? 0 : st === 'Maintenance' ? t * 0.05 : t;
          self._drawDrone(K, ln, p.x, p.lift, 0, 0.6 + (flying ? t * 0.3 : 0), 1.7, time, {
            explode: st === 'Maintenance' ? 0.45 + 0.1 * Math.sin(t) : 0,
            color: offline ? [0.55, 0.6, 0.7, 1] : COL.white,
            rotor: offline ? [0.4, 0.45, 0.55, 1] : st === 'Maintenance' ? COL.warn : COL.blue,
          });
          if (flying) pts.v(p.x, p.lift - 2, 0, a(COL.cyan, 0.5));
          const sp = K.project(M, p.x, p.lift + 7, 0, R.w, R.h), hit = K.project(M, p.x, p.lift, 0, R.w, R.h);
          if (hit) { p.sx = hit[0]; p.sy = hit[1]; }
          if (p.el) {
            if (sp) { p.el.style.opacity = on ? '1' : '0.7'; p.el.className = on ? 'gl-tag sel' : 'gl-tag'; p.el.style.transform = 'translate(' + sp[0].toFixed(1) + 'px,' + sp[1].toFixed(1) + 'px) translate(-50%,-100%)'; }
            else p.el.style.opacity = '0';
          }
        });
        R.draw(fill, 'tris', 'alpha');
        R.draw(ln, 'lines', 'add');
        R.draw(pts, 'points', 'add', 90);
      },
    };
  }



  render() {
    const v = this.renderVals();
    return (
      <div className="pg-fleet ds">
        <div className="app">
          <AppRail active="fleet" />
          <TopBar crumbs={["Command center","Fleet"]} pillars={v.pillars} />
          <main className="main">
            <div className="page">
              <div className="page-head">
                <div>
                  <div className="kicker">
                    <i></i>
                    {"Fleet · aircraft & sensors"}
                  </div>
                  <h1 className="h1" style={{ marginTop: "10px" }}>
                    {"Fleet"}
                  </h1>
                </div>
                <div className="meta">
                  {v.count}{" aircraft · no hardware linked · sample fleet"}
                </div>
                <div className="acts">
                  <div className="segs">
                    {(v.filters || []).map((f, $index) => (
                      <React.Fragment key={$index}>
                      <button className={f?.cls} onClick={f?.pick}>
                        {f?.name}
                      </button>
                      </React.Fragment>
                    ))}
                  </div>
                  <button className="btn btn-primary" onClick={() => this.setState({ activeModal: 'register' })}>
                    {"+ Register aircraft"}
                  </button>
                </div>
              </div>
              <div className="body">
                <section className="panel">
                  <div className="ph">
                    <div className="ph-l">
                      <span className="lbl strong">
                        {"Hangar"}
                      </span>
                      <span className="badge b-sim">
                        {"Visualisation · sample"}
                      </span>
                    </div>
                    <span className="hint">
                      {"Click an aircraft"}
                    </span>
                  </div>
                  <div className="view3d">
                    <canvas className="gl" data-gl="hangar"></canvas>
                    <div className="gl-labels" data-gl-labels="hangar"></div>
                  </div>
                </section>
                <div className="lower">
                  <section className="panel">
                    <div className="scroll" style={{ flex: "1" }}>
                      <table className="tbl">
                        <thead>
                          <tr>
                            <th>
                              {"Aircraft"}
                            </th>
                            <th>
                              {"Model"}
                            </th>
                            <th>
                              {"Payload"}
                            </th>
                            <th>
                              {"Status"}
                            </th>
                            <th>
                              {"Battery"}
                            </th>
                            <th>
                              {"Hours"}
                            </th>
                            <th>
                              {"Cycles"}
                            </th>
                            <th>
                              {"Maintenance"}
                            </th>
                            <th>
                              {"Link"}
                            </th>
                          </tr>
                        </thead>
                        <tbody>
                          {(v.rows || []).map((a, $index) => (
                            <React.Fragment key={$index}>
                            <tr className={a?.selCls} onClick={a?.pick}>
                              <td style={{ color: "#fff" }}>
                                {a?.id}
                              </td>
                              <td>
                                {a?.model}
                              </td>
                              <td>
                                {a?.payload}
                              </td>
                              <td>
                                <span className={`chip ${a?.scls ?? ""}`}>
                                  {a?.status}
                                </span>
                              </td>
                              <td>
                                <span className="batt">
                                  <span className="hbar">
                                    <b style={{ width: `${a?.battStr ?? ""}`, background: `${a?.battColor ?? ""}` }}></b>
                                  </span>
                                  {a?.battStr}
                                </span>
                              </td>
                              <td>
                                {a?.hours}
                              </td>
                              <td>
                                {a?.cycles}
                              </td>
                              <td className={a?.maintCls}>
                                {a?.maint}
                              </td>
                              <td>
                                <span className={`badge ${a?.linkCls ?? ""}`}>
                                  {a?.link}
                                </span>
                              </td>
                            </tr>
                            </React.Fragment>
                          ))}
                        </tbody>
                      </table>
                    </div>
                    <div className="note">
                      {"Battery = last reported charge · linking real aircraft needs the telemetry gateway (MQTT / WebSocket)"}
                    </div>
                  </section>
                  <section className="panel">
                    <div className="side-body scroll">
                      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                        <span className={`chip ${v.cur?.scls ?? ""}`}>
                          {v.cur?.status}
                        </span>
                        <span className={`chip ${v.cur?.chip ?? ""}`}>
                          {v.cur?.pillarName}
                        </span>
                      </div>
                      <h2 className="h2">
                        {v.cur?.id}
                      </h2>
                      <div className="li-s" style={{ marginTop: "4px" }}>
                        {v.cur?.name}{" · "}{v.cur?.payload}
                      </div>
                      <div className="checks">
                        {(v.checks || []).map((c, $index) => (
                          <React.Fragment key={$index}>
                          <div className="chk">
                            <i className={`dia ${c?.dia ?? ""}`}></i>
                            <span>
                              {c?.name}
                            </span>
                            <em className={c?.cls}>
                              {c?.state}
                            </em>
                          </div>
                          </React.Fragment>
                        ))}
                      </div>
                    </div>
                    <div className="side-acts">
                      <Link className="btn btn-primary btn-sm" href={'/fleet/' + v.cur.id}>
                        {"Open aircraft →"}
                      </Link>
                      <button className="btn btn-ghost btn-sm" onClick={() => this.setState({ activeModal: 'schedule' })}>
                        {"Schedule service"}
                      </button>
                    </div>
                  </section>
                </div>
              </div>
            </div>
          </main>
        </div>

        {/* Modal overlays */}
        {this.state.activeModal === 'register' && (
          <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.75)', backdropFilter: 'blur(4px)', zIndex: 999, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '20px' }}>
            <div style={{ background: '#121824', border: '1px solid #2A364F', borderRadius: '12px', width: '100%', maxWidth: '480px', padding: '24px', boxShadow: '0 20px 40px rgba(0,0,0,0.5)' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
                <h3 style={{ margin: 0, fontSize: '18px', fontWeight: 600, color: '#fff' }}>Register New Aircraft</h3>
                <button onClick={() => this.setState({ activeModal: null })} style={{ background: 'none', border: 'none', color: '#8F9BBA', cursor: 'pointer', fontSize: '18px' }}>✕</button>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '14px', marginBottom: '20px' }}>
                <div>
                  <label style={{ display: 'block', color: '#CBD5E1', fontSize: '12px', marginBottom: '6px' }}>Aircraft ID / Call-sign</label>
                  <input 
                    type="text" 
                    placeholder="e.g. QUAD-05 or HEAVY-02"
                    value={this.state.newId}
                    onChange={(e) => this.setState({ newId: e.target.value })}
                    style={{ width: '100%', background: '#0B0F17', border: '1px solid #2A364F', borderRadius: '6px', color: '#fff', padding: '10px 12px', fontSize: '13px', outline: 'none' }}
                  />
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
                  <div>
                    <label style={{ display: 'block', color: '#CBD5E1', fontSize: '12px', marginBottom: '6px' }}>Model</label>
                    <input 
                      type="text" 
                      value={this.state.newModel}
                      onChange={(e) => this.setState({ newModel: e.target.value })}
                      style={{ width: '100%', background: '#0B0F17', border: '1px solid #2A364F', borderRadius: '6px', color: '#fff', padding: '10px 12px', fontSize: '13px', outline: 'none' }}
                    />
                  </div>
                  <div>
                    <label style={{ display: 'block', color: '#CBD5E1', fontSize: '12px', marginBottom: '6px' }}>Industry Pillar</label>
                    <select 
                      value={this.state.newPillar}
                      onChange={(e) => this.setState({ newPillar: e.target.value })}
                      style={{ width: '100%', background: '#0B0F17', border: '1px solid #2A364F', borderRadius: '6px', color: '#fff', padding: '10px 12px', fontSize: '13px', outline: 'none' }}
                    >
                      <option value="energy">Energy Sector</option>
                      <option value="mining">Mining & Volumetric</option>
                      <option value="infra">Infrastructure</option>
                    </select>
                  </div>
                </div>
                <div>
                  <label style={{ display: 'block', color: '#CBD5E1', fontSize: '12px', marginBottom: '6px' }}>Payload Configuration</label>
                  <input 
                    type="text" 
                    value={this.state.newPayload}
                    onChange={(e) => this.setState({ newPayload: e.target.value })}
                    style={{ width: '100%', background: '#0B0F17', border: '1px solid #2A364F', borderRadius: '6px', color: '#fff', padding: '10px 12px', fontSize: '13px', outline: 'none' }}
                  />
                </div>
              </div>
              <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '10px' }}>
                <button className="btn btn-ghost" onClick={() => this.setState({ activeModal: null })}>Cancel</button>
                <button className="btn btn-primary" onClick={() => {
                  if (!this.state.newId.trim()) return;
                  this.setState({
                    activeModal: null,
                    newId: '',
                    toastMessage: `Aircraft ${this.state.newId || 'QUAD-NEW'} registered to fleet successfully`
                  });
                  setTimeout(() => this.setState({ toastMessage: '' }), 4000);
                }}>Register Aircraft</button>
              </div>
            </div>
          </div>
        )}

        {this.state.activeModal === 'schedule' && (
          <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.75)', backdropFilter: 'blur(4px)', zIndex: 999, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '20px' }}>
            <div style={{ background: '#121824', border: '1px solid #2A364F', borderRadius: '12px', width: '100%', maxWidth: '440px', padding: '24px', boxShadow: '0 20px 40px rgba(0,0,0,0.5)' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
                <h3 style={{ margin: 0, fontSize: '18px', fontWeight: 600, color: '#fff' }}>Schedule Service</h3>
                <button onClick={() => this.setState({ activeModal: null })} style={{ background: 'none', border: 'none', color: '#8F9BBA', cursor: 'pointer', fontSize: '18px' }}>✕</button>
              </div>
              <p style={{ color: '#8F9BBA', fontSize: '13px', marginBottom: '16px' }}>Schedule maintenance window for <strong>{v.cur?.id}</strong>.</p>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '14px', marginBottom: '20px' }}>
                <div>
                  <label style={{ display: 'block', color: '#CBD5E1', fontSize: '12px', marginBottom: '6px' }}>Service Date</label>
                  <input 
                    type="date" 
                    value={this.state.serviceDate}
                    onChange={(e) => this.setState({ serviceDate: e.target.value })}
                    style={{ width: '100%', background: '#0B0F17', border: '1px solid #2A364F', borderRadius: '6px', color: '#fff', padding: '10px 12px', fontSize: '13px', outline: 'none' }}
                  />
                </div>
                <div>
                  <label style={{ display: 'block', color: '#CBD5E1', fontSize: '12px', marginBottom: '6px' }}>Service Notes / Inspection items</label>
                  <textarea 
                    rows={3}
                    placeholder="e.g. 50-hour motor bearing & gimbal calibration check"
                    value={this.state.serviceNotes}
                    onChange={(e) => this.setState({ serviceNotes: e.target.value })}
                    style={{ width: '100%', background: '#0B0F17', border: '1px solid #2A364F', borderRadius: '6px', color: '#fff', padding: '10px 12px', fontSize: '13px', outline: 'none', resize: 'vertical' }}
                  />
                </div>
              </div>
              <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '10px' }}>
                <button className="btn btn-ghost" onClick={() => this.setState({ activeModal: null })}>Cancel</button>
                <button className="btn btn-primary" onClick={() => {
                  this.setState({
                    activeModal: null,
                    serviceNotes: '',
                    toastMessage: `Service scheduled for ${v.cur?.id} on ${this.state.serviceDate}`
                  });
                  setTimeout(() => this.setState({ toastMessage: '' }), 4000);
                }}>Confirm Schedule</button>
              </div>
            </div>
          </div>
        )}

        {/* Toast Alert */}
        {this.state.toastMessage && (
          <div style={{ position: 'fixed', bottom: '24px', right: '24px', background: '#38BDF8', color: '#090D16', padding: '12px 20px', borderRadius: '8px', fontWeight: 600, fontSize: '13px', boxShadow: '0 10px 30px rgba(56,189,248,0.3)', zIndex: 1000, display: 'flex', alignItems: 'center', gap: '8px' }}>
            <span>✓</span> {this.state.toastMessage}
          </div>
        )}
      </div>
    );
  }
}

export default View;
