'use client';
/* eslint-disable */
// Generated by scripts/convert-designs.mjs from design/landing-page/Frames.template.html — edit the design or the patches, then re-run.
import React from 'react';
import Link from 'next/link';
import Base from './_base';
import { AppRail, TopBar } from '@/components/chrome';
import { getPillar, setPillar, readJSON, writeJSON, signIn, signOut, saveSession, downloadFile } from '@/lib/store';
import { API_URL, pingApi, inferFile, submitRequest } from '@/lib/api';
import { sessionData } from '@/lib/session';
import './css/Frames.css';

class View extends Base {
  constructor(props) {
    super(props);
    this._dataOverride = sessionData(props.id, this.__data());
    this.state = { pillar: props.pillar || 'energy', filter: 'all', size: 's', sel: 0, ov: { boxes: true, labels: true, heat: false } };
  }

  _frames(pillar) {
    const D = this._data();
    const pc = D.P[pillar];
    const N = 24;
    const detFrames = {};
    pc.dets.forEach((q) => { const n = parseInt(q.frame.slice(4), 10); (detFrames[n] = detFrames[n] || []).push(q); });
    const nums = Array.from({ length: N }, (_, i) => Math.round(((i + 0.5) / N) * pc.frames));
    Object.keys(detFrames).map(Number).forEach((n) => {
      let bi = 0, bd = 1e9;
      nums.forEach((v, i) => { const d = Math.abs(v - n); if (d < bd && !detFrames[v]) { bd = d; bi = i; } });
      nums[bi] = n;
    });
    const uniq = Array.from(new Set(nums)).sort((a, b) => a - b);
    const FLIGHT = 860;
    return uniq.map((n, i) => {
      const dets = detFrames[n] || [];
      const src = i % 5 === 3 ? 'none' : pillar === 'agri' ? 'exif' : 'manifest';
      const secs = Math.round((n / pc.frames) * FLIGHT);
      const lane = Math.min(6, Math.floor((n / pc.frames) * 7));
      const along = ((n / pc.frames) * 7) % 1;
      return {
        idx: i, n, id: 'FRM-' + String(n).padStart(4, '0'), dets, src, lane, along,
        time: 'T+' + String(Math.floor(secs / 60)).padStart(2, '0') + ':' + String(secs % 60).padStart(2, '0'),
        bp: (i * 13) % 100 + '% ' + (i * 29) % 100 + '%',
      };
    });
  }

  renderVals() {
    const D = this._data();
    const { pillar, filter, size, sel, ov } = this.state;
    const pc = D.P[pillar];
    const all = this._frames(pillar);
    const list = all.filter((f) => filter === 'all' || (filter === 'dets' ? f.dets.length : f.src === 'none'));
    const cur0 = all[Math.max(0, Math.min(all.length - 1, sel))];
    const boxesOf = (f) => f.dets.map((q) => ({
      l: (q.bbox[0] / 10).toFixed(1) + '%', t: (q.bbox[1] / 7.5).toFixed(1) + '%',
      w: ((q.bbox[2] - q.bbox[0]) / 10).toFixed(1) + '%', h: ((q.bbox[3] - q.bbox[1]) / 7.5).toFixed(1) + '%',
      color: q.sev === 'crit' ? '#FF6A3D' : '#FFB547', label: q.cls.toUpperCase() + ' ' + q.conf.toFixed(2),
    }));
    const srcBadge = (s) => (s === 'exif' ? ['EXIF', 'b-exif'] : s === 'manifest' ? ['Manifest', 'b-man'] : ['No GPS', 'b-sim']);
    const mxOf = (f) => { const dir = f.lane % 2 ? 1 - f.along : f.along; return [30 + dir * 346, 12 + f.lane * 14]; };
    const [mx, my] = mxOf(cur0);
    const lat = (22.3 - ((-36 + cur0.lane * 12) * 1.5) / 111320).toFixed(5), lon = (70.8 + ((-56 + (cur0.lane % 2 ? 1 - cur0.along : cur0.along) * 112) * 1.5) / 102990).toFixed(5);
    const camera = { energy: 'RGB 20 MP · sample', agri: 'Multispectral 5-band · sample', rescue: 'LWIR 640×512 · sample' }[pillar];
    const cur = Object.assign({}, cur0, {
      thumbCls: pc.thumb + (cur0.dets.length ? '' : ' clean'), boxes: boxesOf(cur0),
      src: srcBadge(cur0.src)[0], srcCls: srcBadge(cur0.src)[1],
      heat: cur0.dets.length ? 'radial-gradient(circle at ' + (cur0.dets[0].bbox[0] / 10 + 6) + '% ' + (cur0.dets[0].bbox[1] / 7.5 + 8) + '%, rgba(255,106,61,.55), rgba(255,181,71,.15) 18%, rgba(0,0,0,0) 34%)' : 'none',
      detRows: cur0.dets.map((q) => Object.assign({}, q, { confStr: q.conf.toFixed(2), bboxStr: q.bbox.join(', ') })),
      noDets: cur0.dets.length === 0,
      meta: [
        ['Captured', cur0.time + ' · lane ' + (cur0.lane + 1) + ' of 7'],
        ['Latitude', lat + '° N' + (cur0.src === 'none' ? ' · interpolated' : '')],
        ['Longitude', lon + '° E'],
        ['Altitude / heading', '42.0 m AGL · ' + (cur0.lane % 2 ? '270°' : '090°')],
        ['Camera', camera],
        ['Exposure', '[EXIF EXPOSURE · ISO]'],
      ].map(([k, v]) => ({ k, v })),
      mx: mx.toFixed(1), my: my.toFixed(1), mxr: (mx - 4).toFixed(1), myr: (my - 4).toFixed(1), rot: 'rotate(45 ' + mx.toFixed(1) + ' ' + my.toFixed(1) + ')',
    });
    const step = (d) => () => this.setState({ sel: Math.max(0, Math.min(all.length - 1, this.state.sel + d)) });
    const tog = (k) => () => this.setState({ ov: Object.assign({}, this.state.ov, { [k]: !this.state.ov[k] }) });
    return {
      pillars: this._pillarTabs(pillar, (k) => { const fr = this._frames(k); const i = fr.findIndex((f) => f.dets.length); this.setState({ pillar: k, sel: Math.max(0, i), filter: 'all' }); }),
      pc,
      shown: list.length,
      filters: [['all', 'All'], ['dets', 'With detections'], ['nogps', 'No GPS']].map(([k, name]) => ({ name, cls: filter === k ? 'on' : '', pick: () => this.setState({ filter: k }) })),
      sizes: [['s', 'Grid'], ['l', 'Large']].map(([k, name]) => ({ name, cls: size === k ? 'on' : '', pick: () => this.setState({ size: k }) })),
      gridCls: 'grid ' + size,
      frames: list.map((f) => ({
        id: f.id, time: f.time, bp: f.bp, thumbCls: pc.thumb + (f.dets.length ? '' : ' clean'), boxes: boxesOf(f),
        src: srcBadge(f.src)[0], srcCls: srcBadge(f.src)[1], hasDets: f.dets.length > 0, n: f.dets.length,
        selCls: f.idx === cur0.idx ? 'sel' : '', pick: () => this.setState({ sel: f.idx }),
      })),
      cur,
      overlays: [['boxes', 'Boxes'], ['labels', 'Labels'], ['heat', 'Heat']].map(([k, name]) => ({ name, cls: ov[k] ? 'on' : '', pick: tog(k) })),
      showBoxes: ov.boxes, showLabels: ov.labels, showHeat: ov.heat,
      prev: step(-1), next: step(1),
      lanes: Array.from({ length: 7 }, (_, i) => ({ x1: 30, x2: 376, y: 12 + i * 14 })),
    };
  }

  componentDidMount() {
    this._syncPillar();
    this._alive = true;
    this._startClock();
    const i = this._frames(this.state.pillar).findIndex((f) => f.dets.length);
    this.setState({ sel: Math.max(0, i) });
  }

  componentWillUnmount() { this._alive = false; this._stopClock(); }



  render() {
    const v = this.renderVals();
    return (
      <div className="pg-frames ds">
        <div className="app">
          <AppRail active="missions" />
          <TopBar crumbs={["Missions","Frames"]} pillars={v.pillars} />
          <main className="main">
            <div className="page">
              <div className="page-head">
                <div>
                  <div className="kicker" style={{ color: `${v.pc?.color ?? ""}` }}>
                    <i></i>
                    {v.pc?.mission}{" · frames"}
                  </div>
                  <h1 className="h1" style={{ marginTop: "10px" }}>
                    {"Frame gallery"}
                  </h1>
                </div>
                <div className="meta">
                  {v.pc?.frames}{" frames · "}{v.shown}{" shown · stylised sample imagery"}
                </div>
                <div className="acts">
                  <div className="segs">
                    {(v.filters || []).map((f, $index) => (
                      <React.Fragment key={$index}>
                      <button className={f?.cls} onClick={f?.pick}>
                        {f?.name}
                      </button>
                      </React.Fragment>
                    ))}
                  </div>
                  <div className="segs">
                    {(v.sizes || []).map((f, $index) => (
                      <React.Fragment key={$index}>
                      <button className={f?.cls} onClick={f?.pick}>
                        {f?.name}
                      </button>
                      </React.Fragment>
                    ))}
                  </div>
                  <Link className="btn btn-ghost" href={'/missions/' + v.pc.mission}>
                    {"← Mission twin"}
                  </Link>
                </div>
              </div>
              <div className="cols">
                <section className="panel">
                  <div className="scroll" style={{ flex: "1" }}>
                    <div className={v.gridCls}>
                      {(v.frames || []).map((f, $index) => (
                        <React.Fragment key={$index}>
                        <button className={`fc ${f?.selCls ?? ""}`} onClick={f?.pick}>
                          <div className={`thumb ${f?.thumbCls ?? ""}`} style={{ backgroundPosition: `${f?.bp ?? ""}` }}>
                            {(f?.boxes || []).map((b, $index) => (
                              <React.Fragment key={$index}>
                              <span className="box" style={{ left: `${b?.l ?? ""}`, top: `${b?.t ?? ""}`, width: `${b?.w ?? ""}`, height: `${b?.h ?? ""}`, color: `${b?.color ?? ""}` }}></span>
                              </React.Fragment>
                            ))}
                            <span className="fc-src">
                              <span className={`badge ${f?.srcCls ?? ""}`}>
                                {f?.src}
                              </span>
                            </span>
                            {f?.hasDets ? (
                              <>
                              <span className="fc-n">
                                {f?.n}
                              </span>
                              </>
                            ) : null}
                          </div>
                          <div className="fc-meta">
                            <span>
                              {f?.id}
                            </span>
                            <em>
                              {f?.time}
                            </em>
                          </div>
                        </button>
                        </React.Fragment>
                      ))}
                    </div>
                  </div>
                </section>
                <section className="panel">
                  <div className="v-bar">
                    <div className="ph-l">
                      <span className="lbl strong">
                        {v.cur?.id}
                      </span>
                      <span className={`badge ${v.cur?.srcCls ?? ""}`}>
                        {v.cur?.src}
                      </span>
                    </div>
                    <div className="segs">
                      {(v.overlays || []).map((o, $index) => (
                        <React.Fragment key={$index}>
                        <button className={o?.cls} onClick={o?.pick}>
                          {o?.name}
                        </button>
                        </React.Fragment>
                      ))}
                    </div>
                    <div className="v-nav">
                      <button onClick={v.prev}>
                        {"‹"}
                      </button>
                      <button onClick={v.next}>
                        {"›"}
                      </button>
                    </div>
                  </div>
                  <div className="scroll v-body">
                    <div className={`viewer thumb ${v.cur?.thumbCls ?? ""}`} style={{ backgroundPosition: `${v.cur?.bp ?? ""}` }}>
                      {v.showHeat ? (
                        <>
                        <div className="heat" style={{ background: `${v.cur?.heat ?? ""}` }}></div>
                        </>
                      ) : null}
                      {v.showBoxes ? (
                        <>
                        <div>
                          {(v.cur?.boxes || []).map((b, $index) => (
                            <React.Fragment key={$index}>
                            <span className="box" style={{ left: `${b?.l ?? ""}`, top: `${b?.t ?? ""}`, width: `${b?.w ?? ""}`, height: `${b?.h ?? ""}`, color: `${b?.color ?? ""}` }}>
                              {v.showLabels ? (
                                <>
                                <b>
                                  {b?.label}
                                </b>
                                </>
                              ) : null}
                            </span>
                            </React.Fragment>
                          ))}
                        </div>
                        </>
                      ) : null}
                    </div>
                    {(v.cur?.detRows || []).map((d, $index) => (
                      <React.Fragment key={$index}>
                      <div className="li dl" style={{ cursor: "default" }}>
                        <i className={`dia ${d?.sevCls ?? ""}`}></i>
                        <span style={{ minWidth: "0" }}>
                          <span className="li-t" style={{ fontSize: "14px" }}>
                            {d?.cls}{" · "}{d?.confStr}
                          </span>
                          <span className="li-s">
                            {"BBox "}{d?.bboxStr}{" · "}{d?.loc}
                          </span>
                        </span>
                        <span className={`chip ${d?.statusCls ?? ""}`}>
                          {d?.status}
                        </span>
                      </div>
                      </React.Fragment>
                    ))}
                    {v.cur?.noDets ? (
                      <>
                      <div className="note" style={{ borderTop: "0" }}>
                        {"No detections above the 0.50 threshold in this frame"}
                      </div>
                      </>
                    ) : null}
                    {(v.cur?.meta || []).map((m, $index) => (
                      <React.Fragment key={$index}>
                      <div className="kvl-row">
                        <span>
                          {m?.k}
                        </span>
                        <b>
                          {m?.v}
                        </b>
                        <i></i>
                      </div>
                      </React.Fragment>
                    ))}
                    <svg className="minimap" width="406" height="120" viewBox="0 0 406 120">
                      {(v.lanes || []).map((l, $index) => (
                        <React.Fragment key={$index}>
                        <line x1={l?.x1} y1={l?.y} x2={l?.x2} y2={l?.y} stroke="#FFB547" strokeWidth="1.2" strokeDasharray="4 3" opacity="0.7"></line>
                        </React.Fragment>
                      ))}
                      <circle cx={v.cur?.mx} cy={v.cur?.my} r="9" fill="none" stroke="#5CE1FF" strokeWidth="1.2" opacity="0.5"></circle>
                      <rect x={v.cur?.mxr} y={v.cur?.myr} width="8" height="8" fill="#5CE1FF" transform={v.cur?.rot}></rect>
                      <text x="8" y="114" fontFamily="IBM Plex Mono, monospace" fontSize="9" fill="#62738F">
                        {"FLIGHT PATH · FRAME POSITION (APPROX.)"}
                      </text>
                    </svg>
                  </div>
                </section>
              </div>
            </div>
          </main>
        </div>
      </div>
    );
  }
}

export default View;
