'use client';
/* eslint-disable */
// Generated by scripts/convert-designs.mjs from design/landing-page/MissionPlanner.template.html — edit the design or the patches, then re-run.
import React from 'react';
import Base from './_base';
import { AppRail, TopBar } from '@/components/chrome';
import { getPillar, setPillar, readJSON, writeJSON, signIn, signOut, saveSession, downloadFile } from '@/lib/store';
import { API_URL, pingApi, inferFile, submitRequest } from '@/lib/api';
import { sessionData } from '@/lib/session';
import './css/MissionPlanner.css';

class View extends Base {
  constructor(props) {
    super(props);
    this.state = { pillar: 'energy', alt: 42, side: 70, front: 80, heading: 0, speed: 8, pattern: 'lawn', cam: 'rgb', view: '3d', showExport: false, s: null };
    this._poly = View.DEFAULT_POLY.map((p) => p.slice());
  }

  static get DEFAULT_POLY() { return [[-50, -34], [52, -38], [56, 36], [-46, 40]]; }

  _cams() {
    return {
      rgb: { name: 'RGB 20 MP', sw: 13.2, sh: 8.8, f: 8.8, px: 5472 },
      ms: { name: 'Multispectral', sw: 4.8, sh: 3.6, f: 5.74, px: 1280 },
      lwir: { name: 'LWIR 640', sw: 10.88, sh: 8.7, f: 13, px: 640 },
    };
  }

  // Lawnmower (or crosshatch) lanes clipped to the convex area polygon. World unit = 1.5 m.
  _plan() {
    const st = this.state, cam = this._cams()[st.cam];
    const footW = (st.alt * cam.sw) / cam.f, footH = (st.alt * cam.sh) / cam.f;
    const spacing = footW * (1 - st.side / 100), interval = footH * (1 - st.front / 100);
    const U = 4, poly = this._poly;
    const lanesFor = (deg) => {
      const r = (deg * Math.PI) / 180, c = Math.cos(r), s = Math.sin(r);
      const rot = poly.map(([x, z]) => [x * c + z * s, -x * s + z * c]);
      const zs = rot.map((p) => p[1]), minZ = Math.min(...zs), maxZ = Math.max(...zs);
      const out = [];
      let dir = 1;
      for (let z = minZ + spacing / U / 2; z < maxZ; z += spacing / U) {
        const xs = [];
        for (let i = 0; i < rot.length; i++) {
          const p = rot[i], q = rot[(i + 1) % rot.length];
          if ((p[1] <= z && q[1] > z) || (q[1] <= z && p[1] > z)) xs.push(p[0] + ((z - p[1]) / (q[1] - p[1])) * (q[0] - p[0]));
        }
        if (xs.length < 2) continue;
        xs.sort((m, n) => m - n);
        const a0 = dir > 0 ? xs[0] : xs[xs.length - 1], a1 = dir > 0 ? xs[xs.length - 1] : xs[0];
        const back = ([x, zz]) => [x * c - zz * s, x * s + zz * c];
        out.push([back([a0, z]), back([a1, z])]);
        dir = -dir;
      }
      return out;
    };
    let lanes = lanesFor(st.heading);
    if (st.pattern === 'cross') lanes = lanes.concat(lanesFor(st.heading + 90));
    let len = 0, photos = 0;
    lanes.forEach(([p, q], i) => {
      const l = Math.hypot(q[0] - p[0], q[1] - p[1]) * U;
      len += l;
      photos += Math.floor(l / interval) + 1;
      if (i > 0) { const pr = lanes[i - 1][1]; len += Math.hypot(p[0] - pr[0], p[1] - pr[1]) * U; }
    });
    let area = 0;
    for (let i = 0; i < poly.length; i++) { const p = poly[i], q = poly[(i + 1) % poly.length]; area += p[0] * q[1] - q[0] * p[1]; }
    area = (Math.abs(area) / 2) * U * U / 10000;
    const seconds = len / st.speed + lanes.length * 6 + (2 * st.alt) / 3;
    const minutes = seconds / 60, USABLE = 22;
    return { lanes, spacing, interval, footW, footH, len, photos, area, minutes, batteries: Math.max(1, Math.ceil(minutes / USABLE)), gsd: ((footW * 100) / cam.px) };
  }

  renderVals() {
    const D = this._data();
    const st = this.state;
    const pc = D.P[st.pillar];
    const site = D.sites.find((x) => x.key === { energy: 'rsp', agri: 'kfb', rescue: 'ads' }[st.pillar]);
    const pl = this._plan();
    this._planCache = pl;
    const opt = (key, list, fmt) => list.map(([v, name]) => ({ name, cls: st[key] === v ? 'on' : '', pick: () => this.setState({ [key]: v }) }));
    const group = (name, key, list, value) => ({ name, value, opts: opt(key, list) });
    const cam = this._cams()[st.cam];
    const lat0 = (z) => (22.3 - (z * 4) / 111320).toFixed(5), lon0 = (x) => (70.8 + (x * 4) / 102990).toFixed(5);
    const manifest = [{ k: '{', p: '', v: '' }];
    let idx = 0;
    pl.lanes.slice(0, 2).forEach(([p, q]) => {
      const hdg = ((Math.atan2(q[0] - p[0], -(q[1] - p[1])) * 180) / Math.PI + 360) % 360;
      for (let j = 0; j < 3; j++) {
        const t = j / 2, x = p[0] + (q[0] - p[0]) * t, z = p[1] + (q[1] - p[1]) * t;
        idx++;
        manifest.push({ k: '  "frame_' + String(idx).padStart(4, '0') + '.jpg"', p: ': { ', v: '"lat": ' + lat0(z) + ', "lng": ' + lon0(x) + ', "alt": ' + st.alt.toFixed(1) + ', "heading": ' + hdg.toFixed(1) + ' },' });
      }
    });
    manifest.push({ k: '  …', p: '', v: '' }, { k: '}', p: '', v: '' });
    return {
      pillars: this._pillarTabs(st.pillar, (k) => this.setState({ pillar: k, cam: k === 'agri' ? 'ms' : k === 'rescue' ? 'lwir' : 'rgb', alt: k === 'rescue' ? 30 : 42 })),
      pc, site,
      groups: [
        group('Pattern', 'pattern', [['lawn', 'Lawnmower'], ['cross', 'Crosshatch']], st.pattern === 'lawn' ? 'single pass' : 'double pass'),
        group('Altitude AGL', 'alt', [[30, '30'], [42, '42'], [60, '60'], [90, '90']], st.alt + ' m'),
        group('Side overlap', 'side', [[60, '60%'], [70, '70%'], [80, '80%']], st.side + '%'),
        group('Front overlap', 'front', [[70, '70%'], [80, '80%'], [85, '85%']], st.front + '%'),
        group('Lane heading', 'heading', [[0, '0°'], [45, '45°'], [90, '90°'], [135, '135°']], st.heading + '°'),
        group('Speed', 'speed', [[5, '5'], [8, '8'], [12, '12']], st.speed + ' m/s'),
        group('Payload', 'cam', [['rgb', 'RGB'], ['ms', 'Multi'], ['lwir', 'LWIR']], cam.name),
      ],
      views: [['3d', '3D'], ['top', 'Top']].map(([k, name]) => ({ name, cls: st.view === k ? 'on' : '', pick: () => this.setState({ view: k }) })),
      s: {
        area: pl.area.toFixed(1), spacing: pl.spacing.toFixed(1), interval: pl.interval.toFixed(1), lanes: pl.lanes.length,
        km: (pl.len / 1000).toFixed(2), minutes: pl.minutes.toFixed(1), photos: pl.photos.toLocaleString('en-US'), gsd: pl.gsd.toFixed(2),
        batteries: pl.batteries, batTxt: pl.batteries > 1 ? 'amber' : '',
        batLabel: pl.batteries > 1 ? pl.batteries + ' flights needed' : 'Single flight', batCls: pl.batteries > 1 ? 'st-warn' : 'st-resolved',
      },
      checks: [
        ['Area inside site boundary', 'sev-ok'],
        [st.alt <= 120 ? 'Altitude ' + st.alt + ' m AGL · [CHECK LOCAL LIMIT]' : 'Altitude above 120 m', st.alt <= 120 ? 'sev-warn' : 'sev-crit'],
        ['Airspace permission · [PERMISSION REF]', 'sev-warn'],
        [pl.batteries > 1 ? 'Split into ' + pl.batteries + ' flights (22 min usable · sample)' : 'Fits one battery (22 min usable · sample)', pl.batteries > 1 ? 'sev-warn' : 'sev-ok'],
      ].map(([text, dia]) => ({ text, dia })),
      showExport: st.showExport,
      openExport: () => this.setState({ showExport: true }),
      closeExport: () => this.setState({ showExport: false }),
      resetArea: () => { this._poly = View.DEFAULT_POLY.map((p) => p.slice()); this.setState({ s: Date.now() }); },
      manifest,
      downloadManifest: () => this._downloadManifest(),
    };
  }

  // Full manifest: one entry per planned photo, same shape as backend/telemetry.py GOLDEN_DEMO_MANIFEST.
  _downloadManifest() {
    const pl = this._plan(), st = this.state, out = {};
    let idx = 0;
    pl.lanes.forEach(([p, q]) => {
      const len = Math.hypot(q[0] - p[0], q[1] - p[1]) * 4, n = Math.floor(len / pl.interval) + 1;
      const hdg = ((Math.atan2(q[0] - p[0], -(q[1] - p[1])) * 180) / Math.PI + 360) % 360;
      for (let j = 0; j < n; j++) {
        const t = n > 1 ? j / (n - 1) : 0, x = p[0] + (q[0] - p[0]) * t, z = p[1] + (q[1] - p[1]) * t;
        idx++;
        out['frame_' + String(idx).padStart(4, '0') + '.jpg'] = { lat: +(22.3 - (z * 4) / 111320).toFixed(6), lng: +(70.8 + (x * 4) / 102990).toFixed(6), alt: st.alt, heading: +hdg.toFixed(1) };
      }
    });
    downloadFile('manifest_' + st.pillar + '_' + idx + '_frames.json', JSON.stringify(out, null, 2));
    this.setState({ showExport: false });
  }

  componentDidMount() {
    this._syncPillar();
    this._alive = true;
    this._startClock();
    this._boot(0);
  }

  componentWillUnmount() {
    this._alive = false;
    this._stopClock();
    if (this._raf) cancelAnimationFrame(this._raf);
    if (this._planScene) this._planScene.destroy();
  }

  _boot(tries) {
    if (!this._alive) return;
    const canvas = document.querySelector('[data-gl="plan"]');
    if (!canvas) { if (tries < 120) requestAnimationFrame(() => this._boot(tries + 1)); return; }
    this._planScene = this._plannerScene(this._engine(), canvas, document.querySelector('[data-gl-labels="plan"]'));
    this._loop([this._planScene]);
  }

  // Terrain with a draggable 4-corner area, planned lanes, capture points and a footprint preview.
  _plannerScene(K, canvas, labelsEl) {
    const R = K.renderer(canvas, [0.016, 0.043, 0.11]);
    if (!R) return null;
    const { Batch, COL, a, lerp, clamp, smooth } = K;
    const self = this;
    const ground = (x, z) => { const m = smooth(60, 140, Math.hypot(x, z)); return m * (8 * Math.sin(x * 0.03 + 1) * Math.cos(z * 0.03) + 14 * m); };
    const tb = new Batch();
    for (let g = -160; g <= 160; g += 8) for (let u = -160; u < 160; u += 4) {
      const c = (h) => [lerp(0.13, 0.42, smooth(-2, 24, h)), lerp(0.3, 0.68, smooth(-2, 24, h)), lerp(0.72, 1, smooth(-2, 24, h)), 0.16 + 0.26 * smooth(-2, 24, h)];
      const h1 = ground(u, g), h2 = ground(u + 4, g), k1 = ground(g, u), k2 = ground(g, u + 4);
      tb.line(u, h1, g, u + 4, h2, g, c(h1), c(h2));
      tb.line(g, k1, u, g, k2, u + 4, c(k1), c(k2));
    }
    const terrain = new Float32Array(tb.a);
    const inv = (m) => {
      const o = new Array(16);
      o[0] = m[5] * m[10] * m[15] - m[5] * m[11] * m[14] - m[9] * m[6] * m[15] + m[9] * m[7] * m[14] + m[13] * m[6] * m[11] - m[13] * m[7] * m[10];
      o[4] = -m[4] * m[10] * m[15] + m[4] * m[11] * m[14] + m[8] * m[6] * m[15] - m[8] * m[7] * m[14] - m[12] * m[6] * m[11] + m[12] * m[7] * m[10];
      o[8] = m[4] * m[9] * m[15] - m[4] * m[11] * m[13] - m[8] * m[5] * m[15] + m[8] * m[7] * m[13] + m[12] * m[5] * m[11] - m[12] * m[7] * m[9];
      o[12] = -m[4] * m[9] * m[14] + m[4] * m[10] * m[13] + m[8] * m[5] * m[14] - m[8] * m[6] * m[13] - m[12] * m[5] * m[10] + m[12] * m[6] * m[9];
      o[1] = -m[1] * m[10] * m[15] + m[1] * m[11] * m[14] + m[9] * m[2] * m[15] - m[9] * m[3] * m[14] - m[13] * m[2] * m[11] + m[13] * m[3] * m[10];
      o[5] = m[0] * m[10] * m[15] - m[0] * m[11] * m[14] - m[8] * m[2] * m[15] + m[8] * m[3] * m[14] + m[12] * m[2] * m[11] - m[12] * m[3] * m[10];
      o[9] = -m[0] * m[9] * m[15] + m[0] * m[11] * m[13] + m[8] * m[1] * m[15] - m[8] * m[3] * m[13] - m[12] * m[1] * m[11] + m[12] * m[3] * m[9];
      o[13] = m[0] * m[9] * m[14] - m[0] * m[10] * m[13] - m[8] * m[1] * m[14] + m[8] * m[2] * m[13] + m[12] * m[1] * m[10] - m[12] * m[2] * m[9];
      o[2] = m[1] * m[6] * m[15] - m[1] * m[7] * m[14] - m[5] * m[2] * m[15] + m[5] * m[3] * m[14] + m[13] * m[2] * m[7] - m[13] * m[3] * m[6];
      o[6] = -m[0] * m[6] * m[15] + m[0] * m[7] * m[14] + m[4] * m[2] * m[15] - m[4] * m[3] * m[14] - m[12] * m[2] * m[7] + m[12] * m[3] * m[6];
      o[10] = m[0] * m[5] * m[15] - m[0] * m[7] * m[13] - m[4] * m[1] * m[15] + m[4] * m[3] * m[13] + m[12] * m[1] * m[7] - m[12] * m[3] * m[5];
      o[14] = -m[0] * m[5] * m[14] + m[0] * m[6] * m[13] + m[4] * m[1] * m[14] - m[4] * m[2] * m[13] - m[12] * m[1] * m[6] + m[12] * m[2] * m[5];
      o[3] = -m[1] * m[6] * m[11] + m[1] * m[7] * m[10] + m[5] * m[2] * m[11] - m[5] * m[3] * m[10] - m[9] * m[2] * m[7] + m[9] * m[3] * m[6];
      o[7] = m[0] * m[6] * m[11] - m[0] * m[7] * m[10] - m[4] * m[2] * m[11] + m[4] * m[3] * m[10] + m[8] * m[2] * m[7] - m[8] * m[3] * m[6];
      o[11] = -m[0] * m[5] * m[11] + m[0] * m[7] * m[9] + m[4] * m[1] * m[11] - m[4] * m[3] * m[9] - m[8] * m[1] * m[7] + m[8] * m[3] * m[5];
      o[15] = m[0] * m[5] * m[10] - m[0] * m[6] * m[9] - m[4] * m[1] * m[10] + m[4] * m[2] * m[9] + m[8] * m[1] * m[6] - m[8] * m[2] * m[5];
      const det = m[0] * o[0] + m[1] * o[4] + m[2] * o[8] + m[3] * o[12];
      return o.map((v) => v / (det || 1));
    };
    const tags = [0, 1, 2, 3].map((i) => {
      if (!labelsEl) return null;
      const el = document.createElement('div');
      el.className = 'gl-tag';
      el.style.color = '#5CE1FF';
      el.textContent = 'P' + (i + 1);
      labelsEl.appendChild(el);
      return el;
    });
    const home = labelsEl ? document.createElement('div') : null;
    if (home) { home.className = 'gl-tag'; home.style.color = '#7BE3A0'; home.textContent = 'HOME'; labelsEl.appendChild(home); }

    let M = null, drag = null, orbit = null, yaw = 0.35, pitch = 0.9, pv = 0.9, handles = [], lastPush = 0;
    const local = (e) => { const r = canvas.getBoundingClientRect(); return [(e.clientX - r.left) * canvas.clientWidth / Math.max(1, r.width), (e.clientY - r.top) * canvas.clientHeight / Math.max(1, r.height)]; };
    const toGround = (px, py) => {
      if (!M) return null;
      const I = inv(M), x = (px / R.w) * 2 - 1, y = 1 - (py / R.h) * 2;
      const un = (zc) => { const v = [I[0] * x + I[4] * y + I[8] * zc + I[12], I[1] * x + I[5] * y + I[9] * zc + I[13], I[2] * x + I[6] * y + I[10] * zc + I[14], I[3] * x + I[7] * y + I[11] * zc + I[15]]; return [v[0] / v[3], v[1] / v[3], v[2] / v[3]]; };
      const n = un(-1), f = un(1);
      if (Math.abs(f[1] - n[1]) < 1e-6) return null;
      const t = -n[1] / (f[1] - n[1]);
      return [n[0] + (f[0] - n[0]) * t, n[2] + (f[2] - n[2]) * t];
    };
    const onDown = (e) => {
      const [px, py] = local(e);
      let best = -1, bd = 22;
      handles.forEach((h, i) => { const d = Math.hypot(h[0] - px, h[1] - py); if (d < bd) { bd = d; best = i; } });
      if (best >= 0) drag = best; else orbit = { x: e.clientX, y: e.clientY, yaw, pitch };
    };
    const onMove = (e) => {
      if (drag !== null) {
        const [px, py] = local(e), g = toGround(px, py);
        if (g) { self._poly[drag] = [clamp(g[0], -110, 110), clamp(g[1], -80, 80)]; }
        const now = Date.now();
        if (now - lastPush > 90) { lastPush = now; self.setState({ s: now }); }
      } else if (orbit) {
        yaw = orbit.yaw - (e.clientX - orbit.x) * 0.005;
        pitch = clamp(orbit.pitch + (e.clientY - orbit.y) * 0.004, 0.35, 1.4);
      }
    };
    const onUp = () => { if (drag !== null) self.setState({ s: Date.now() }); drag = null; orbit = null; };
    canvas.addEventListener('pointerdown', onDown);
    window.addEventListener('pointermove', onMove);
    window.addEventListener('pointerup', onUp);

    return {
      destroy() { canvas.removeEventListener('pointerdown', onDown); window.removeEventListener('pointermove', onMove); window.removeEventListener('pointerup', onUp); },
      frame(t, dt) {
        const asp = R.resize();
        pv = lerp(pv, self.state.view === 'top' ? 1.45 : pitch, Math.min(1, dt * 3));
        const cy = self.state.view === 'top' ? 0 : yaw, rad = 175 * Math.max(1, 1.2 / asp);
        const eye = [rad * Math.cos(pv) * Math.sin(cy), rad * Math.sin(pv), rad * Math.cos(pv) * Math.cos(cy)];
        M = K.camera(asp, eye, [0, 0, 0], 0.7);
        R.begin(M, eye, 170, 420);
        R.draw(terrain, 'lines', 'add');
        const pl = self._planCache || self._plan();
        const poly = self._poly, alt = (self.state.alt / 1.5) * 0.5 + 6;
        const ln = new Batch(), fill = new Batch(), pts = new Batch();
        const gy = (x, z) => ground(x, z) + 0.4;
        fill.tri([poly[0][0], gy(...poly[0]), poly[0][1]], [poly[1][0], gy(...poly[1]), poly[1][1]], [poly[2][0], gy(...poly[2]), poly[2][1]], a(COL.cyan, 0.07));
        fill.tri([poly[0][0], gy(...poly[0]), poly[0][1]], [poly[2][0], gy(...poly[2]), poly[2][1]], [poly[3][0], gy(...poly[3]), poly[3][1]], a(COL.cyan, 0.07));
        handles = [];
        poly.forEach((p, i) => {
          const q = poly[(i + 1) % poly.length];
          for (let k = 0; k < 20; k++) {
            if (k % 2) continue;
            const x1 = lerp(p[0], q[0], k / 20), z1 = lerp(p[1], q[1], k / 20), x2 = lerp(p[0], q[0], (k + 1) / 20), z2 = lerp(p[1], q[1], (k + 1) / 20);
            ln.line(x1, gy(x1, z1), z1, x2, gy(x2, z2), z2, a(COL.cyan, 0.9));
          }
          const y = gy(p[0], p[1]), hot = drag === i;
          const dm = hot ? 3.2 : 2.4;
          [[dm, 0], [0, dm], [-dm, 0], [0, -dm]].forEach(([ox, oz], j, arr) => { const n = arr[(j + 1) % 4]; ln.line(p[0] + ox, y, p[1] + oz, p[0] + n[0], y, p[1] + n[1], a(hot ? COL.white : COL.cyan, 1)); });
          ln.line(p[0], y, p[1], p[0], y + 8, p[1], a(COL.cyan, hot ? 1 : 0.5), a(COL.cyan, 0));
          pts.v(p[0], y, p[1], a(hot ? COL.white : COL.cyan, 1));
          const sp = K.project(M, p[0], y, p[1], R.w, R.h);
          handles.push(sp || [-999, -999]);
          const tp = K.project(M, p[0], y + 9, p[1], R.w, R.h);
          if (tags[i]) { if (tp) { tags[i].style.opacity = '1'; tags[i].style.transform = 'translate(' + tp[0].toFixed(1) + 'px,' + tp[1].toFixed(1) + 'px) translate(-50%,-100%)'; } else tags[i].style.opacity = '0'; }
        });
        const interval = pl.interval / 4;
        let prev = null;
        pl.lanes.forEach(([p, q], li) => {
          if (prev) ln.line(prev[0], alt, prev[1], p[0], alt, p[1], a(COL.cyan, 0.35));
          const len = Math.hypot(q[0] - p[0], q[1] - p[1]), n = Math.max(1, Math.floor(len / 2.2));
          for (let k = 0; k < n; k += 2) {
            const x1 = lerp(p[0], q[0], k / n), z1 = lerp(p[1], q[1], k / n), x2 = lerp(p[0], q[0], Math.min(1, (k + 1) / n)), z2 = lerp(p[1], q[1], Math.min(1, (k + 1) / n));
            ln.line(x1, alt, z1, x2, alt, z2, a(COL.cyan, 0.85));
          }
          const shots = Math.floor(len / Math.max(0.5, interval));
          for (let k = 0; k <= shots && k < 80; k += 1) { const f = shots ? k / shots : 0; pts.v(lerp(p[0], q[0], f), alt, lerp(p[1], q[1], f), a(COL.white, 0.35)); }
          prev = q;
        });
        if (pl.lanes.length) {
          const start = pl.lanes[0][0], hx = start[0] - 8, hz = start[1] - 8, hy = gy(hx, hz);
          ln.ring(hx, hy, hz, 3, 20, a(COL.green, 1));
          ln.line(hx, hy, hz, start[0], alt, start[1], a(COL.green, 0.5));
          const hp = K.project(M, hx, hy + 4, hz, R.w, R.h);
          if (home) { if (hp) { home.style.opacity = '1'; home.style.transform = 'translate(' + hp[0].toFixed(1) + 'px,' + hp[1].toFixed(1) + 'px) translate(-50%,-100%)'; } else home.style.opacity = '0'; }
          // animated footprint sweep along the first lanes
          const total = pl.lanes.length, li = Math.floor((t * 0.25) % total), [p, q] = pl.lanes[li], f = (t * 0.25) % 1;
          const cx = lerp(p[0], q[0], f), cz = lerp(p[1], q[1], f), dir = Math.atan2(q[1] - p[1], q[0] - p[0]);
          const hw = pl.footH / 8, hl = pl.footW / 8, c = Math.cos(dir), s = Math.sin(dir);
          const cor = [[-hw, -hl], [hw, -hl], [hw, hl], [-hw, hl]].map(([lx, lz]) => [cx + lx * c - lz * s, cz + lx * s + lz * c]);
          for (let k = 0; k < 4; k++) {
            const u = cor[k], v = cor[(k + 1) % 4];
            ln.line(u[0], gy(u[0], u[1]), u[1], v[0], gy(v[0], v[1]), v[1], a(COL.warn, 0.9));
            ln.line(cx, alt, cz, u[0], gy(u[0], u[1]), u[1], a(COL.warn, 0.3), a(COL.warn, 0.05));
          }
          self._drawDrone(K, ln, cx, alt + 1, cz, dir, 1.1, t, { legs: false });
        }
        R.draw(fill, 'tris', 'alpha');
        R.draw(ln, 'lines', 'add');
        R.draw(pts, 'points', 'add', 22);
      },
    };
  }



  render() {
    const v = this.renderVals();
    return (
      <div className="pg-mission-planner ds">
        <div className="app">
          <AppRail active="missions" />
          <TopBar crumbs={["Missions","Mission planner"]} pillars={v.pillars} />
          <main className="main">
            <div className="page">
              <div className="page-head">
                <div>
                  <div className="kicker" style={{ color: `${v.pc?.color ?? ""}` }}>
                    <i></i>
                    {"Mission planner · "}{v.pc?.name}
                  </div>
                  <h1 className="h1" style={{ marginTop: "10px" }}>
                    {"Plan survey"}
                  </h1>
                </div>
                <div className="meta">
                  {v.site?.name}{" · draft · not submitted"}
                </div>
                <div className="acts">
                  <button className="btn btn-ghost" onClick={() => alert('Mission draft plan saved to browser storage.')}>
                    {"Save draft"}
                  </button>
                  <button className="btn btn-primary" onClick={v.openExport}>
                    {"Export manifest"}
                  </button>
                </div>
              </div>
              <div className="cols">
                <section className="panel">
                  <div className="ph">
                    <span className="lbl strong">
                      {"Flight parameters"}
                    </span>
                    <button className="btn btn-ghost btn-sm" onClick={v.resetArea}>
                      {"Reset area"}
                    </button>
                  </div>
                  <div className="scroll params">
                    {(v.groups || []).map((g, $index) => (
                      <React.Fragment key={$index}>
                      <div className="prm">
                        <span className="lbl">
                          {g?.name}
                          <em>
                            {g?.value}
                          </em>
                        </span>
                        <div className="segs">
                          {(g?.opts || []).map((o, $index) => (
                            <React.Fragment key={$index}>
                            <button className={o?.cls} onClick={o?.pick}>
                              {o?.name}
                            </button>
                            </React.Fragment>
                          ))}
                        </div>
                      </div>
                      </React.Fragment>
                    ))}
                    <div className="prm">
                      <div className="warnbox">
                        <i className="dia sev-warn"></i>
                        <span>
                          {"Camera footprints use a sample sensor model for each payload. Replace with the registered aircraft's calibrated values."}
                        </span>
                      </div>
                    </div>
                  </div>
                </section>
                <section className="panel">
                  <div className="ph">
                    <div className="ph-l">
                      <span className="lbl strong">
                        {"Survey area"}
                      </span>
                      <span className="badge b-man">
                        {"Planned · not flown"}
                      </span>
                    </div>
                    <div className="segs">
                      {(v.views || []).map((v, $index) => (
                        <React.Fragment key={$index}>
                        <button className={v?.cls} onClick={v?.pick}>
                          {v?.name}
                        </button>
                        </React.Fragment>
                      ))}
                    </div>
                  </div>
                  <div className="view3d">
                    <canvas className="gl" data-gl="plan"></canvas>
                    <div className="gl-labels" data-gl-labels="plan"></div>
                    <div className="ov ov-tl glass hint">
                      <span className="lbl">
                        {"Drag the corner handles to reshape the area"}
                      </span>
                    </div>
                    <div className="ov ov-bl readout">
                      {"AREA "}
                      <b>
                        {v.s?.area}{" ha"}
                      </b>
                      {" · LANE SPACING "}
                      <b>
                        {v.s?.spacing}{" m"}
                      </b>
                      {" · PHOTO EVERY "}
                      <b>
                        {v.s?.interval}{" m"}
                      </b>
                    </div>
                  </div>
                </section>
                <section className="panel">
                  <div className="ph">
                    <span className="lbl strong">
                      {"Plan summary"}
                    </span>
                    <span className={`chip ${v.s?.batCls ?? ""}`}>
                      {v.s?.batLabel}
                    </span>
                  </div>
                  <div className="stats">
                    <div className="st">
                      <span className="lbl">
                        {"Lanes"}
                      </span>
                      <b>
                        {v.s?.lanes}
                      </b>
                    </div>
                    <div className="st">
                      <span className="lbl">
                        {"Path"}
                      </span>
                      <b>
                        {v.s?.km}
                        <small>
                          {"km"}
                        </small>
                      </b>
                    </div>
                    <div className="st">
                      <span className="lbl">
                        {"Flight time"}
                      </span>
                      <b>
                        {v.s?.minutes}
                        <small>
                          {"min"}
                        </small>
                      </b>
                    </div>
                    <div className="st">
                      <span className="lbl">
                        {"Photos"}
                      </span>
                      <b>
                        {v.s?.photos}
                      </b>
                    </div>
                    <div className="st">
                      <span className="lbl">
                        {"GSD"}
                      </span>
                      <b>
                        {v.s?.gsd}
                        <small>
                          {"cm/px"}
                        </small>
                      </b>
                    </div>
                    <div className="st">
                      <span className="lbl">
                        {"Batteries"}
                      </span>
                      <b className={v.s?.batTxt}>
                        {v.s?.batteries}
                      </b>
                    </div>
                  </div>
                  <div className="checks">
                    {(v.checks || []).map((c, $index) => (
                      <React.Fragment key={$index}>
                      <div className="chk">
                        <i className={`dia ${c?.dia ?? ""}`}></i>
                        <span>
                          {c?.text}
                        </span>
                      </div>
                      </React.Fragment>
                    ))}
                  </div>
                  <div className="sum-acts">
                    <button className="btn btn-primary" onClick={v.openExport}>
                      {"Export manifest JSON"}
                    </button>
                    <button className="btn btn-ghost" disabled={true}>
                      {"Send to aircraft · none linked"}
                    </button>
                  </div>
                </section>
              </div>
            </div>
            {v.showExport ? (
              <>
              <div className="modal-bg">
                <section className="panel modal">
                  <div className="ph">
                    <div className="ph-l">
                      <span className="lbl strong">
                        {"Telemetry manifest preview"}
                      </span>
                      <span className="badge b-man">
                        {"Manifest"}
                      </span>
                    </div>
                    <span className="lbl">
                      {v.s?.photos}{" entries · first 6 shown"}
                    </span>
                  </div>
                  <div className="scroll code">
                    {(v.manifest || []).map((l, $index) => (
                      <React.Fragment key={$index}>
                      <div>
                        <span className="j-key">
                          {l?.k}
                        </span>
                        <span className="j-pun">
                          {l?.p}
                        </span>
                        <span className="j-num">
                          {l?.v}
                        </span>
                      </div>
                      </React.Fragment>
                    ))}
                  </div>
                  <div className="note">
                    {"Same shape as GOLDEN_DEMO_MANIFEST in backend/telemetry.py · positions are planned, not recorded"}
                  </div>
                  <div className="modal-foot">
                    <button className="btn btn-ghost" onClick={v.closeExport}>
                      {"Close"}
                    </button>
                    <button className="btn btn-primary" onClick={v.downloadManifest}>
                      {"Download JSON"}
                    </button>
                  </div>
                </section>
              </div>
              </>
            ) : null}
          </main>
        </div>
      </div>
    );
  }
}

export default View;
