'use client';
/* eslint-disable */
// Generated by scripts/convert-designs.mjs from design/landing-page/MissionsLog.template.html — edit the design or the patches, then re-run.
import React from 'react';
import Link from 'next/link';
import Base from './_base';
import { AppRail, TopBar } from '@/components/chrome';
import { getPillar, setPillar, readJSON, writeJSON, signIn, signOut, saveSession, downloadFile } from '@/lib/store';
import { API_URL, pingApi, inferFile, submitRequest } from '@/lib/api';
import { sessionData } from '@/lib/session';
import './css/MissionsLog.css';

class View extends Base {
  constructor(props) {
    super(props);
    this.state = { pillar: 'energy', pf: 'all', sf: 'all', tf: 'all', q: '', sel: 'AER-EN-0142', checked: [], page: 1 };
    this._selSite = 'rsp';
  }

  renderVals() {
    const D = this._data();
    const { pillar, pf, sf, tf, q, sel, checked } = this.state;
    const all = D.missionsAll;
    const ql = q.trim().toLowerCase();
    const rows = all.filter((m) => (pf === 'all' || m.pillar === pf)
      && (sf === 'all' || m.status.toLowerCase() === sf)
      && (tf === 'all' || m.tele.toLowerCase() === tf)
      && (!ql || m.id.toLowerCase().indexOf(ql) >= 0 || m.site.toLowerCase().indexOf(ql) >= 0));
    const decorate = (m) => Object.assign({}, m, {
      chip: D.P[m.pillar].chip, pillarName: D.P[m.pillar].name,
      covStr: m.coverage + '%', covCls: m.coverage < 80 ? 'warn' : '',
      statColor: m.status === 'Complete' ? '#7BE3A0' : m.status === 'Failed' ? '#FF6A3D' : '#5CE1FF',
      statLabel: m.status === 'Processing' ? 'Processing ' + m.pct + '%' : m.status,
    });
    const curM = decorate(all.find((m) => m.id === sel) || all[0]);
    this._selSite = curM.siteKey;
    const seg = (key, val, opts) => opts.map(([k, name]) => ({ name, cls: val === k ? 'on' : '', pick: () => this.setState({ [key]: k }) }));
    const pickPillar = (k) => this.setState({ pillar: k, pf: k });
    const allChecked = rows.length > 0 && rows.every((m) => checked.indexOf(m.id) >= 0);
    return {
      pillars: this._pillarTabs(pillar, pickPillar),
      total: all.length,
      shown: rows.length,
      onSearch: (e) => this.setState({ q: (e && e.target && e.target.value) || '' }),
      pillarF: seg('pf', pf, [['all', 'All'], ['energy', 'Energy'], ['agri', 'Agri'], ['rescue', 'Rescue']]),
      statusF: seg('sf', sf, [['all', 'All'], ['processing', 'Running'], ['complete', 'Done'], ['failed', 'Failed']]),
      teleF: seg('tf', tf, [['all', 'Any'], ['exif', 'EXIF'], ['manifest', 'Manifest'], ['simulated', 'Sim']]),
      rows: rows.map((m) => Object.assign(decorate(m), {
        selCls: m.id === sel ? 'sel' : '',
        ckCls: checked.indexOf(m.id) >= 0 ? 'on' : '',
        pick: () => this.setState({ sel: m.id }),
        check: (e) => {
          if (e && e.stopPropagation) e.stopPropagation();
          const c = this.state.checked;
          this.setState({ checked: c.indexOf(m.id) >= 0 ? c.filter((x) => x !== m.id) : c.concat(m.id) });
        },
      })),
      noRows: rows.length === 0,
      allCls: allChecked ? 'on' : '',
      toggleAll: () => this.setState({ checked: allChecked ? [] : rows.map((m) => m.id) }),
      hasChecked: checked.length > 0,
      noChecked: checked.length === 0,
      checkedCount: checked.length,
      clearChecked: () => this.setState({ checked: [] }),
      cur: curM,
    };
  }

  componentDidMount() {
    this._syncPillar();
    this._alive = true;
    this._startClock();
    this._boot(0);
  }

  componentWillUnmount() {
    this._alive = false;
    this._stopClock();
    if (this._raf) cancelAnimationFrame(this._raf);
    if (this._ao) this._ao.destroy();
  }

  _boot(tries) {
    if (!this._alive) return;
    const canvas = document.querySelector('[data-gl="ao"]');
    if (!canvas) { if (tries < 120) requestAnimationFrame(() => this._boot(tries + 1)); return; }
    this._ao = this._aoScene(this._engine(), canvas, document.querySelector('[data-gl-labels="ao"]'));
    this._loop([this._ao]);
  }



  render() {
    const v = this.renderVals();
    return (
      <div className="pg-missions-log ds">
        <div className="app">
          <AppRail active="missions" />
          <TopBar crumbs={["Command center","Missions"]} pillars={v.pillars} />
          <main className="main">
            <div className="ml">
              <div className="ml-head">
                <div>
                  <div className="kicker">
                    <i></i>
                    {"Missions · all pillars"}
                  </div>
                  <h1 className="h1" style={{ marginTop: "10px" }}>
                    {"Mission log"}
                  </h1>
                </div>
                <div className="meta" style={{ paddingBottom: "6px" }}>
                  {v.total}{" missions · 6 sites · sample data"}
                </div>
                <div className="acts">
                  <button className="btn btn-ghost" onClick={() => downloadFile('missions_log_export.csv', 'ID,Site,Pillar,Date,Duration,Telemetry\nSOLAR-PERIMETER-01,Solar Array Alpha,energy,14 Sep 2026,38m,RTK Fixed\nMINE-STOCKPILE-04,Quarry North,mining,12 Sep 2026,24m,RTK Float', 'text/csv')}>
                    {"Export CSV"}
                  </button>
                  <Link className="btn btn-primary" href={'/missions/new'}>
                    {"+ New inspection"}
                  </Link>
                </div>
              </div>
              <div className="filters">
                <label className="find">
                  <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62738F" strokeWidth="1.6">
                    <circle cx="11" cy="11" r="7"></circle>
                    <path d="M20 20l-4-4"></path>
                  </svg>
                  <input type="text" placeholder="Search mission ID or site" onInput={v.onSearch} />
                </label>
                <div className="fgroup">
                  <span className="lbl">
                    {"Pillar"}
                  </span>
                  <div className="segs">
                    {(v.pillarF || []).map((f, $index) => (
                      <React.Fragment key={$index}>
                      <button className={f?.cls} onClick={f?.pick}>
                        {f?.name}
                      </button>
                      </React.Fragment>
                    ))}
                  </div>
                </div>
                <div className="fgroup">
                  <span className="lbl">
                    {"Status"}
                  </span>
                  <div className="segs">
                    {(v.statusF || []).map((f, $index) => (
                      <React.Fragment key={$index}>
                      <button className={f?.cls} onClick={f?.pick}>
                        {f?.name}
                      </button>
                      </React.Fragment>
                    ))}
                  </div>
                </div>
                <div className="fgroup">
                  <span className="lbl">
                    {"Telemetry"}
                  </span>
                  <div className="segs">
                    {(v.teleF || []).map((f, $index) => (
                      <React.Fragment key={$index}>
                      <button className={f?.cls} onClick={f?.pick}>
                        {f?.name}
                      </button>
                      </React.Fragment>
                    ))}
                  </div>
                </div>
                <div className="range">
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
                    <rect x="3" y="5" width="18" height="16"></rect>
                    <path d="M3 10h18M8 3v4M16 3v4"></path>
                  </svg>
                  {"16 Aug – 14 Sep 2026"}
                </div>
              </div>
              <div className="cols">
                <section className="panel">
                  <div className="ph">
                    {v.noChecked ? (
                      <>
                      <span className="lbl strong">
                        {"Showing "}{v.shown}{" of "}{v.total}
                      </span>
                      </>
                    ) : null}
                    {v.hasChecked ? (
                      <>
                      <div className="bulk">
                        <b>
                          {v.checkedCount}{" selected"}
                        </b>
                        <button className="btn btn-ghost btn-sm" onClick={() => alert(`${v.checkedCount} missions selected for side-by-side comparative analytics.`)}>
                          {"Compare"}
                        </button>
                        <button className="btn btn-ghost btn-sm" onClick={() => downloadFile('selected_missions_export.csv', 'Selected Missions Export\n' + (v.checkedCount || 0) + ' items selected', 'text/csv')}>
                          {"Export"}
                        </button>
                        <button className="btn btn-danger btn-sm" onClick={() => alert(`${v.checkedCount} missions archived successfully.`)}>
                          {"Archive"}
                        </button>
                        <button className="btn btn-ghost btn-sm" onClick={v.clearChecked}>
                          {"Clear"}
                        </button>
                      </div>
                      </>
                    ) : null}
                    <span className="lbl">
                      {"Sorted by date · newest first"}
                    </span>
                  </div>
                  <div className="scroll tbl-wrap">
                    <table className="tbl">
                      <thead>
                        <tr>
                          <th style={{ width: "30px" }}>
                            <span className={`cbx ${v.allCls ?? ""}`} onClick={v.toggleAll}></span>
                          </th>
                          <th>
                            {"Mission ID"}
                          </th>
                          <th>
                            {"Site"}
                          </th>
                          <th>
                            {"Pillar"}
                          </th>
                          <th>
                            {"Date (UTC)"}
                          </th>
                          <th>
                            {"Duration"}
                          </th>
                          <th>
                            {"Frames"}
                          </th>
                          <th>
                            {"Crit / Total"}
                          </th>
                          <th>
                            {"Coverage"}
                          </th>
                          <th>
                            {"Telemetry"}
                          </th>
                          <th>
                            {"Status"}
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        {(v.rows || []).map((m, $index) => (
                          <React.Fragment key={$index}>
                          <tr className={m?.selCls} onClick={m?.pick}>
                            <td>
                              <span className={`cbx ${m?.ckCls ?? ""}`} onClick={m?.check}></span>
                            </td>
                            <td className="id">
                              {m?.id}
                            </td>
                            <td>
                              {m?.site}
                            </td>
                            <td>
                              <span className={`chip ${m?.chip ?? ""}`}>
                                {m?.pillarName}
                              </span>
                            </td>
                            <td>
                              {m?.date}
                            </td>
                            <td>
                              {m?.duration}
                            </td>
                            <td>
                              {m?.frames}
                            </td>
                            <td>
                              {m?.det}
                            </td>
                            <td>
                              <span className="cov">
                                <span className={`bar3 ${m?.covCls ?? ""}`}>
                                  <b style={{ width: `${m?.covStr ?? ""}` }}></b>
                                </span>
                                {m?.covStr}
                              </span>
                            </td>
                            <td>
                              <span className={`badge ${m?.tcls ?? ""}`}>
                                {m?.tele}
                              </span>
                            </td>
                            <td>
                              <span className="stat" style={{ color: `${m?.statColor ?? ""}` }}>
                                <i className="dia" style={{ background: `${m?.statColor ?? ""}` }}></i>
                                {m?.statLabel}
                              </span>
                            </td>
                          </tr>
                          </React.Fragment>
                        ))}
                      </tbody>
                    </table>
                    {v.noRows ? (
                      <>
                      <div className="empty">
                        {"No missions match these filters"}
                      </div>
                      </>
                    ) : null}
                  </div>
                  <div className="pager">
                    <span>
                      {"1–"}{v.shown}{" of "}{v.total}{" · sample set"}
                    </span>
                    <div className="pages">
                      <button onClick={() => this.setState({ page: Math.max(1, this.state.page - 1) })}>
                        {"‹"}
                      </button>
                      <button className={this.state.page === 1 ? "on" : ""} onClick={() => this.setState({ page: 1 })}>
                        {"1"}
                      </button>
                      <button className={this.state.page === 2 ? "on" : ""} onClick={() => this.setState({ page: 2 })}>
                        {"2"}
                      </button>
                      <button className={this.state.page === 3 ? "on" : ""} onClick={() => this.setState({ page: 3 })}>
                        {"3"}
                      </button>
                      <button onClick={() => this.setState({ page: Math.min(3, this.state.page + 1) })}>
                        {"›"}
                      </button>
                    </div>
                  </div>
                </section>
                <div className="side">
                  <section className="panel">
                    <div className="ph">
                      <span className="lbl strong">
                        {"Area of operations"}
                      </span>
                      <span className="badge b-sim">
                        {"Approx. site positions"}
                      </span>
                    </div>
                    <div className="ao">
                      <canvas className="gl" data-gl="ao"></canvas>
                      <div className="gl-labels" data-gl-labels="ao"></div>
                      <div className="ao-hint">
                        {"Click a pin"}
                      </div>
                      <div className="glass ao-legend">
                        <span>
                          <i className="dia" style={{ background: "#5CE1FF" }}></i>
                          {"Energy"}
                        </span>
                        <span>
                          <i className="dia" style={{ background: "#9BE15D" }}></i>
                          {"Agri"}
                        </span>
                        <span>
                          <i className="dia" style={{ background: "#FF7A4D" }}></i>
                          {"Rescue"}
                        </span>
                      </div>
                    </div>
                  </section>
                  <section className="panel sel">
                    <div className="sel-top">
                      <span className={`chip ${v.cur?.chip ?? ""}`}>
                        {v.cur?.pillarName}
                      </span>
                      <span className={`badge ${v.cur?.tcls ?? ""}`}>
                        {v.cur?.tele}
                      </span>
                    </div>
                    <h2 className="h2">
                      {v.cur?.id}
                    </h2>
                    <div className="sel-site">
                      {v.cur?.site}{" · "}{v.cur?.date}{" UTC"}
                    </div>
                    <div className="kvg">
                      <div>
                        <span className="lbl">
                          {"Duration"}
                        </span>
                        <b>
                          {v.cur?.duration}
                        </b>
                      </div>
                      <div>
                        <span className="lbl">
                          {"Frames"}
                        </span>
                        <b>
                          {v.cur?.frames}
                        </b>
                      </div>
                      <div>
                        <span className="lbl">
                          {"Crit / total"}
                        </span>
                        <b>
                          {v.cur?.det}
                        </b>
                      </div>
                      <div>
                        <span className="lbl">
                          {"Coverage"}
                        </span>
                        <b>
                          {v.cur?.covStr}
                        </b>
                      </div>
                      <div>
                        <span className="lbl">
                          {"Operator"}
                        </span>
                        <b>
                          {v.cur?.operator}
                        </b>
                      </div>
                      <div>
                        <span className="lbl">
                          {"Aircraft"}
                        </span>
                        <b>
                          {v.cur?.aircraft}
                        </b>
                      </div>
                    </div>
                    <div className="sel-acts">
                      <Link className="btn btn-primary btn-sm" href={'/missions/' + v.cur.id}>
                        {"Open twin"}
                      </Link>
                      <Link className="btn btn-ghost btn-sm" href={'/missions/' + v.cur.id + '/report'}>
                        {"Report"}
                      </Link>
                      <button className="btn btn-ghost btn-sm" onClick={() => alert(`Inspection re-run queued for ${v.cur?.id || 'mission'}. Telemetry gateway initialized.`)}>
                        {"Re-run"}
                      </button>
                    </div>
                  </section>
                </div>
              </div>
            </div>
          </main>
        </div>
      </div>
    );
  }
}

export default View;
