'use client';
/* eslint-disable */
// Generated by scripts/convert-designs.mjs from design/landing-page/MissionReport.template.html — edit the design or the patches, then re-run.
import React from 'react';
import Link from 'next/link';
import Base from './_base';
import { AppRail, TopBar } from '@/components/chrome';
import { getPillar, setPillar, readJSON, writeJSON, signIn, signOut, saveSession, downloadFile } from '@/lib/store';
import { API_URL, pingApi, inferFile, submitRequest } from '@/lib/api';
import { sessionData } from '@/lib/session';
import './css/MissionReport.css';

class View extends Base {
  constructor(props) {
    super(props);
    this._dataOverride = sessionData(props.id, this.__data());
    this.state = { pillar: props.pillar || 'energy', fmt: 'pdf', exp: 'idle', inc: { prov: true, summary: true, map: true, table: true, method: true, dossiers: true } };
  }

  renderVals() {
    const D = this._data();
    const { pillar, fmt, exp, inc } = this.state;
    const pc = D.P[pillar];
    const dets = pc.dets;
    const X = (x) => (x + 64) * 5, Y = (z) => (z + 44) * 5;
    let cells = [];
    if (pillar === 'energy') {
      for (let r = 0; r < 14; r++) for (let c = 0; c < 23; c++) {
        const x = -57.5 + c * 5.2, z = -38.5 + r * 5.5, hot = dets.some((q) => Math.abs(q.x - x) < 0.1 && Math.abs(q.z - z) < 0.1);
        cells.push({ x: (X(x) - 11.5).toFixed(1), y: (Y(z) - 6).toFixed(1), w: 23, h: 12, fill: hot ? '#FFB199' : '#B9C7E3', stroke: hot ? '#E0522B' : '#8FA3CC' });
      }
    } else if (pillar === 'agri') {
      for (let r = 0; r < 14; r++) for (let c = 0; c < 20; c++) {
        const x = -57 + c * 6, z = -39 + r * 6;
        let n = 0.6 + 0.3 * Math.sin(x * 0.06 + 1) * Math.cos(z * 0.08);
        dets.forEach((q) => { n -= 0.75 * Math.exp(-((x - q.x) ** 2 + (z - q.z) ** 2) / 120); });
        n = Math.max(0, Math.min(1, n));
        const fill = n < 0.35 ? '#F0A58F' : n < 0.55 ? '#F2D58A' : '#A9D8A0';
        cells.push({ x: (X(x) - 14).toFixed(1), y: (Y(z) - 14).toFixed(1), w: 28, h: 28, fill, stroke: '#E9EDF4' });
      }
    } else {
      let seed = 11;
      const rnd = () => (seed = (seed * 16807) % 2147483647) / 2147483647;
      for (let i = 0; i < 30; i++) {
        const x = -60 + rnd() * 120, z = -40 + rnd() * 80, w = 3 + rnd() * 6, dd = 3 + rnd() * 5;
        rnd(); rnd();
        cells.push({ x: (X(x) - w * 2.5).toFixed(1), y: (Y(z) - dd * 2.5).toFixed(1), w: (w * 5).toFixed(1), h: (dd * 5).toFixed(1), fill: '#CBC6D8', stroke: '#9C95B3' });
      }
    }
    const pts = [];
    for (let i = 0; i < 7; i++) { const z = -36 + i * 12; if (i % 2) pts.push([56, z], [-56, z]); else pts.push([-56, z], [56, z]); }
    const pathPts = pts.map(([x, z]) => X(x).toFixed(0) + ',' + Y(z).toFixed(0)).join(' ');
    const color = (q) => (q.sev === 'crit' ? '#E0522B' : '#D98E12');
    const rows = dets.map((q, i) => Object.assign({}, q, { n: i + 1, confStr: q.conf.toFixed(2), color: color(q) }));

    const payload = D.session ? { session: D.session.session, pillar: D.session.pillar, model: D.session.model, telemetry: D.session.telemetry, detections: D.session.detections, results: D.session.results, metrics: Object.assign({}, D.session.metrics, { sample_data: false }) } : {
      session: { id: pc.mission, created_utc: '2026-09-14T14:05:00Z', site: pc.site, mode: 'golden_demo' },
      pillar: pc.key,
      model: { weights: pc.model, conf_threshold: 0.5, source: 'demo' },
      telemetry: { source: 'simulated', provenance: 'manifest_fallback', origin: { lat: 22.3, lng: 70.8 }, frames: pc.frames },
      detections: dets.map((q) => ({
        id: q.id, class: q.cls.toLowerCase(), confidence: q.conf, severity: q.sev === 'crit' ? 'critical' : 'warning',
        bbox_xyxy: q.bbox, position: { lat: +q.lat.slice(0, 8), lng: +q.lon.slice(0, 8), accuracy: 'approximate', source: 'manifest' },
        world_offset_m: { east: +q.offX, north: +q.offZ },
      })),
      metrics: { inference_time_ms: 38.4, detections_total: dets.length, critical: dets.filter((q) => q.sev === 'crit').length, sample_data: true },
    };
    const jsonLines = this._jsonLines(payload);
    this._payload = payload;

    const setInc = (k) => { if (k === 'prov') return; this.setState({ inc: Object.assign({}, this.state.inc, { [k]: !this.state.inc[k] }) }); };
    const pickPillar = (k) => { this.setState({ pillar: k, exp: 'idle' }); window.history.replaceState(null, '', '/missions/' + D.P[k].mission + '/report'); };
    const ext = fmt === 'pdf' ? '.pdf' : '.json';
    return {
      pillars: this._pillarTabs(pillar, pickPillar),
      pc,
      provTele: D.session ? ((D.session.detections || []).some((d) => d.telemetry && d.telemetry.source === 'simulated') ? 'reported by the backend; some frames had no manifest entry, so their positions are simulated' : 'reported by the backend from the golden-demo flight manifest') : 'simulated from the golden-demo flight manifest',
      provDet: D.session ? 'the fine-tuned model ' + pc.model + ' via the inference API' : 'demo weights (' + pc.model + ')',
      provTeleShort: D.session ? ((D.session.detections || []).some((d) => d.telemetry && d.telemetry.source === 'simulated') ? 'Backend · partly simulated' : 'Backend · manifest') : 'Simulated (manifest)',
      infTime: D.session && D.session.metrics && D.session.metrics.inference_time_ms ? D.session.metrics.inference_time_ms + ' ms / frame' : '38.4 ms / frame · sample',
      isPdf: fmt === 'pdf', isJson: fmt === 'json',
      showPdf: () => this._export('pdf'),
      showJson: () => this._export('json'),
      tabs: [['pdf', 'PDF preview', '2 pages'], ['json', 'JSON payload', jsonLines.length + ' lines']].map(([k, name, n]) => ({ name, n, cls: fmt === k ? 'on' : '', pick: () => this.setState({ fmt: k, exp: 'idle' }) })),
      formats: [['pdf', 'PDF'], ['json', 'JSON']].map(([k, name]) => ({ name, cls: fmt === k ? 'on' : '', pick: () => this.setState({ fmt: k, exp: 'idle' }) })),
      inc,
      incList: [['prov', 'Provenance statement', 'Required'], ['summary', 'Summary metrics', ''], ['map', 'Site map', ''], ['table', 'Detections table', ''], ['method', 'Method', ''], ['dossiers', 'Detection dossiers', '']]
        .map(([k, name, note]) => ({ name, note, cls: inc[k] ? 'on' : '', toggle: () => setInc(k) })),
      kpis: pc.kpis,
      cells, pathPts,
      marks: dets.map((q, i) => ({ tr: 'translate(' + X(q.x).toFixed(1) + ' ' + Y(q.z).toFixed(1) + ')', color: color(q), n: String(i + 1) })),
      rows,
      dossiers: rows.filter((q) => q.sev === 'crit').slice(0, 3).map((q) => Object.assign({}, q, { thumb: pc.thumb, bboxStr: q.bbox.join(', ') })),
      jsonLines,
      fileName: pc.mission + '_report' + ext,
      fileSize: fmt === 'pdf' ? '~1.1 MB · 2 pages' : '~' + Math.max(2, Math.round(JSON.stringify(payload).length / 1024)) + ' KB',
      checks: ['Telemetry source labelled simulated', 'Coordinates marked approximate', 'Model and weights stated', 'Values taken from session payload'],
      goCls: exp === 'busy' ? 'btn btn-primary is-busy' : exp === 'done' ? 'btn btn-go' : 'btn btn-primary',
      goLabel: exp === 'busy' ? 'Preparing ' + ext.slice(1).toUpperCase() + '…' : exp === 'done' ? 'Ready · ' + pc.mission + ext : 'Export ' + ext.slice(1).toUpperCase(),
      goNote: exp === 'done' ? (fmt === 'pdf' ? 'Choose “Save as PDF” in the print dialog' : 'JSON saved to your downloads') : 'Generated from the session payload, not re-computed',
      doExport: () => this._export(fmt),
    };
  }

  _export(fmt) {
    if (this.state.exp === 'busy') return;
    this.setState({ fmt, exp: 'busy' });
    clearTimeout(this._expT);
    this._expT = setTimeout(() => {
      if (!this._alive) return;
      this.setState({ exp: 'done' });
      if (fmt === 'json') downloadFile(this.renderVals().fileName, JSON.stringify(this._payload, null, 2));
      else window.print();
    }, 700);
  }

  _jsonLines(obj) {
    const out = [];
    const lit = (v) => typeof v === 'string' ? ['"' + v + '"', 'j-str'] : typeof v === 'number' ? [String(v), 'j-num'] : [String(v), 'j-lit'];
    const walk = (v, depth, key, last) => {
      const pad = '  '.repeat(depth), k = key == null ? '' : '"' + key + '": ', tail = last ? '' : ',';
      const flatArr = Array.isArray(v) && v.every((x) => typeof x !== 'object');
      if (v && typeof v === 'object' && !flatArr) {
        const arr = Array.isArray(v), entries = arr ? v.map((x, i) => [null, x]) : Object.entries(v);
        const inline = !arr && entries.every(([, x]) => typeof x !== 'object') && entries.length <= 2;
        if (inline) {
          out.push({ pad, k, v: '{ ' + entries.map(([ek, ex]) => '"' + ek + '": ' + lit(ex)[0]).join(', ') + ' }', cls: 'j-num', tail });
          return;
        }
        out.push({ pad, k, v: arr ? '[' : '{', cls: 'j-pun', tail: '' });
        entries.forEach(([ek, ex], i) => walk(ex, depth + 1, ek, i === entries.length - 1));
        out.push({ pad, k: '', v: arr ? ']' : '}', cls: 'j-pun', tail });
      } else if (flatArr) {
        out.push({ pad, k, v: '[' + v.map((x) => lit(x)[0]).join(', ') + ']', cls: 'j-num', tail });
      } else {
        const [txt, cls] = lit(v);
        out.push({ pad, k, v: txt, cls, tail });
      }
    };
    walk(obj, 0, null, true);
    return out.map((l, i) => Object.assign(l, { ln: String(i + 1) }));
  }

  componentDidMount() {
    this._syncPillar();
    this._alive = true;
    this._startClock();
  }

  componentWillUnmount() {
    this._alive = false;
    this._stopClock();
    clearTimeout(this._expT);
  }



  render() {
    const v = this.renderVals();
    return (
      <div className="pg-mission-report ds">
        <div className="app">
          <AppRail active="reports" />
          <TopBar crumbs={["Missions","Mission report"]} pillars={v.pillars} />
          <main className="main">
            <div className="rp">
              <div className="rp-head">
                <div>
                  <div className="kicker" style={{ color: `${v.pc?.color ?? ""}` }}>
                    <i></i>
                    {"Mission report · "}{v.pc?.name}
                  </div>
                  <h1 className="h1" style={{ marginTop: "10px" }}>
                    {v.pc?.mission}{" report"}
                  </h1>
                </div>
                <div className="meta" style={{ paddingBottom: "6px" }}>
                  {"Built from session payload · "}{v.pc?.date}{" UTC"}
                </div>
                <div className="acts">
                  <Link className="btn btn-ghost" href={'/missions/' + v.pc.mission}>
                    {"← Back to twin"}
                  </Link>
                  <button className="btn btn-ghost" onClick={v.showJson}>
                    {"Export JSON"}
                  </button>
                  <button className="btn btn-primary" onClick={v.showPdf}>
                    {"Export PDF"}
                  </button>
                </div>
              </div>
              <div className="cols">
                <section className="panel">
                  <div className="tabs">
                    {(v.tabs || []).map((t, $index) => (
                      <React.Fragment key={$index}>
                      <button className={`tab ${t?.cls ?? ""}`} onClick={t?.pick}>
                        {t?.name}
                        <em>
                          {t?.n}
                        </em>
                      </button>
                      </React.Fragment>
                    ))}
                  </div>
                  {v.isPdf ? (
                    <>
                    <div className="scroll docwrap">
                      <div className="docs">
                        <article className="paper">
                          <div className="pp-head">
                            <img src="/brand/logo-mark.png" alt="" />
                            <span className="pp-brand">
                              {"Aerolytics"}
                            </span>
                            <span className="pp-kind">
                              {"Inspection report · "}{v.pc?.name}{" · page 1 / 2"}
                            </span>
                          </div>
                          <h2 className="pp-title">
                            {v.pc?.site}{": "}{v.pc?.long}
                          </h2>
                          <div className="pp-sub">
                            {v.pc?.mission}{" · "}{v.pc?.date}{" UTC · Rajkot AO 22.3000° N 70.8000° E"}
                          </div>
                          {v.inc?.prov ? (
                            <>
                            <div className="pp-prov">
                              <i className="dia"></i>
                              <div>
                                <b>
                                  {"Data provenance."}
                                </b>
                                {" Telemetry for this mission is "}
                                <b>
                                  {v.provTele}
                                </b>
                                {". Coordinates are approximate and not survey-grade. Detections come from "}{v.provDet}{" and are not validated field measurements."}
                              </div>
                            </div>
                            </>
                          ) : null}
                          {v.inc?.summary ? (
                            <>
                            <div>
                              <div className="pp-h">
                                {"1 · Summary"}
                              </div>
                              <div className="pp-kpis">
                                {(v.kpis || []).map((k, $index) => (
                                  <React.Fragment key={$index}>
                                  <div className="pp-kpi">
                                    <span>
                                      {k?.k}
                                    </span>
                                    <b>
                                      {k?.v}{" "}
                                      <small style={{ fontSize: "12px", fontWeight: "400" }}>
                                        {k?.of}
                                      </small>
                                    </b>
                                    <em>
                                      {k?.badge}
                                    </em>
                                  </div>
                                  </React.Fragment>
                                ))}
                              </div>
                            </div>
                            </>
                          ) : null}
                          {v.inc?.map ? (
                            <>
                            <div>
                              <div className="pp-h">
                                {"2 · Site map"}
                              </div>
                              <div className="pp-map">
                                <svg viewBox="0 0 640 440">
                                  {(v.cells || []).map((c, $index) => (
                                    <React.Fragment key={$index}>
                                    <rect x={c?.x} y={c?.y} width={c?.w} height={c?.h} fill={c?.fill} stroke={c?.stroke} strokeWidth="0.6"></rect>
                                    </React.Fragment>
                                  ))}
                                  <polyline points={v.pathPts} fill="none" stroke="#D98E12" strokeWidth="1.6" strokeDasharray="6 4"></polyline>
                                  {(v.marks || []).map((m, $index) => (
                                    <React.Fragment key={$index}>
                                    <g transform={m?.tr}>
                                      <circle r="14" fill="none" stroke={m?.color} strokeWidth="1.2" opacity="0.5"></circle>
                                      <rect x="-6" y="-6" width="12" height="12" fill={m?.color} transform="rotate(45)"></rect>
                                      <text x="12" y="-10" fontFamily="IBM Plex Mono, monospace" fontSize="11" fontWeight="500" fill="#0B1530">
                                        {m?.n}
                                      </text>
                                    </g>
                                    </React.Fragment>
                                  ))}
                                  <g transform="translate(596 40)">
                                    <path d="M0 -18 L7 6 L0 1 L-7 6 Z" fill="#0B1530"></path>
                                    <text x="-4" y="22" fontFamily="IBM Plex Mono, monospace" fontSize="10" fill="#0B1530">
                                      {"N"}
                                    </text>
                                  </g>
                                  <g transform="translate(24 414)">
                                    <rect width="75" height="4" fill="#0B1530"></rect>
                                    <text y="-6" fontFamily="IBM Plex Mono, monospace" fontSize="9.5" fill="#0B1530">
                                      {"~22 m"}
                                    </text>
                                  </g>
                                </svg>
                              </div>
                              <div className="pp-cap">
                                <span>
                                  {"Dashed amber: simulated flight path (7 lanes)"}
                                </span>
                                <span>
                                  {"Markers numbered as in table · positions approximate"}
                                </span>
                              </div>
                            </div>
                            </>
                          ) : null}
                          {v.inc?.table ? (
                            <>
                            <div>
                              <div className="pp-h">
                                {"3 · Detections"}
                              </div>
                              <table className="pp-tbl">
                                <thead>
                                  <tr>
                                    <th>
                                      {"#"}
                                    </th>
                                    <th>
                                      {"ID"}
                                    </th>
                                    <th>
                                      {"Class"}
                                    </th>
                                    <th>
                                      {"Conf."}
                                    </th>
                                    <th>
                                      {"Severity"}
                                    </th>
                                    <th>
                                      {v.pc?.unit}{" / location"}
                                    </th>
                                    <th>
                                      {"Lat"}
                                    </th>
                                    <th>
                                      {"Lon"}
                                    </th>
                                    <th>
                                      {"Status"}
                                    </th>
                                  </tr>
                                </thead>
                                <tbody>
                                  {(v.rows || []).map((r, $index) => (
                                    <React.Fragment key={$index}>
                                    <tr>
                                      <td>
                                        {r?.n}
                                      </td>
                                      <td>
                                        {r?.id}
                                      </td>
                                      <td style={{ fontWeight: "500" }}>
                                        {r?.cls}
                                      </td>
                                      <td>
                                        {r?.confStr}
                                      </td>
                                      <td>
                                        <i className="sevp" style={{ background: `${r?.color ?? ""}` }}></i>
                                        {r?.sevLabel}
                                      </td>
                                      <td>
                                        {r?.loc}
                                      </td>
                                      <td>
                                        {r?.lat}
                                      </td>
                                      <td>
                                        {r?.lon}
                                      </td>
                                      <td>
                                        {r?.status}
                                      </td>
                                    </tr>
                                    </React.Fragment>
                                  ))}
                                </tbody>
                              </table>
                            </div>
                            </>
                          ) : null}
                          {v.inc?.method ? (
                            <>
                            <div>
                              <div className="pp-h">
                                {"4 · Method"}
                              </div>
                              <div className="pp-method">
                                <div>
                                  <span>
                                    {"Model"}
                                  </span>
                                  <b>
                                    {v.pc?.model}{" · YOLO"}
                                  </b>
                                </div>
                                <div>
                                  <span>
                                    {"Confidence threshold"}
                                  </span>
                                  <b>
                                    {"0.50"}
                                  </b>
                                </div>
                                <div>
                                  <span>
                                    {"Frames processed"}
                                  </span>
                                  <b>
                                    {v.pc?.frames}
                                  </b>
                                </div>
                                <div>
                                  <span>
                                    {"Telemetry source"}
                                  </span>
                                  <b>
                                    {v.provTeleShort}
                                  </b>
                                </div>
                                <div>
                                  <span>
                                    {"Inference time"}
                                  </span>
                                  <b>
                                    {v.infTime}
                                  </b>
                                </div>
                                <div>
                                  <span>
                                    {"Coordinate accuracy"}
                                  </span>
                                  <b>
                                    {"Approximate"}
                                  </b>
                                </div>
                              </div>
                            </div>
                            </>
                          ) : null}
                          <div className="pp-foot">
                            <span>
                              {"Generated by Aerolytics · "}{v.pc?.mission}
                            </span>
                            <span>
                              {"Golden demo · not for operational use"}
                            </span>
                          </div>
                        </article>
                        {v.inc?.dossiers ? (
                          <>
                          <article className="paper">
                            <div className="pp-head">
                              <img src="/brand/logo-mark.png" alt="" />
                              <span className="pp-brand">
                                {"Aerolytics"}
                              </span>
                              <span className="pp-kind">
                                {"Detection dossiers · page 2 / 2"}
                              </span>
                            </div>
                            <div className="pp-h">
                              {"5 · Critical detections"}
                            </div>
                            <div className="dcards">
                              {(v.dossiers || []).map((d, $index) => (
                                <React.Fragment key={$index}>
                                <div className="dcard">
                                  <div className={`thumb ${d?.thumb ?? ""}`}>
                                    <span className="bbox"></span>
                                  </div>
                                  <div className="dcard-b">
                                    <b>
                                      {d?.n}{" · "}{d?.cls}{" "}{d?.confStr}
                                    </b>
                                    {d?.id}{" · "}{d?.frame}
                                    <br />
                                    {d?.loc}
                                    <br />
                                    {d?.lat}{", "}{d?.lon}
                                    <br />
                                    {"BBox "}{d?.bboxStr}
                                  </div>
                                </div>
                                </React.Fragment>
                              ))}
                            </div>
                            <div className="pp-foot">
                              <span>
                                {"Frame crops shown are sample imagery"}
                              </span>
                              <span>
                                {v.pc?.mission}{" · page 2 / 2"}
                              </span>
                            </div>
                          </article>
                          </>
                        ) : null}
                      </div>
                    </div>
                    </>
                  ) : null}
                  {v.isJson ? (
                    <>
                    <div className="scroll docwrap json">
                      {(v.jsonLines || []).map((l, $index) => (
                        <React.Fragment key={$index}>
                        <div className="jl">
                          <span className="j-ln">
                            {l?.ln}
                          </span>
                          <span>
                            {l?.pad}
                          </span>
                          <span className="j-key">
                            {l?.k}
                          </span>
                          <span className={l?.cls}>
                            {l?.v}
                          </span>
                          <span className="j-pun">
                            {l?.tail}
                          </span>
                        </div>
                        </React.Fragment>
                      ))}
                    </div>
                    </>
                  ) : null}
                </section>
                <aside className="panel exp">
                  <div className="ph">
                    <span className="lbl strong">
                      {"Export"}
                    </span>
                    <div className="segs">
                      {(v.formats || []).map((f, $index) => (
                        <React.Fragment key={$index}>
                        <button className={f?.cls} onClick={f?.pick}>
                          {f?.name}
                        </button>
                        </React.Fragment>
                      ))}
                    </div>
                  </div>
                  <div className="exp-sec">
                    <span className="lbl">
                      {"Include"}
                    </span>
                    <div className="inc">
                      {(v.incList || []).map((i, $index) => (
                        <React.Fragment key={$index}>
                        <button className={`ck ${i?.cls ?? ""}`} onClick={i?.toggle}>
                          <i></i>
                          {i?.name}
                          <em>
                            {i?.note}
                          </em>
                        </button>
                        </React.Fragment>
                      ))}
                    </div>
                  </div>
                  <div className="exp-sec">
                    <span className="lbl">
                      {"File"}
                    </span>
                    <div className="fname">
                      {v.fileName}
                      <span>
                        {v.fileSize}
                      </span>
                    </div>
                  </div>
                  <div className="exp-sec">
                    <span className="lbl">
                      {"Integrity checks"}
                    </span>
                    <div className="checks">
                      {(v.checks || []).map((c, $index) => (
                        <React.Fragment key={$index}>
                        <div>
                          <i className="dia sev-ok"></i>
                          {c}
                        </div>
                        </React.Fragment>
                      ))}
                    </div>
                  </div>
                  <div className="exp-go">
                    <button className={v.goCls} onClick={v.doExport}>
                      {v.goLabel}
                    </button>
                    <div className="exp-note">
                      {v.goNote}
                    </div>
                  </div>
                </aside>
              </div>
            </div>
          </main>
        </div>
      </div>
    );
  }
}

export default View;
