'use client';
/* eslint-disable */
// Generated by scripts/convert-designs.mjs from design/landing-page/NewInspection.template.html — edit the design or the patches, then re-run.
import React from 'react';
import Link from 'next/link';
import Base from './_base';
import { AppRail, TopBar } from '@/components/chrome';
import { getPillar, setPillar, readJSON, writeJSON, signIn, signOut, saveSession, downloadFile } from '@/lib/store';
import { API_URL, pingApi, inferFile, submitRequest } from '@/lib/api';
import { sessionData } from '@/lib/session';
import './css/NewInspection.css';

class View extends Base {
  constructor(props) {
    super(props);
    this.state = { pillar: 'energy', tele: 'manifest', thr: 0.5, save: true, phase: 'ready', prog: 0, removed: [] };
    this._runFrac = 0;
    this._tele = 'manifest';
    this._pillar = 'energy';
  }

  _files(pillar) {
    if (this.state && this.state.uploads && this.state.uploads.length) return this.state.uploads;
    const F = {
      energy: [
        ['solar_01.jpg', 'RGB', '4.8 MB', '4000×3000', 'manifest'], ['solar_02.jpg', 'RGB', '4.7 MB', '4000×3000', 'manifest'],
        ['solar_03.jpg', 'RGB', '4.9 MB', '4000×3000', 'manifest'], ['solar_04.jpg', 'RGB', '4.6 MB', '4000×3000', 'manifest'],
        ['solar_05.jpg', 'RGB', '4.8 MB', '4000×3000', 'manifest'], ['DJI_0231.JPG', 'RGB', '5.1 MB', '4000×3000', 'exif'],
        ['DJI_0232_T.JPG', 'Thermal', '0.9 MB', '640×512', 'none'],
      ],
      agri: [
        ['agri_01.jpg', 'RGB', '5.2 MB', '5472×3648', 'manifest'], ['agri_02.jpg', 'RGB', '5.3 MB', '5472×3648', 'manifest'],
        ['MS_0114.TIF', 'Multispectral', '12.4 MB', '1280×960', 'exif'], ['MS_0115.TIF', 'Multispectral', '12.1 MB', '1280×960', 'exif'],
        ['field_pass.mp4', 'Video · 120 f', '186 MB', '3840×2160', 'none'],
      ],
      rescue: [
        ['thermal_01.jpg', 'Thermal', '0.8 MB', '640×512', 'manifest'], ['thermal_02.jpg', 'Thermal', '0.8 MB', '640×512', 'manifest'],
        ['LWIR_0007.JPG', 'Thermal', '0.7 MB', '640×512', 'none'], ['LWIR_0008.JPG', 'Thermal', '0.7 MB', '640×512', 'none'],
        ['sweep_night.mp4', 'Video · 120 f', '94 MB', '640×512', 'none'],
      ],
    };
    return F[pillar].map(([name, type, size, res, gps]) => ({ name, type, size, res, gps, frames: type.indexOf('Video') === 0 ? 120 : 1 }));
  }

  renderVals() {
    const D = this._data();
    const { pillar, tele, thr, save, phase, prog, removed } = this.state;
    const pc = D.P[pillar];
    const files = this._files(pillar).filter((f) => removed.indexOf(f.name) < 0);
    const cnt = (g) => files.filter((f) => f.gps === g).length;
    const frames = files.reduce((s, f) => s + f.frames, 0);
    const TELE = {
      exif: { name: 'EXIF GPS only', badge: 'EXIF', bcls: 'b-exif' },
      manifest: { name: 'Flight manifest', badge: 'Manifest', bcls: 'b-man' },
      sim: { name: 'Simulated path', badge: 'Simulated', bcls: 'b-sim' },
    };
    const warn = tele === 'exif'
      ? (cnt('manifest') + cnt('none')) + ' of ' + files.length + ' files have no EXIF GPS and will not be placed on the map. Detections from them stay in the report without coordinates.'
      : tele === 'manifest'
        ? cnt('none') + ' file(s) have neither EXIF GPS nor a manifest entry. They will be interpolated along the planned path and labelled SIMULATED.'
        : 'Every position will be generated along a 7-lane lawnmower path over the Rajkot AO and labelled SIMULATED in the twin and the report.';
    const pickPillar = (k) => { this._pillar = k; this.setState({ pillar: k, removed: [], phase: 'ready', prog: 0 }); this._runFrac = 0; };
    const STG = [['Upload', 0.18], ['Telemetry', 0.12], ['Inference', 0.45], ['Normalize', 0.1], ['Geo-map', 0.15]];
    let acc = 0;
    const stages = STG.map(([name, share]) => {
      const local = Math.max(0, Math.min(1, (prog - acc) / share));
      acc += share;
      return { name, w: (local * 100).toFixed(0) + '%', pct: (local * 100).toFixed(0) + '%', cls: local <= 0 ? 'wait' : '', dia: local >= 1 ? 'sev-ok' : local > 0 ? 'dia-live' : 'dia-off' };
    });
    const dets = pc.dets.length;
    return {
      pillars: this._pillarTabs(pillar, pickPillar),
      pc,
      reservedId: pc.mission.replace(/\d+$/, (n) => String(+n + 2).padStart(4, '0')),
      steps: [['01', 'Pillar', 'done'], ['02', 'Media', files.length ? 'done' : 'active'], ['03', 'Telemetry', 'done'], ['04', 'Run', phase === 'done' ? 'done' : 'active']]
        .map(([idx, name, cls]) => ({ idx, name, cls })),
      pcards: ['energy', 'agri', 'rescue'].map((k) => ({
        name: D.P[k].name, model: D.P[k].model, color: D.P[k].color, cls: k === pillar ? 'on' : '',
        classes: D.P[k].classes.map((c) => c[0]).join(' · '),
        isEnergy: k === 'energy', isAgri: k === 'agri', isRescue: k === 'rescue', pick: () => pickPillar(k),
      })),
      files: files.map((f) => Object.assign({}, f, {
        bcls: f.gps === 'exif' ? 'b-exif' : f.gps === 'manifest' ? 'b-man' : 'b-sim',
        gps: f.gps === 'exif' ? 'EXIF GPS' : f.gps === 'manifest' ? 'Manifest match' : 'No GPS',
        remove: () => this.setState({ removed: this.state.removed.concat(f.name) }),
      })),
      fileCount: files.length, frameCount: frames, exifCount: cnt('exif'), manCount: cnt('manifest'), noneCount: cnt('none'),
      tcards: [
        ['exif', 'Use EXIF GPS', 'Place only frames whose image metadata carries GPS.', cnt('exif') + ' of ' + files.length + ' files usable'],
        ['manifest', 'Match flight manifest', 'Match filenames to planned waypoints, EXIF where present.', 'rajkot_golden_demo.json · 7 lanes'],
        ['sim', 'Simulate lawnmower path', 'Generate a path for a demo when no telemetry exists.', '7 lanes · 42 m AGL · 70% overlap'],
      ].map(([k, name, desc, field]) => ({ name, desc, field, badge: TELE[k].badge, bcls: TELE[k].bcls, cls: tele === k ? 'on' : '', pick: () => { this._tele = k; this.setState({ tele: k }); } })),
      tele: TELE[tele],
      teleWarn: warn,
      thresholds: [0.25, 0.5, 0.75].map((v) => ({ name: v.toFixed(2), cls: thr === v ? 'on' : '', pick: () => this.setState({ thr: v }) })),
      thrStr: thr.toFixed(2),
      saveCls: save ? 'on' : '',
      toggleSave: () => this.setState({ save: !this.state.save }),
      isReady: phase === 'ready', isRunning: phase === 'running', isDone: phase === 'done',
      runNoteLive: this.state.runNote,
      runChip: phase === 'ready' ? (this.state.uploads && this.state.uploads.length ? 'Ready · real files' : 'Ready · sample') : phase === 'running' ? 'Running · ' + Math.round(prog * 100) + '%' : 'Complete',
      runChipCls: phase === 'done' ? 'st-resolved' : 'st-new',
      stages,
      run: () => this._run(),
      reset: () => { this._runFrac = 0; this.setState({ phase: 'ready', prog: 0, sessionId: null, runNote: '', uploads: [] }); },
      sessionId: this.state.sessionId,
      dropTitle: this.state.uploads && this.state.uploads.length ? this.state.uploads.length + ' file(s) ready · drop more to add' : 'Drop drone imagery or video',
      browse: () => { const el = document.querySelector('[data-file="upload"]'); if (el) el.click(); },
      onFiles: (e) => { this._addFiles(e.target.files); e.target.value = ''; },
      dragOver: (e) => e.preventDefault(),
      onDrop: (e) => { e.preventDefault(); this._addFiles(e.dataTransfer.files); },
      doneNote: this.state.runNote || (dets + ' detections · ' + frames + ' frames · sample result, not a field measurement'),
    };
  }

  // Real run: POST each uploaded image to the FastAPI backend; fall back to a labelled simulation.
  async _run() {
    if (this.state.phase === 'running') return;
    const pillar = this.state.pillar;
    const files = this._files(pillar).filter((f) => f.file && this.state.removed.indexOf(f.name) < 0 && !/^video\//.test(f.file.type || ''));
    if (!files.length) return this._simulate('Sample files · simulated run, no backend call');
    this.setState({ phase: 'running', prog: 0.05, runNote: '' });
    const online = await pingApi();
    if (!online) return this._simulate('Backend not reachable at ' + API_URL + ' · simulated run');
    const results = [];
    for (let i = 0; i < files.length; i++) {
      try { results.push(await inferFile(pillar, files[i].file)); }
      catch (e) { results.push({ filename: files[i].name, error: String((e && e.message) || e), detections: [] }); }
      this._runFrac = (i + 1) / files.length;
      if (this._alive) this.setState({ prog: Math.min(0.95, 0.3 + 0.65 * ((i + 1) / files.length)) });
    }
    const ok = results.filter((r) => !r.error);
    const dets = [];
    ok.forEach((r) => (r.detections || []).forEach((d) => dets.push(Object.assign({}, d, { filename: r.filename, telemetry: r.telemetry, image: r.image }))));
    const code = { energy: 'EN', agri: 'AG', rescue: 'RS' }[pillar];
    const id = 'AER-' + code + '-U' + Date.now().toString(36).slice(-5).toUpperCase();
    const times = ok.map((r) => r.inference_time_ms || 0);
    saveSession({
      session: { id, created_utc: new Date().toISOString(), site: 'Uploaded mission', mode: 'live_upload', api: API_URL },
      pillar,
      model: { weights: this._data().P[pillar].model, conf_threshold: 0.5, source: 'backend' },
      telemetry: { source: 'backend telemetry.py (manifest or procedural fallback)', frames: ok.length },
      detections: dets,
      results,
      metrics: { inference_time_ms: times.length ? +(times.reduce((s, t) => s + t, 0) / times.length).toFixed(1) : null, detections_total: dets.length, failed_frames: results.length - ok.length },
    });
    if (this._alive) this.setState({ phase: 'done', prog: 1, sessionId: id, runNote: dets.length + ' detections · ' + ok.length + ' of ' + results.length + ' frames processed by the backend' + (results.length - ok.length ? ' · ' + (results.length - ok.length) + ' failed' : '') });
  }

  _addFiles(list) {
    const MAN = /^(solar|agri|thermal)_\d+\.jpe?g$/i;
    const add = Array.from(list || []).map((f) => ({
      name: f.name, type: (f.type || '').startsWith('video') ? 'Video · not sent' : 'Image',
      size: (f.size / 1048576).toFixed(1) + ' MB', res: '—', gps: MAN.test(f.name) ? 'manifest' : 'none', frames: 1, file: f,
    }));
    if (add.length) this.setState({ uploads: (this.state.uploads || []).concat(add), removed: [], phase: 'ready', prog: 0, sessionId: null, runNote: '' });
  }

  _simulate(note) {
    this.setState({ phase: 'running', prog: 0, runNote: note });
    const t0 = performance.now(), DUR = 7000;
    clearInterval(this._runId);
    this._runId = setInterval(() => {
      if (!this._alive) return clearInterval(this._runId);
      const p = Math.min(1, (performance.now() - t0) / DUR);
      this._runFrac = p;
      this.setState({ prog: p });
      if (p >= 1) { clearInterval(this._runId); this.setState({ phase: 'done' }); }
    }, 120);
  }

  componentDidMount() {
    this._syncPillar();
    this._alive = true;
    this._startClock();
    this._boot(0);
  }

  componentWillUnmount() {
    this._alive = false;
    this._stopClock();
    clearInterval(this._runId);
    if (this._raf) cancelAnimationFrame(this._raf);
  }

  _boot(tries) {
    if (!this._alive) return;
    const canvas = document.querySelector('[data-gl="manifest"]');
    if (!canvas) { if (tries < 120) requestAnimationFrame(() => this._boot(tries + 1)); return; }
    this._loop([this._manifestScene(this._engine(), canvas)]);
  }

  // Flight manifest preview: lawnmower lanes, capture points coloured by position source.
  _manifestScene(K, canvas) {
    const R = K.renderer(canvas, [0.016, 0.043, 0.11]);
    if (!R) return null;
    const { Batch, COL, a, lerp, smooth } = K;
    const self = this;
    const placedEl = document.querySelector('[data-hud="placed"]');
    const ground = (x, z) => { const m = smooth(50, 120, Math.hypot(x, z)); return m * (8 * Math.sin(x * 0.04 + 1) * Math.cos(z * 0.035) + 12 * m); };
    const tb = new Batch();
    for (let g = -130; g <= 130; g += 10) for (let u = -130; u < 130; u += 5) {
      const h1 = ground(u, g), h2 = ground(u + 5, g), k1 = ground(g, u), k2 = ground(g, u + 5);
      const c = (h) => [lerp(0.13, 0.42, smooth(0, 20, h)), lerp(0.3, 0.68, smooth(0, 20, h)), lerp(0.72, 1, smooth(0, 20, h)), 0.2 + 0.25 * smooth(0, 20, h)];
      tb.line(u, h1, g, u + 5, h2, g, c(h1), c(h2));
      tb.line(g, k1, u, g, k2, u + 5, c(k1), c(k2));
    }
    const terrain = new Float32Array(tb.a);
    const ALT = 22, pts = [], wps = [];
    for (let i = 0; i < 7; i++) {
      const z = -30 + i * 10, xs = i % 2 ? [45, -45] : [-45, 45];
      wps.push([xs[0], z], [xs[1], z]);
      for (let j = 0; j < 6; j++) pts.push({ x: lerp(xs[0], xs[1], (j + 0.5) / 6), z, i: pts.length });
    }
    let total = 0;
    const segs = [];
    for (let i = 0; i < wps.length - 1; i++) { const len = Math.hypot(wps[i + 1][0] - wps[i][0], wps[i + 1][1] - wps[i][1]); segs.push({ p: wps[i], q: wps[i + 1], len, cum: total }); total += len; }
    const at = (f) => { const d = f * total; for (const s of segs) if (d <= s.cum + s.len) { const t = (d - s.cum) / s.len; return [lerp(s.p[0], s.q[0], t), lerp(s.p[1], s.q[1], t)]; } return wps[wps.length - 1]; };
    let hudT = 0;

    return {
      frame(t, dt) {
        const asp = R.resize();
        const yaw = 0.6 + t * 0.06, pitch = 0.8, rad = 118 * Math.max(1, 1.1 / asp);
        const eye = [rad * Math.cos(pitch) * Math.sin(yaw), rad * Math.sin(pitch), rad * Math.cos(pitch) * Math.cos(yaw)];
        const M = K.camera(asp, eye, [0, 4, 0], 0.7);
        R.begin(M, eye, 90, 300);
        R.draw(terrain, 'lines', 'add');

        const tele = self._tele, running = self.state.phase !== 'ready', f = running ? self._runFrac : (t * 0.05) % 1;
        const files = self._files(self._pillar).filter((x) => self.state.removed.indexOf(x.name) < 0);
        const srcOf = (i) => files.length ? files[i % files.length].gps : 'none';
        const ln = new Batch(), pb = new Batch();
        const pathCol = tele === 'sim' ? COL.warn : COL.cyan;
        segs.forEach((s) => {
          for (let u = 0; u < s.len; u += 2.6) {
            const u2 = Math.min(s.len, u + (tele === 'sim' ? 1.4 : 2.6));
            ln.line(lerp(s.p[0], s.q[0], u / s.len), ALT, lerp(s.p[1], s.q[1], u / s.len), lerp(s.p[0], s.q[0], u2 / s.len), ALT, lerp(s.p[1], s.q[1], u2 / s.len), a(pathCol, 0.35));
          }
        });
        let placed = 0;
        pts.forEach((p) => {
          const src = tele === 'sim' ? 'sim' : srcOf(p.i);
          const place = tele === 'exif' ? src === 'exif' : true;
          const col = !place ? [0.33, 0.39, 0.49] : src === 'exif' ? COL.cyan : src === 'manifest' ? [0.5, 0.7, 1] : COL.warn;
          const lit = !running || p.i / pts.length < f;
          const g = ground(p.x, p.z) + 0.3;
          if (place) placed++;
          pb.v(p.x, ALT, p.z, a(col, lit ? 1 : 0.25));
          if (place && lit) {
            ln.line(p.x, ALT, p.z, p.x, g, p.z, a(col, 0.25), a(col, 0.05));
            ln.ring(p.x, g, p.z, 1.6, 12, a(col, 0.55));
          }
        });
        const dp = at(f), c0 = [dp[0], ALT + 1.5, dp[1]];
        for (let k = 0; k < 4; k++) {
          const an = (k / 4) * Math.PI * 2 + Math.PI / 4 + t * 0.5, ex = c0[0] + Math.cos(an) * 3, ez = c0[2] + Math.sin(an) * 3;
          ln.line(c0[0], c0[1], c0[2], ex, c0[1], ez, a(COL.white, 0.95));
          ln.ring(ex, c0[1] + 0.3, ez, 1.4, 12, a(COL.blue, 0.85));
        }
        [[-6, -4], [6, -4], [6, 4], [-6, 4]].forEach(([lx, lz]) => ln.line(c0[0], c0[1] - 1, c0[2], dp[0] + lx, 0.5, dp[1] + lz, a(COL.cyan, 0.3), a(COL.cyan, 0.05)));
        R.draw(ln, 'lines', 'add');
        R.draw(pb, 'points', 'add', 34);
        hudT += dt;
        if (placedEl && hudT > 0.2) { hudT = 0; placedEl.textContent = placed + ' / ' + pts.length; }
      },
    };
  }



  render() {
    const v = this.renderVals();
    return (
      <div className="pg-new-inspection ds">
        <div className="app">
          <AppRail active="missions" />
          <TopBar crumbs={["Missions","New inspection"]} pillars={v.pillars} />
          <main className="main">
            <div className="ni">
              <div className="ni-head">
                <div>
                  <div className="kicker">
                    <i></i>
                    {"New inspection · draft"}
                  </div>
                  <h1 className="h1" style={{ marginTop: "10px" }}>
                    {"Plan & upload mission"}
                  </h1>
                </div>
                <div className="meta" style={{ paddingBottom: "6px" }}>
                  {"Reserved ID "}{v.reservedId}
                </div>
                <div className="steps">
                  {(v.steps || []).map((s, $index) => (
                    <React.Fragment key={$index}>
                    <div className={`step ${s?.cls ?? ""}`}>
                      <b>
                        {s?.idx}
                      </b>
                      {s?.name}
                    </div>
                    </React.Fragment>
                  ))}
                </div>
              </div>
              <div className="cols">
                <div className="scroll left">
                  <section className="panel">
                    <div className="ph">
                      <div className="sec-t">
                        <span className="idx">
                          {"01"}
                        </span>
                        <span className="lbl strong">
                          {"Pillar & model"}
                        </span>
                      </div>
                      <span className="badge b-sim">
                        {"Demo weights"}
                      </span>
                    </div>
                    <div className="pad">
                      <div className="pcards">
                        {(v.pcards || []).map((c, $index) => (
                          <React.Fragment key={$index}>
                          <button className={`pcard ${c?.cls ?? ""}`} style={{ color: `${c?.color ?? ""}` }} onClick={c?.pick}>
                            {c?.isEnergy ? (
                              <>
                              <svg width="32" height="32" viewBox="0 0 32 32" fill="none" stroke="currentColor" strokeWidth="1.5">
                                <path d="M7 8h18l3 14H4L7 8z"></path>
                                <path d="M16 8v14M5.5 15h21M11.5 8l-1.5 14M20.5 8l1.5 14M16 22v5M11 27h10"></path>
                              </svg>
                              </>
                            ) : null}
                            {c?.isAgri ? (
                              <>
                              <svg width="32" height="32" viewBox="0 0 32 32" fill="none" stroke="currentColor" strokeWidth="1.5">
                                <path d="M6 26C6 14 13 6 27 5c0 14-8 21-21 21z"></path>
                                <path d="M6 26L20 12M13 19h-5M17 15l-1-5"></path>
                              </svg>
                              </>
                            ) : null}
                            {c?.isRescue ? (
                              <>
                              <svg width="32" height="32" viewBox="0 0 32 32" fill="none" stroke="currentColor" strokeWidth="1.5">
                                <circle cx="16" cy="16" r="11"></circle>
                                <path d="M16 2v6M16 24v6M2 16h6M24 16h6"></path>
                                <circle cx="16" cy="13" r="2.2"></circle>
                                <path d="M12.5 21c.6-3 2-4.5 3.5-4.5s2.9 1.5 3.5 4.5"></path>
                              </svg>
                              </>
                            ) : null}
                            <span className="pcard-n">
                              {c?.name}
                            </span>
                            <span className="pcard-m">
                              {c?.model}
                            </span>
                            <span className="pcard-c">
                              {c?.classes}
                            </span>
                          </button>
                          </React.Fragment>
                        ))}
                      </div>
                    </div>
                  </section>
                  <section className="panel">
                    <div className="ph">
                      <div className="sec-t">
                        <span className="idx">
                          {"02"}
                        </span>
                        <span className="lbl strong">
                          {"Media"}
                        </span>
                      </div>
                      <span className="lbl">
                        {"JPG · TIF · MP4 · up to 4 GB"}
                      </span>
                    </div>
                    <div className="pad">
                      <div className="drop" onDragOver={v.dragOver} onDrop={v.onDrop}>
                        <div className="drop-icon">
                          <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
                            <path d="M12 16V4M7 9l5-5 5 5"></path>
                            <path d="M4 15v5h16v-5"></path>
                          </svg>
                        </div>
                        <div>
                          <div className="drop-t">
                            {v.dropTitle}
                          </div>
                          <div className="drop-s">
                            {"RGB, thermal (LWIR) or multispectral. GPS is read from EXIF when present."}
                          </div>
                        </div>
                        <button className="btn btn-ghost btn-sm" onClick={v.browse}>
                          {"Browse files"}
                        </button>
                        <input type="file" multiple accept="image/*,video/*" className="hidden-file" data-file="upload" onChange={v.onFiles} />
                      </div>
                      <div className="files">
                        <table className="tbl">
                          <thead>
                            <tr>
                              <th>
                                {"File"}
                              </th>
                              <th>
                                {"Type"}
                              </th>
                              <th>
                                {"Size"}
                              </th>
                              <th>
                                {"Resolution"}
                              </th>
                              <th>
                                {"Position source"}
                              </th>
                              <th></th>
                            </tr>
                          </thead>
                          <tbody>
                            {(v.files || []).map((f, $index) => (
                              <React.Fragment key={$index}>
                              <tr>
                                <td style={{ color: "#fff" }}>
                                  {f?.name}
                                </td>
                                <td>
                                  {f?.type}
                                </td>
                                <td>
                                  {f?.size}
                                </td>
                                <td>
                                  {f?.res}
                                </td>
                                <td>
                                  <span className={`badge ${f?.bcls ?? ""}`}>
                                    {f?.gps}
                                  </span>
                                </td>
                                <td>
                                  <button className="fx" onClick={f?.remove}>
                                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6">
                                      <path d="M6 6l12 12M18 6L6 18"></path>
                                    </svg>
                                  </button>
                                </td>
                              </tr>
                              </React.Fragment>
                            ))}
                          </tbody>
                        </table>
                        <div className="fsum">
                          <span>
                            <b>
                              {v.fileCount}
                            </b>
                            {" files"}
                          </span>
                          <span>
                            <b>
                              {v.frameCount}
                            </b>
                            {" frames"}
                          </span>
                          <span>
                            <b>
                              {v.exifCount}
                            </b>
                            {" EXIF GPS"}
                          </span>
                          <span>
                            <b>
                              {v.manCount}
                            </b>
                            {" in manifest"}
                          </span>
                          <span>
                            <b>
                              {v.noneCount}
                            </b>
                            {" no position"}
                          </span>
                        </div>
                      </div>
                    </div>
                  </section>
                  <section className="panel">
                    <div className="ph">
                      <div className="sec-t">
                        <span className="idx">
                          {"03"}
                        </span>
                        <span className="lbl strong">
                          {"Telemetry source & inference"}
                        </span>
                      </div>
                    </div>
                    <div className="pad">
                      <div className="tcards">
                        {(v.tcards || []).map((t, $index) => (
                          <React.Fragment key={$index}>
                          <button className={`tcard ${t?.cls ?? ""}`} onClick={t?.pick}>
                            <span className="tcard-top">
                              <span className="radio"></span>
                              <span className={`badge ${t?.bcls ?? ""}`}>
                                {t?.badge}
                              </span>
                            </span>
                            <span className="tcard-n">
                              {t?.name}
                            </span>
                            <span className="tcard-d">
                              {t?.desc}
                            </span>
                            <span className="tcard-f">
                              {t?.field}
                            </span>
                          </button>
                          </React.Fragment>
                        ))}
                      </div>
                      <div className="warn">
                        <i className="dia sev-warn"></i>
                        <span>
                          {v.teleWarn}
                        </span>
                      </div>
                      <div className="opts">
                        <div className="opt">
                          <span className="lbl">
                            {"Confidence threshold"}
                          </span>
                          <div className="segs">
                            {(v.thresholds || []).map((c, $index) => (
                              <React.Fragment key={$index}>
                              <button className={c?.cls} onClick={c?.pick}>
                                {c?.name}
                              </button>
                              </React.Fragment>
                            ))}
                          </div>
                        </div>
                        <button className={`ck ${v.saveCls ?? ""}`} onClick={v.toggleSave}>
                          <i></i>
                          {"Save annotated frames"}
                        </button>
                      </div>
                    </div>
                  </section>
                </div>
                <div className="right">
                  <section className="panel">
                    <div className="ph">
                      <span className="lbl strong">
                        {"Flight manifest preview"}
                      </span>
                      <span className={`badge ${v.tele?.bcls ?? ""}`}>
                        {v.tele?.badge}
                      </span>
                    </div>
                    <div className="preview">
                      <canvas className="gl" data-gl="manifest"></canvas>
                      <div className="glass pv-count">
                        <span className="lbl">
                          {"Capture points placed"}
                        </span>
                        <b data-hud="placed">
                          {"0 / 0"}
                        </b>
                      </div>
                      <div className="glass pv-legend">
                        <span>
                          <i className="dia" style={{ background: "#5CE1FF" }}></i>
                          {"EXIF GPS"}
                        </span>
                        <span>
                          <i className="dia" style={{ background: "#7FB2FF" }}></i>
                          {"Manifest match"}
                        </span>
                        <span>
                          <i className="dia" style={{ background: "#FFB547" }}></i>
                          {"Simulated / interpolated"}
                        </span>
                        <span>
                          <i className="dia dia-off" style={{ boxShadow: "inset 0 0 0 1px #53637D" }}></i>
                          {"Not placed"}
                        </span>
                      </div>
                    </div>
                  </section>
                  <section className="panel run">
                    <div className="sec-t" style={{ justifyContent: "space-between" }}>
                      <div className="sec-t">
                        <span className="idx">
                          {"04"}
                        </span>
                        <span className="lbl strong">
                          {"Review & run"}
                        </span>
                      </div>
                      <span className={`chip ${v.runChipCls ?? ""}`}>
                        {v.runChip}
                      </span>
                    </div>
                    {v.isReady ? (
                      <>
                      <div>
                        <div className="kv2" style={{ marginTop: "14px" }}>
                          <div>
                            <span className="lbl">
                              {"Pillar"}
                            </span>
                            <b>
                              {v.pc?.name}{" · "}{v.pc?.long}
                            </b>
                          </div>
                          <div>
                            <span className="lbl">
                              {"Model"}
                            </span>
                            <b>
                              {v.pc?.model}
                            </b>
                          </div>
                          <div>
                            <span className="lbl">
                              {"Frames"}
                            </span>
                            <b>
                              {v.frameCount}
                            </b>
                          </div>
                          <div>
                            <span className="lbl">
                              {"Telemetry"}
                            </span>
                            <b>
                              {v.tele?.name}
                            </b>
                          </div>
                          <div>
                            <span className="lbl">
                              {"Threshold"}
                            </span>
                            <b>
                              {v.thrStr}
                            </b>
                          </div>
                          <div>
                            <span className="lbl">
                              {"Endpoint"}
                            </span>
                            <b>
                              {"POST /api/v1/infer/"}{v.pc?.key}
                            </b>
                          </div>
                        </div>
                        <button className="btn btn-primary btn-block" onClick={v.run}>
                          {"Run inference"}
                        </button>
                      </div>
                      </>
                    ) : null}
                    {v.isRunning ? (
                      <>
                      <div className="stages" style={{ marginTop: "14px" }}>
                        {(v.stages || []).map((g, $index) => (
                          <React.Fragment key={$index}>
                          <div className={`stg ${g?.cls ?? ""}`}>
                            <i className={`dia ${g?.dia ?? ""}`}></i>
                            <span>
                              {g?.name}
                            </span>
                            <span className="bar3">
                              <b style={{ width: `${g?.w ?? ""}` }}></b>
                            </span>
                            <em>
                              {g?.pct}
                            </em>
                          </div>
                          </React.Fragment>
                        ))}
                      </div>
                      </>
                    ) : null}
                    {v.isDone ? (
                      <>
                      <div>
                        <div className="done-box">
                          <i className="dia sev-ok" style={{ width: "12px", height: "12px" }}></i>
                          <div>
                            <b>
                              {"Inference complete"}
                            </b>
                            <span>
                              {v.doneNote}
                            </span>
                          </div>
                        </div>
                        <div className="row-btns">
                          <Link className="btn btn-go" href={'/missions/' + (v.sessionId || (v.pc ? v.pc.mission : 'AER-EN-0142'))}>
                            {"Open mission twin →"}
                          </Link>
                          <button className="btn btn-ghost" onClick={v.reset}>
                            {"Start another"}
                          </button>
                        </div>
                      </div>
                      </>
                    ) : null}
                  </section>
                </div>
              </div>
            </div>
          </main>
        </div>
      </div>
    );
  }
}

export default View;
