'use client';
/* eslint-disable */
// Generated by scripts/convert-designs.mjs from design/landing-page/Platform.template.html — edit the design or the patches, then re-run.
import React from 'react';
import Link from 'next/link';
import Base from './_base';
import { MkNav, MkFoot } from '@/components/chrome';
import { getPillar, setPillar, readJSON, writeJSON, signIn, signOut, saveSession, downloadFile } from '@/lib/store';
import { API_URL, pingApi, inferFile, submitRequest } from '@/lib/api';
import { sessionData } from '@/lib/session';
import './css/Platform.css';

class View extends Base {
  constructor(props) {
    super(props);
    this.state = { stage: 2 };
    this._stage = 2;
  }

  _stages() {
    return [
      ['Capture', 'RGB, thermal and multispectral frames are recorded by the drone and uploaded as images or video.', [['Inputs', 'JPG · TIF · MP4'], ['Sources', 'RGB · LWIR · multispectral']], 'Upload flow built', 'b-live'],
      ['Telemetry', 'Each frame gets a position. EXIF GPS is used first, then a flight manifest, then a simulated lawnmower path, and the source is recorded.', [['Order', 'EXIF → manifest → simulated'], ['Code', 'backend/telemetry.py']], 'Manifest fallback', 'b-man'],
      ['Inference', 'A pillar-specific YOLO model finds defects, disease or people and returns boxes with confidence scores.', [['Endpoint', 'POST /api/v1/infer/{pillar}'], ['Models', 'YOLOv8n fine-tuned · 640 px'], ['Threshold', 'confidence ≥ 0.50']], 'Running in FastAPI', 'b-live'],
      ['Normalize', 'Every model answers in the same schema, so energy, agri and rescue detections can share one map and one report.', [['Fields', 'class · confidence · bbox_xyxy'], ['Timing', 'inference_time_ms']], 'Schema defined', 'b-live'],
      ['Geo-map', 'Pixel boxes are projected to site coordinates using the frame position, altitude and heading. Precision follows the telemetry source.', [['Output', 'lat · lng · world offset'], ['Accuracy', 'approximate without RTK']], 'Approximate positions', 'b-sim'],
      ['Digital twin', 'Detections become markers on a 3D model of the site, with the flight path, coverage and inspection dossiers.', [['Views', '3D · top · follow drone'], ['Renderer', 'Three.js / WebGL']], 'In the command center', 'b-live'],
      ['Action', 'Operators assign crews, dispatch teams and export PDF or JSON reports built from the session data.', [['Exports', 'PDF · JSON'], ['Rule', 'provenance statement always included']], 'Demo mode', 'b-sim'],
    ].map(([name, body, facts, badge, bcls], i) => ({ idx: String(i + 1).padStart(2, '0'), name, body, facts: facts.map(([k, v]) => ({ k, v })), badge, bcls }));
  }

  renderVals() {
    const S = this._stages();
    const { stage } = this.state;
    this._stage = stage;
    return {
      cur: S[stage],
      stages: S.map((s, i) => ({ idx: s.idx, name: s.name, cls: i === stage ? 'on' : '', pick: () => this.setState({ stage: i }) })),
      fields: [
        ['pillar', 'energy, agri or rescue: picks the model and the vocabulary.'],
        ['telemetry', 'Position and attitude of the aircraft when the frame was taken, tagged with its source.'],
        ['detections[]', 'One entry per object: class, confidence and a pixel bounding box.'],
        ['bbox_xyxy', 'Box corners in image pixels, used for crops and for projection to the ground.'],
        ['inference_time_ms', 'Measured model time for the frame, surfaced in analytics.'],
      ].map(([k, v]) => ({ k, v })),
      ladder: [
        ['Live GPS', 'b-live', 'Streamed from the aircraft during flight. RTK-grade when the hardware has it.', 'Roadmap'],
        ['EXIF', 'b-exif', 'Read from the image file. As accurate as the drone’s own GPS.', 'Supported'],
        ['Manifest', 'b-man', 'Matched to a planned flight path by filename. Positions are approximate.', 'Supported'],
        ['Simulated', 'b-sim', 'Generated for demonstrations. Never shown as a field measurement.', 'Golden demo'],
      ].map(([badge, bcls, body, state]) => ({ badge, bcls, body, state })),
      tech: [
        ['Detection', 'Ultralytics YOLOv8', 'Three fine-tuned nano models, one per pillar, trained at 640 px for 15 epochs.'],
        ['API', 'FastAPI', 'Accepts uploads per pillar and returns the normalized detection schema.'],
        ['Frontend', 'Next.js + TypeScript', 'The command center, reports and marketing site in one app.'],
        ['3D', 'Three.js', 'Digital twins, flight playback, live feeds and the hangar.'],
        ['Data (planned)', 'PostGIS', 'Sites, missions and detections as geospatial records.'],
        ['Telemetry (planned)', 'WebSocket · MQTT', 'Live aircraft streams replacing manifest positions.'],
      ].map(([role, name, body]) => ({ role, name, body })),
      road: [
        ['Now', '#5CE1FF', ['Three fine-tuned pillar models', 'Manifest and simulated telemetry', '3D command center and reports', 'Golden demo over Rajkot']],
        ['Next', '#FFB547', ['Live telemetry over WebSocket', 'Validation sets and accuracy tracking', 'Multi-tenant organizations and roles', 'Audit logging']],
        ['Later', '#9BE15D', ['RTK GPS and survey-grade positions', 'MQTT fleet gateway', 'Orthomosaics, DEM/DSM and satellite layers', 'Mission planning sent to aircraft']],
      ].map(([name, color, items]) => ({ name, color, items: items.map((t) => ({ t })) })),
    };
  }

  componentDidMount() {
    this._syncPillar(); this._alive = true; this._boot(0); }
  componentWillUnmount() { this._alive = false; if (this._raf) cancelAnimationFrame(this._raf); if (this._pipe) this._pipe.destroy(); }

  _boot(tries) {
    if (!this._alive) return;
    const canvas = document.querySelector('[data-gl="pipe"]');
    if (!canvas) { if (tries < 120) requestAnimationFrame(() => this._boot(tries + 1)); return; }
    this._pipe = this._pipeScene(this._engine(), canvas, document.querySelector('[data-gl-labels="pipe"]'));
    this._loop([this._pipe]);
  }

  // Seven stage nodes on an S-curve; packets flow between them; the selected node lifts and glows.
  _pipeScene(K, canvas, labelsEl) {
    const R = K.renderer(canvas, [0.016, 0.043, 0.11]);
    if (!R) return null;
    const { Batch, COL, a, lerp, clamp } = K;
    const self = this;
    const names = this._stages().map((s) => s.name);
    const nodes = names.map((n, i) => {
      const u = i / (names.length - 1);
      const el = labelsEl ? document.createElement('div') : null;
      if (el) { el.className = 'gl-tag'; el.style.color = '#5CE1FF'; el.textContent = n.toUpperCase(); labelsEl.appendChild(el); }
      return { x: lerp(-66, 66, u), z: Math.sin(u * Math.PI * 2) * 16, lift: 0, el, sx: -1, sy: -1 };
    });
    const grid = new Batch();
    for (let g = -120; g <= 120; g += 8) { grid.line(g, -8, -60, g, -8, 60, [0.3, 0.55, 1, 0.07]); grid.line(-120, -8, g * 0.5, 120, -8, g * 0.5, [0.3, 0.55, 1, 0.07]); }
    const gridArr = new Float32Array(grid.a);
    const onUp = (e) => {
      const r = canvas.getBoundingClientRect();
      const px = (e.clientX - r.left) * canvas.clientWidth / Math.max(1, r.width), py = (e.clientY - r.top) * canvas.clientHeight / Math.max(1, r.height);
      let best = -1, bd = 40;
      nodes.forEach((n, i) => { const d = Math.hypot(n.sx - px, n.sy - py); if (d < bd) { bd = d; best = i; } });
      if (best >= 0) self.setState({ stage: best });
    };
    canvas.addEventListener('pointerup', onUp);

    return {
      destroy() { canvas.removeEventListener('pointerup', onUp); },
      frame(t, dt) {
        const asp = R.resize();
        const sel = nodes[self._stage] || nodes[0];
        const cy = 0.15 + Math.sin(t * 0.1) * 0.12, rad = 150 * Math.max(1, 1.5 / asp);
        const T = [sel.x * 0.25, 4, 0];
        const eye = [T[0] + rad * Math.cos(0.42) * Math.sin(cy), T[1] + rad * Math.sin(0.42), T[2] + rad * Math.cos(0.42) * Math.cos(cy)];
        const M = K.camera(asp, eye, T, 0.62);
        R.begin(M, eye, 100, 300);
        R.draw(gridArr, 'lines', 'add');
        const ln = new Batch(), fill = new Batch(), pts = new Batch();
        for (let i = 0; i < nodes.length - 1; i++) {
          const A = nodes[i], B = nodes[i + 1];
          for (let k = 0; k < 20; k++) {
            const u1 = k / 20, u2 = (k + 1) / 20;
            ln.line(lerp(A.x, B.x, u1), lerp(A.lift, B.lift, u1), lerp(A.z, B.z, u1), lerp(A.x, B.x, u2), lerp(A.lift, B.lift, u2), lerp(A.z, B.z, u2), a(COL.blue, 0.35));
          }
          for (let p = 0; p < 3; p++) {
            const u = (t * 0.5 + p / 3 + i * 0.11) % 1;
            pts.v(lerp(A.x, B.x, u), lerp(A.lift, B.lift, u) + 0.2, lerp(A.z, B.z, u), a(COL.cyan, 1));
          }
        }
        nodes.forEach((n, i) => {
          const on = i === self._stage;
          n.lift = lerp(n.lift, on ? 6 : 0, Math.min(1, dt * 3));
          const c = on ? COL.cyan : COL.blue, r = on ? 7 : 5.5, spin = t * (on ? 0.6 : 0.15) + i;
          const top = n.lift + 2, bot = n.lift - 2;
          const hx = Array.from({ length: 6 }, (_, k) => { const an = (k / 6) * Math.PI * 2 + spin; return [n.x + Math.cos(an) * r, n.z + Math.sin(an) * r]; });
          for (let k = 0; k < 6; k++) {
            const p = hx[k], q = hx[(k + 1) % 6];
            ln.line(p[0], top, p[1], q[0], top, q[1], a(c, 0.95));
            ln.line(p[0], bot, p[1], q[0], bot, q[1], a(c, 0.4));
            ln.line(p[0], bot, p[1], p[0], top, p[1], a(c, 0.35));
            fill.tri([n.x, top, n.z], [p[0], top, p[1]], [q[0], top, q[1]], a(c, on ? 0.22 : 0.07));
          }
          ln.line(n.x, bot, n.z, n.x, -8, n.z, a(c, 0.15));
          if (on) { const ph = (t * 0.7) % 1; ln.ring(n.x, top, n.z, r + ph * 10, 30, a(COL.cyan, 0.7 * (1 - ph))); }
          const sp = K.project(M, n.x, top + 5, n.z, R.w, R.h), hit = K.project(M, n.x, n.lift, n.z, R.w, R.h);
          if (hit) { n.sx = hit[0]; n.sy = hit[1]; }
          if (n.el) {
            if (sp) { n.el.style.opacity = '1'; n.el.className = on ? 'gl-tag sel' : 'gl-tag'; n.el.style.transform = 'translate(' + sp[0].toFixed(1) + 'px,' + sp[1].toFixed(1) + 'px) translate(-50%,-100%)'; }
            else n.el.style.opacity = '0';
          }
        });
        self._drawDrone(K, ln, nodes[0].x - 4, 16 + Math.sin(t * 1.3), nodes[0].z, t * 0.4, 1.4, t, { legs: false });
        const last = nodes[nodes.length - 1];
        [[-3, -4], [3, -4], [3, 4], [-3, 4]].forEach(([dx, dz], k, arr) => { const q = arr[(k + 1) % 4]; ln.line(last.x + 10 + dx, 10, last.z + dz, last.x + 10 + q[0], 10, last.z + q[1], a(COL.white, 0.6)); });
        R.draw(fill, 'tris', 'alpha');
        R.draw(ln, 'lines', 'add');
        R.draw(pts, 'points', 'add', 26);
      },
    };
  }



  render() {
    const v = this.renderVals();
    return (
      <div className="pg-platform ds">
        <div className="mk">
          <MkNav active="platform" />
          <section className="hero">
            <canvas className="gl" data-gl="pipe"></canvas>
            <div className="gl-labels" data-gl-labels="pipe"></div>
            <div className="mk-shade"></div>
            <div className="hero-copy">
              <div className="kicker">
                <i></i>
                {"Platform"}
              </div>
              <h1 className="mk-h1">
                {"One engine,"}
                <br />
                <span>
                  {"seven stages."}
                </span>
              </h1>
              <p className="mk-lede">
                {"Every Aerolytics mission moves through the same pipeline, from the first frame to the final report. Pick a stage to see what it does and what runs it today."}
              </p>
              <div className="mk-cta">
                <Link className="btn btn-primary" href={'/contact'}>
                  {"Request a pilot"}
                </Link>
                <Link className="btn btn-ghost" href={'/demo'}>
                  {"Open the demo"}
                </Link>
              </div>
            </div>
            <aside className="glass stage-card">
              <div className="kicker">
                <i></i>
                {"Stage "}{v.cur?.idx}{" of 7"}
              </div>
              <h2 className="h2">
                {v.cur?.name}
              </h2>
              <p>
                {v.cur?.body}
              </p>
              <div style={{ marginTop: "14px" }}>
                {(v.cur?.facts || []).map((f, $index) => (
                  <React.Fragment key={$index}>
                  <div className="kvl-row">
                    <span>
                      {f?.k}
                    </span>
                    <b>
                      {f?.v}
                    </b>
                    <i></i>
                  </div>
                  </React.Fragment>
                ))}
              </div>
              <div style={{ marginTop: "14px" }}>
                <span className={`badge ${v.cur?.bcls ?? ""}`}>
                  {v.cur?.badge}
                </span>
              </div>
            </aside>
            <div className="stage-nav">
              {(v.stages || []).map((s, $index) => (
                <React.Fragment key={$index}>
                <button className={`sn ${s?.cls ?? ""}`} onClick={s?.pick}>
                  <small>
                    {s?.idx}
                  </small>
                  <span>
                    {s?.name}
                  </span>
                </button>
                </React.Fragment>
              ))}
            </div>
          </section>
          <section className="mk-sec">
            <div className="kicker">
              <i></i>
              {"01 / One response schema"}
            </div>
            <h2 className="mk-h2">
              {"Every pillar answers in the same shape."}
            </h2>
            <div className="schema">
              <div className="code">
                <div>
                  <span className="p">
                    {"{"}
                  </span>
                </div>
                <div>
                  {" "}
                  <span className="k">
                    {"\"pillar\""}
                  </span>
                  <span className="p">
                    {": "}
                  </span>
                  <span className="s">
                    {"\"energy\""}
                  </span>
                  <span className="p">
                    {","}
                  </span>
                </div>
                <div>
                  {" "}
                  <span className="k">
                    {"\"filename\""}
                  </span>
                  <span className="p">
                    {": "}
                  </span>
                  <span className="s">
                    {"\"solar_01.jpg\""}
                  </span>
                  <span className="p">
                    {","}
                  </span>
                </div>
                <div>
                  {" "}
                  <span className="k">
                    {"\"telemetry\""}
                  </span>
                  <span className="p">
                    {": { "}
                  </span>
                  <span className="k">
                    {"\"lat\""}
                  </span>
                  <span className="p">
                    {": "}
                  </span>
                  <span className="n">
                    {"22.3001"}
                  </span>
                  <span className="p">
                    {", "}
                  </span>
                  <span className="k">
                    {"\"lng\""}
                  </span>
                  <span className="p">
                    {": "}
                  </span>
                  <span className="n">
                    {"70.8001"}
                  </span>
                  <span className="p">
                    {","}
                  </span>
                </div>
                <div>
                  {" "}
                  <span className="k">
                    {"\"alt\""}
                  </span>
                  <span className="p">
                    {": "}
                  </span>
                  <span className="n">
                    {"45.0"}
                  </span>
                  <span className="p">
                    {", "}
                  </span>
                  <span className="k">
                    {"\"heading\""}
                  </span>
                  <span className="p">
                    {": "}
                  </span>
                  <span className="n">
                    {"90.0"}
                  </span>
                  <span className="p">
                    {" },"}
                  </span>
                </div>
                <div>
                  {" "}
                  <span className="k">
                    {"\"detections\""}
                  </span>
                  <span className="p">
                    {": ["}
                  </span>
                </div>
                <div>
                  {" "}
                  <span className="p">
                    {"{ "}
                  </span>
                  <span className="k">
                    {"\"class\""}
                  </span>
                  <span className="p">
                    {": "}
                  </span>
                  <span className="s">
                    {"\"crack\""}
                  </span>
                  <span className="p">
                    {", "}
                  </span>
                  <span className="k">
                    {"\"confidence\""}
                  </span>
                  <span className="p">
                    {": "}
                  </span>
                  <span className="n">
                    {"0.91"}
                  </span>
                  <span className="p">
                    {","}
                  </span>
                </div>
                <div>
                  {" "}
                  <span className="k">
                    {"\"bbox_xyxy\""}
                  </span>
                  <span className="p">
                    {": ["}
                  </span>
                  <span className="n">
                    {"412.0, 228.0, 538.0, 341.0"}
                  </span>
                  <span className="p">
                    {"] }"}
                  </span>
                </div>
                <div>
                  {" "}
                  <span className="p">
                    {"],"}
                  </span>
                </div>
                <div>
                  {" "}
                  <span className="k">
                    {"\"inference_time_ms\""}
                  </span>
                  <span className="p">
                    {": "}
                  </span>
                  <span className="n">
                    {"38.4"}
                  </span>
                </div>
                <div>
                  <span className="p">
                    {"}"}
                  </span>
                </div>
              </div>
              <div className="fields">
                {(v.fields || []).map((f, $index) => (
                  <React.Fragment key={$index}>
                  <div className="fld">
                    <b>
                      {f?.k}
                    </b>
                    <span>
                      {f?.v}
                    </span>
                  </div>
                  </React.Fragment>
                ))}
              </div>
            </div>
          </section>
          <section className="mk-sec">
            <div className="kicker">
              <i></i>
              {"02 / Provenance"}
            </div>
            <h2 className="mk-h2">
              {"Where every coordinate comes from."}
            </h2>
            <div className="ladder">
              {(v.ladder || []).map((r, $index) => (
                <React.Fragment key={$index}>
                <div className="panel rung">
                  <span className={`badge ${r?.bcls ?? ""}`}>
                    {r?.badge}
                  </span>
                  <p>
                    {r?.body}
                  </p>
                  <div className="meta">
                    {r?.state}
                  </div>
                </div>
                </React.Fragment>
              ))}
            </div>
          </section>
          <section className="mk-sec">
            <div className="kicker">
              <i></i>
              {"03 / Built on"}
            </div>
            <h2 className="mk-h2">
              {"Open, proven components."}
            </h2>
            <div className="stack">
              {(v.tech || []).map((t, $index) => (
                <React.Fragment key={$index}>
                <div className="panel tech">
                  <div className="lbl">
                    {t?.role}
                  </div>
                  <h3>
                    {t?.name}
                  </h3>
                  <p>
                    {t?.body}
                  </p>
                </div>
                </React.Fragment>
              ))}
            </div>
          </section>
          <section className="mk-sec">
            <div className="kicker">
              <i></i>
              {"04 / Roadmap"}
            </div>
            <h2 className="mk-h2">
              {"From golden demo to live fleet."}
            </h2>
            <div className="road">
              {(v.road || []).map((c, $index) => (
                <React.Fragment key={$index}>
                <div className="col">
                  <h3 style={{ color: `${c?.color ?? ""}` }}>
                    {c?.name}
                  </h3>
                  <ul>
                    {(c?.items || []).map((i, $index) => (
                      <React.Fragment key={$index}>
                      <li>
                        <i className="dia" style={{ background: `${c?.color ?? ""}` }}></i>
                        {i?.t}
                      </li>
                      </React.Fragment>
                    ))}
                  </ul>
                </div>
                </React.Fragment>
              ))}
            </div>
          </section>
          <MkFoot />
        </div>
      </div>
    );
  }
}

export default View;
