'use client';
/* eslint-disable */
// Generated by scripts/convert-designs.mjs from design/landing-page/Reports.template.html — edit the design or the patches, then re-run.
import React from 'react';
import Link from 'next/link';
import Base from './_base';
import { AppRail, TopBar } from '@/components/chrome';
import { getPillar, setPillar, readJSON, writeJSON, signIn, signOut, saveSession, downloadFile } from '@/lib/store';
import { API_URL, pingApi, inferFile, submitRequest } from '@/lib/api';
import { sessionData } from '@/lib/session';
import './css/Reports.css';

class View extends Base {
  constructor(props) {
    super(props);
    this.state = { pillar: 'energy', fmt: 'all', tab: 'gen', sel: null, off: [] };
  }

  _reports() {
    const D = this._data();
    const out = [];
    D.missionsAll.filter((m) => m.status === 'Complete').forEach((m, i) => {
      const parts = m.det.split(' / ');
      ['PDF', 'JSON'].forEach((fmt, j) => {
        if (j === 1 && i % 2) return;
        out.push({
          id: 'RPT-' + m.id.slice(-4) + '-' + (j ? 'J' : 'P'), mission: m.id, pillar: m.pillar, fmt, site: m.site,
          size: fmt === 'PDF' ? (0.9 + (i % 4) * 0.12).toFixed(1) + ' MB · 2 p' : (5 + (i % 5)) + ' KB',
          tele: m.tele, tcls: m.tcls, date: m.date, by: m.operator, frames: m.frames, coverage: m.coverage,
          crit: parts[0] || '0', total: parts[1] || '0',
          status: i === 3 && j === 0 ? 'Superseded' : 'Ready',
        });
      });
    });
    return out;
  }

  renderVals() {
    const D = this._data();
    const { pillar, fmt, tab, sel, off } = this.state;
    const all = this._reports();
    const rows = all.filter((r) => fmt === 'all' || r.fmt.toLowerCase() === fmt);
    const cur0 = all.find((r) => r.id === sel) || rows[0] || all[0];
    const deco = (r) => Object.assign({}, r, {
      chip: D.P[r.pillar].chip, pillarName: D.P[r.pillar].name, fmtCls: r.fmt === 'JSON' ? 'json' : '',
      stCls: r.status === 'Ready' ? 'st-resolved' : 'st-off', teleLower: r.tele.toLowerCase() === 'exif' ? 'from EXIF GPS' : r.tele.toLowerCase(),
    });
    const cur = deco(cur0);
    const schedules = [
      ['weekly-solar', 'Weekly solar summary', 'Energy · all solar sites', 'Every Mon · 09:00 IST', '21 Sep 2026 09:00'],
      ['agri-disease', 'Disease spread digest', 'Agri · Kalawad Rd blocks', 'Every 3 days · 07:00 IST', '17 Sep 2026 07:00'],
      ['rescue-afteraction', 'After-action report', 'Rescue · on mission close', 'On mission complete', 'Event-driven'],
      ['monthly-exec', 'Monthly operations pack', 'All pillars · PDF', '1st of month · 10:00 IST', '01 Oct 2026 10:00'],
    ];
    return {
      pillars: this._pillarTabs(pillar, (k) => { const r = all.find((x) => x.pillar === k); this.setState({ pillar: k, sel: r ? r.id : sel }); }),
      count: all.length,
      schedCount: schedules.length,
      formats: [['all', 'All'], ['pdf', 'PDF'], ['json', 'JSON']].map(([k, name]) => ({ name, cls: fmt === k ? 'on' : '', pick: () => this.setState({ fmt: k }) })),
      tabs: [['gen', 'Generated', rows.length], ['sched', 'Scheduled', schedules.length]].map(([k, name, n]) => ({ name, n, cls: tab === k ? 'on' : '', pick: () => this.setState({ tab: k }) })),
      isGen: tab === 'gen', isSched: tab === 'sched',
      rows: rows.map((r) => Object.assign(deco(r), { selCls: r.id === cur.id ? 'sel' : '', pick: () => this.setState({ sel: r.id }) })),
      schedules: schedules.map(([key, name, scope, cadence, next]) => ({
        name, scope, cadence, next, to: '[DISTRIBUTION LIST]', cls: off.indexOf(key) >= 0 ? '' : 'on',
        toggle: () => this.setState({ off: off.indexOf(key) >= 0 ? off.filter((x) => x !== key) : off.concat(key) }),
      })),
      cur,
      downloadCur: () => downloadFile(cur.id + '.json', JSON.stringify(cur, null, 2)),
      copyLabel: this.state.copied ? 'Link copied' : 'Copy share link',
      copyLink: () => { try { navigator.clipboard.writeText(window.location.origin + '/missions/' + cur.mission + '/report'); } catch (e) {} this.setState({ copied: true }); setTimeout(() => this._alive !== false && this.setState({ copied: false }), 1600); },
      details: [
        ['Mission', cur.mission], ['Site', cur.site], ['Generated', cur.date + ' UTC · ' + cur.by], ['Telemetry', cur.tele + ' · labelled in report'],
        ['Detections', cur.crit + ' critical / ' + cur.total + ' total'], ['Checksum', 'SHA-256 computed on export'], ['Retention', '[RETENTION POLICY]'],
      ].map(([k, v]) => ({ k, v })),
    };
  }

  componentDidMount() {
    this._syncPillar(); this._alive = true; this._startClock(); }
  componentWillUnmount() { this._alive = false; this._stopClock(); }



  render() {
    const v = this.renderVals();
    return (
      <div className="pg-reports ds">
        <div className="app">
          <AppRail active="reports" />
          <TopBar crumbs={["Command center","Reports"]} pillars={v.pillars} />
          <main className="main">
            <div className="page">
              <div className="page-head">
                <div>
                  <div className="kicker">
                    <i></i>
                    {"Reports archive"}
                  </div>
                  <h1 className="h1" style={{ marginTop: "10px" }}>
                    {"Reports"}
                  </h1>
                </div>
                <div className="meta">
                  {v.count}{" generated · "}{v.schedCount}{" schedules · sample"}
                </div>
                <div className="acts">
                  <div className="segs">
                    {(v.formats || []).map((f, $index) => (
                      <React.Fragment key={$index}>
                      <button className={f?.cls} onClick={f?.pick}>
                        {f?.name}
                      </button>
                      </React.Fragment>
                    ))}
                  </div>
                  <button className="btn btn-primary" onClick={() => alert('New mission summary report generation triggered. Processing thermal & AI defect analytics...')}>
                    {"+ Generate report"}
                  </button>
                </div>
              </div>
              <div className="cols">
                <section className="panel">
                  <div className="tabs">
                    {(v.tabs || []).map((t, $index) => (
                      <React.Fragment key={$index}>
                      <button className={`tab ${t?.cls ?? ""}`} onClick={t?.pick}>
                        {t?.name}
                        <em>
                          {t?.n}
                        </em>
                      </button>
                      </React.Fragment>
                    ))}
                  </div>
                  {v.isGen ? (
                    <>
                    <div className="scroll" style={{ flex: "1" }}>
                      <table className="tbl">
                        <thead>
                          <tr>
                            <th>
                              {"Report"}
                            </th>
                            <th>
                              {"Mission"}
                            </th>
                            <th>
                              {"Pillar"}
                            </th>
                            <th>
                              {"Format"}
                            </th>
                            <th>
                              {"Size"}
                            </th>
                            <th>
                              {"Telemetry"}
                            </th>
                            <th>
                              {"Generated (UTC)"}
                            </th>
                            <th>
                              {"By"}
                            </th>
                            <th>
                              {"Status"}
                            </th>
                          </tr>
                        </thead>
                        <tbody>
                          {(v.rows || []).map((r, $index) => (
                            <React.Fragment key={$index}>
                            <tr className={r?.selCls} onClick={r?.pick}>
                              <td style={{ color: "#fff" }}>
                                {r?.id}
                              </td>
                              <td>
                                {r?.mission}
                              </td>
                              <td>
                                <span className={`chip ${r?.chip ?? ""}`}>
                                  {r?.pillarName}
                                </span>
                              </td>
                              <td>
                                <span className={`fmt ${r?.fmtCls ?? ""}`}>
                                  {r?.fmt}
                                </span>
                              </td>
                              <td>
                                {r?.size}
                              </td>
                              <td>
                                <span className={`badge ${r?.tcls ?? ""}`}>
                                  {r?.tele}
                                </span>
                              </td>
                              <td>
                                {r?.date}
                              </td>
                              <td>
                                {r?.by}
                              </td>
                              <td>
                                <span className={`chip ${r?.stCls ?? ""}`}>
                                  {r?.status}
                                </span>
                              </td>
                            </tr>
                            </React.Fragment>
                          ))}
                        </tbody>
                      </table>
                    </div>
                    </>
                  ) : null}
                  {v.isSched ? (
                    <>
                    <div className="scroll" style={{ flex: "1" }}>
                      {(v.schedules || []).map((s, $index) => (
                        <React.Fragment key={$index}>
                        <div className="li sched">
                          <span style={{ minWidth: "0" }}>
                            <span className="li-t">
                              {s?.name}
                            </span>
                            <span className="li-s">
                              {s?.scope}{" · to "}{s?.to}
                            </span>
                          </span>
                          <span>
                            <span className="lbl">
                              {"Cadence"}
                            </span>
                            <span className="li-s" style={{ color: "#CFDAEE" }}>
                              {s?.cadence}
                            </span>
                          </span>
                          <span>
                            <span className="lbl">
                              {"Next run"}
                            </span>
                            <span className="li-s" style={{ color: "#CFDAEE" }}>
                              {s?.next}
                            </span>
                          </span>
                          <button className={`toggle ${s?.cls ?? ""}`} onClick={s?.toggle}>
                            <i></i>
                          </button>
                        </div>
                        </React.Fragment>
                      ))}
                    </div>
                    <div className="note">
                      {"Scheduled delivery needs an email or webhook integration · not connected in the demo"}
                    </div>
                    </>
                  ) : null}
                </section>
                <section className="panel pv">
                  <div className="ph">
                    <span className="lbl strong">
                      {"Preview · "}{v.cur?.id}
                    </span>
                    <span className={`fmt ${v.cur?.fmtCls ?? ""}`}>
                      {v.cur?.fmt}
                    </span>
                  </div>
                  <div className="pv-stage">
                    <div className="mini">
                      <div className="mini-h">
                        <img src="/brand/logo-mark.png" alt="" />
                        <b>
                          {"Aerolytics"}
                        </b>
                        <span>
                          {v.cur?.pillarName}{" report"}
                        </span>
                      </div>
                      <div className="mini-t">
                        {v.cur?.site}
                      </div>
                      <div className="mini-p">
                        <b>
                          {"Data provenance."}
                        </b>
                        {" Telemetry "}{v.cur?.teleLower}{". Coordinates approximate. Demo weights, not validated field measurements."}
                      </div>
                      <div className="mini-k">
                        <div>
                          {"Frames"}
                          <b>
                            {v.cur?.frames}
                          </b>
                        </div>
                        <div>
                          {"Crit"}
                          <b>
                            {v.cur?.crit}
                          </b>
                        </div>
                        <div>
                          {"Total"}
                          <b>
                            {v.cur?.total}
                          </b>
                        </div>
                        <div>
                          {"Cov."}
                          <b>
                            {v.cur?.coverage}{"%"}
                          </b>
                        </div>
                      </div>
                      <div className="mini-map"></div>
                      <div className="mini-rows">
                        <i style={{ width: "100%" }}></i>
                        <i style={{ width: "92%" }}></i>
                        <i style={{ width: "96%" }}></i>
                        <i style={{ width: "80%" }}></i>
                      </div>
                    </div>
                  </div>
                  <div className="scroll pv-body">
                    {(v.details || []).map((d, $index) => (
                      <React.Fragment key={$index}>
                      <div className="kvl-row">
                        <span>
                          {d?.k}
                        </span>
                        <b>
                          {d?.v}
                        </b>
                        <i></i>
                      </div>
                      </React.Fragment>
                    ))}
                  </div>
                  <div className="pv-acts">
                    <Link className="btn btn-primary wide" href={'/missions/' + v.cur.mission + '/report'}>
                      {"Open full report →"}
                    </Link>
                    <button className="btn btn-ghost" onClick={v.downloadCur}>
                      {"Download JSON"}
                    </button>
                    <button className="btn btn-ghost" onClick={v.copyLink}>
                      {v.copyLabel}
                    </button>
                  </div>
                </section>
              </div>
            </div>
          </main>
        </div>
      </div>
    );
  }
}

export default View;
