'use client';
/* eslint-disable */
// Generated by scripts/convert-designs.mjs from design/landing-page/SettingsTeam.template.html — edit the design or the patches, then re-run.
import React from 'react';
import Base from './_base';
import { AppRail, TopBar, SettingsNav } from '@/components/chrome';
import { getPillar, setPillar, readJSON, writeJSON, signIn, signOut, saveSession, downloadFile } from '@/lib/store';
import { API_URL, pingApi, inferFile, submitRequest } from '@/lib/api';
import { sessionData } from '@/lib/session';
import './css/SettingsTeam.css';

class View extends Base {
  constructor(props) {
    super(props);
    this.state = {
      pillar: 'energy', rf: 'all', q: '', sel: 'OPS-1', inviteRole: 'Viewer', inviteEmail: '', sent: 0,
      members: [
        { handle: 'ADM-1', ini: 'AD', email: '[ADMIN EMAIL]', role: 'Admin', pillars: ['energy', 'agri', 'rescue'], last: '1 h ago', status: 'Active' },
        { handle: 'OPS-1 · you', id: 'OPS-1', ini: 'RK', email: '[WORK EMAIL]', role: 'Operator', pillars: ['energy', 'agri', 'rescue'], last: 'Now', status: 'Active' },
        { handle: 'PLT-1', ini: 'P1', email: '[PILOT EMAIL]', role: 'Pilot', pillars: ['energy', 'agri'], last: '3 h ago', status: 'Active' },
        { handle: 'PLT-2', ini: 'P2', email: '[PILOT EMAIL]', role: 'Pilot', pillars: ['rescue'], last: 'Yesterday', status: 'Active' },
        { handle: 'ANL-1', ini: 'A1', email: '[ANALYST EMAIL]', role: 'Analyst', pillars: ['agri'], last: '2 days ago', status: 'Active' },
        { handle: 'VWR-1', ini: 'V1', email: '[CLIENT EMAIL]', role: 'Viewer', pillars: ['energy'], last: '—', status: 'Invited' },
      ].map((m) => Object.assign({ id: m.handle }, m)),
    };
  }

  _roles() { return ['Admin', 'Operator', 'Pilot', 'Analyst', 'Viewer']; }

  renderVals() {
    const D = this._data();
    const { pillar, rf, q, sel, inviteRole, members, sent } = this.state;
    const ROLES = this._roles();
    const roleCls = { Admin: 'c-rescue', Operator: 'st-new', Pilot: 'c-agri', Analyst: 'st-assigned', Viewer: 'st-off' };
    const ql = q.trim().toLowerCase();
    const list = members.filter((m) => (rf === 'all' || m.role === rf) && (!ql || (m.handle + m.email + m.role).toLowerCase().indexOf(ql) >= 0));
    const cur0 = members.find((m) => m.id === sel) || members[0];
    const isYou = cur0.id === 'OPS-1';
    const update = (patch) => this.setState({ members: this.state.members.map((m) => (m.id === cur0.id ? Object.assign({}, m, patch) : m)) });
    const PERMS = [
      ['View missions, twins & reports', [1, 1, 1, 1, 1]],
      ['Upload media & run inference', [1, 1, 1, 0, 0]],
      ['Plan missions', [1, 1, 1, 0, 0]],
      ['Assign crews & dispatch teams', [1, 1, 0, 0, 0]],
      ['Control aircraft (when linked)', [1, 0, 1, 0, 0]],
      ['Export reports', [1, 1, 0, 1, 0]],
      ['Manage fleet & sites', [1, 1, 0, 0, 0]],
      ['Manage team, keys & settings', [1, 0, 0, 0, 0]],
    ];
    const ri = ROLES.indexOf(cur0.role);
    return {
      pillars: this._pillarTabs(pillar, (k) => this.setState({ pillar: k })),
      activeCount: members.filter((m) => m.status === 'Active').length,
      invitedCount: members.filter((m) => m.status === 'Invited').length,
      onSearch: (e) => this.setState({ q: (e && e.target && e.target.value) || '' }),
      roleF: [['all', 'All']].concat(ROLES.map((r) => [r, r])).map(([k, name]) => ({ name, cls: rf === k ? 'on' : '', pick: () => this.setState({ rf: k }) })),
      members: list.map((m) => ({
        handle: m.handle, ini: m.ini, email: m.email, role: m.role, roleCls: roleCls[m.role], last: m.last, status: m.status,
        stCls: m.status === 'Active' ? 'st-resolved' : 'st-warn',
        pills: ['energy', 'agri', 'rescue'].map((k) => ({ bg: m.pillars.indexOf(k) >= 0 ? D.P[k].color : 'transparent' })),
        selCls: m.id === cur0.id ? 'sel' : '', pick: () => this.setState({ sel: m.id }),
      })),
      roleCols: ROLES.map((r, i) => ({ name: r, cls: i === ri ? 'on' : '' })),
      perms: PERMS.map(([name, row]) => ({ name, cells: row.map((v, i) => ({ dia: v ? 'sev-ok' : 'dia-off', cls: i === ri ? 'on' : '' })) })),
      cur: { handle: cur0.handle, ini: cur0.ini, email: cur0.email, status: cur0.status, stCls: cur0.status === 'Active' ? 'st-resolved' : 'st-warn', isYou },
      roleOpts: ROLES.map((r) => ({ name: r, cls: cur0.role === r ? 'on' : '', locked: isYou, pick: () => update({ role: r }) })),
      access: ['energy', 'agri', 'rescue'].map((k) => ({
        name: D.P[k].name + ' · ' + D.P[k].long, color: D.P[k].color, cls: cur0.pillars.indexOf(k) >= 0 ? 'on' : '', locked: cur0.role === 'Admin',
        toggle: () => update({ pillars: cur0.pillars.indexOf(k) >= 0 ? cur0.pillars.filter((x) => x !== k) : cur0.pillars.concat(k) }),
      })),
      inviteRoles: ROLES.map((r) => ({ name: r, cls: inviteRole === r ? 'on' : '', pick: () => this.setState({ inviteRole: r }) })),
      onInviteEmail: (e) => this.setState({ inviteEmail: (e && e.target && e.target.value) || '' }),
      inviteLabel: sent ? 'Invite sent · simulated' : 'Send invite',
      sendInvite: () => {
        const n = this.state.sent + 1, id = 'INV-' + n;
        this.setState({
          sent: n, sel: id,
          members: this.state.members.concat({ id, handle: id, ini: 'IN', email: this.state.inviteEmail || '[EMAIL ADDRESS]', role: this.state.inviteRole, pillars: ['energy'], last: '—', status: 'Invited' }),
        });
      },
    };
  }

  componentDidMount() {
    this._syncPillar(); this._alive = true; this._startClock(); }
  componentWillUnmount() { this._alive = false; this._stopClock(); }



  render() {
    const v = this.renderVals();
    return (
      <div className="pg-settings-team ds">
        <div className="app">
          <AppRail active="settings" />
          <TopBar crumbs={["Settings","Team"]} pillars={v.pillars} />
          <main className="main">
            <div className="settings">
              <SettingsNav active="team" />
              <div className="set-main">
                <div className="page-head">
                  <div>
                    <div className="kicker">
                      <i></i>
                      {"Settings · access control"}
                    </div>
                    <h1 className="h1" style={{ marginTop: "10px" }}>
                      {"Team & roles"}
                    </h1>
                  </div>
                  <div className="meta">
                    {v.activeCount}{" active · "}{v.invitedCount}{" invited · seats 4 of 10 used by pilots and operators"}
                  </div>
                </div>
                <div className="set-cols">
                  <div className="scroll stack">
                    <section className="panel">
                      <div className="toolbar">
                        <span className="input">
                          <input type="text" placeholder="Search members" onInput={v.onSearch} />
                        </span>
                        <div className="segs">
                          {(v.roleF || []).map((f, $index) => (
                            <React.Fragment key={$index}>
                            <button className={f?.cls} onClick={f?.pick}>
                              {f?.name}
                            </button>
                            </React.Fragment>
                          ))}
                        </div>
                      </div>
                      <table className="tbl">
                        <thead>
                          <tr>
                            <th>
                              {"Member"}
                            </th>
                            <th>
                              {"Role"}
                            </th>
                            <th>
                              {"Pillars"}
                            </th>
                            <th>
                              {"Last active"}
                            </th>
                            <th>
                              {"Status"}
                            </th>
                          </tr>
                        </thead>
                        <tbody>
                          {(v.members || []).map((m, $index) => (
                            <React.Fragment key={$index}>
                            <tr className={m?.selCls} onClick={m?.pick}>
                              <td>
                                <div className="who">
                                  <span className="ini">
                                    {m?.ini}
                                  </span>
                                  <span>
                                    <b>
                                      {m?.handle}
                                    </b>
                                    <em>
                                      {m?.email}
                                    </em>
                                  </span>
                                </div>
                              </td>
                              <td>
                                <span className={`chip ${m?.roleCls ?? ""}`}>
                                  {m?.role}
                                </span>
                              </td>
                              <td>
                                <span className="pa">
                                  {(m?.pills || []).map((p, $index) => (
                                    <React.Fragment key={$index}>
                                    <i style={{ background: `${p?.bg ?? ""}` }}></i>
                                    </React.Fragment>
                                  ))}
                                </span>
                              </td>
                              <td>
                                {m?.last}
                              </td>
                              <td>
                                <span className={`chip ${m?.stCls ?? ""}`}>
                                  {m?.status}
                                </span>
                              </td>
                            </tr>
                            </React.Fragment>
                          ))}
                        </tbody>
                      </table>
                    </section>
                    <section className="panel">
                      <div className="card-h">
                        <span className="lbl strong">
                          {"Roles & permissions"}
                        </span>
                        <span className="lbl">
                          {"Highlighted column = selected member's role"}
                        </span>
                      </div>
                      <div style={{ padding: "6px 0 8px" }}>
                        <table className="perm">
                          <thead>
                            <tr>
                              <th>
                                {"Permission"}
                              </th>
                              {(v.roleCols || []).map((r, $index) => (
                                <React.Fragment key={$index}>
                                <th className={r?.cls}>
                                  {r?.name}
                                </th>
                                </React.Fragment>
                              ))}
                            </tr>
                          </thead>
                          <tbody>
                            {(v.perms || []).map((p, $index) => (
                              <React.Fragment key={$index}>
                              <tr>
                                <td>
                                  {p?.name}
                                </td>
                                {(p?.cells || []).map((c, $index) => (
                                  <React.Fragment key={$index}>
                                  <td className={c?.cls}>
                                    <i className={`dia ${c?.dia ?? ""}`}></i>
                                  </td>
                                  </React.Fragment>
                                ))}
                              </tr>
                              </React.Fragment>
                            ))}
                          </tbody>
                        </table>
                      </div>
                      <div className="note">
                        {"Aircraft control stays disabled until hardware is linked and the pilot's certificate is on file"}
                      </div>
                    </section>
                  </div>
                  <div className="scroll stack">
                    <section className="panel">
                      <div className="card-h">
                        <div className="who">
                          <span className="ini big-ini">
                            {v.cur?.ini}
                          </span>
                          <span>
                            <b style={{ fontSize: "16px" }}>
                              {v.cur?.handle}
                            </b>
                            <em style={{ fontSize: "12px" }}>
                              {v.cur?.email}
                            </em>
                          </span>
                        </div>
                        <span className={`chip ${v.cur?.stCls ?? ""}`}>
                          {v.cur?.status}
                        </span>
                      </div>
                      <div className="card-b">
                        <span className="lbl">
                          {"Role"}
                        </span>
                        <div className="segs" style={{ marginTop: "8px" }}>
                          {(v.roleOpts || []).map((r, $index) => (
                            <React.Fragment key={$index}>
                            <button className={r?.cls} onClick={r?.pick} disabled={r?.locked}>
                              {r?.name}
                            </button>
                            </React.Fragment>
                          ))}
                        </div>
                      </div>
                      <div className="card-h" style={{ paddingTop: "0" }}>
                        <span className="lbl">
                          {"Pillar access"}
                        </span>
                      </div>
                      {(v.access || []).map((a, $index) => (
                        <React.Fragment key={$index}>
                        <div className="ptog">
                          <i className="dia" style={{ background: `${a?.color ?? ""}` }}></i>
                          <span className="srow-t">
                            {a?.name}
                          </span>
                          <button className={`tgl ${a?.cls ?? ""}`} onClick={a?.toggle} disabled={a?.locked}>
                            <i></i>
                          </button>
                        </div>
                        </React.Fragment>
                      ))}
                      <div className="card-b" style={{ display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: "8px" }}>
                        <button className="btn btn-ghost btn-sm" onClick={() => alert(`Password reset email dispatched to ${v.cur?.name || 'team member'}.`)}>
                          {"Reset password"}
                        </button>
                        <button className="btn btn-danger btn-sm" disabled={v.cur?.isYou}>
                          {"Remove"}
                        </button>
                      </div>
                    </section>
                    <section className="panel">
                      <div className="card-h">
                        <span className="lbl strong">
                          {"Invite a member"}
                        </span>
                        <span className="lbl">
                          {"Expires in 7 days"}
                        </span>
                      </div>
                      <div className="card-b">
                        <label className="field">
                          <span className="lbl">
                            {"Email"}
                          </span>
                          <span className="input">
                            <input type="email" placeholder="[EMAIL ADDRESS]" onInput={v.onInviteEmail} />
                          </span>
                        </label>
                        <div className="field" style={{ marginTop: "12px" }}>
                          <span className="lbl">
                            {"Role"}
                          </span>
                          <div className="segs">
                            {(v.inviteRoles || []).map((r, $index) => (
                              <React.Fragment key={$index}>
                              <button className={r?.cls} onClick={r?.pick}>
                                {r?.name}
                              </button>
                              </React.Fragment>
                            ))}
                          </div>
                        </div>
                        <button className="btn btn-primary" style={{ width: "100%", marginTop: "14px" }} onClick={v.sendInvite}>
                          {v.inviteLabel}
                        </button>
                      </div>
                    </section>
                  </div>
                </div>
              </div>
            </div>
          </main>
        </div>
      </div>
    );
  }
}

export default View;
