'use client';
/* eslint-disable */
// Generated by scripts/convert-designs.mjs from design/landing-page/SettingsProfile.template.html — edit the design or the patches, then re-run.
import React from 'react';
import Base from './_base';
import { AppRail, TopBar, SettingsNav } from '@/components/chrome';
import { getPillar, setPillar, readJSON, writeJSON, signIn, signOut, saveSession, downloadFile } from '@/lib/store';
import { API_URL, pingApi, inferFile, submitRequest } from '@/lib/api';
import { sessionData } from '@/lib/session';
import './css/SettingsProfile.css';

class View extends Base {
  constructor(props) {
    super(props);
    this.state = {
      pillar: 'energy', dirty: false, saved: false, mfa: false, motion: false,
      prefs: { pillar: 'energy', coord: 'dd', units: 'metric', view: '3d' },
      notifs: { crit: [true, true], done: [true, false], fail: [true, true], maint: [true, false], weekly: [false, true] },
    };
    this._motion = false;
    const saved = readJSON('aero.profile', null);
    if (saved) Object.assign(this.state, saved, { dirty: false, saved: false });
  }

  renderVals() {
    const { pillar, dirty, saved, mfa, motion, prefs, notifs } = this.state;
    this._motion = motion;
    const touch = () => { if (!this.state.dirty) this.setState({ dirty: true, saved: false }); };
    const setPref = (k, v) => this.setState({ prefs: Object.assign({}, this.state.prefs, { [k]: v }), dirty: true, saved: false });
    const pref = (key, name, hint, opts) => ({ name, hint, opts: opts.map(([v, label]) => ({ name: label, cls: prefs[key] === v ? 'on' : '', pick: () => setPref(key, v) })) });
    const tog = (k, i) => () => {
      const next = Object.assign({}, this.state.notifs);
      next[k] = next[k].slice();
      next[k][i] = !next[k][i];
      this.setState({ notifs: next, dirty: true, saved: false });
    };
    return {
      pillars: this._pillarTabs(pillar, (k) => this.setState({ pillar: k })),
      dirty, clean: !dirty,
      saveLabel: saved ? 'Saved' : 'Save changes',
      touch,
      save: () => { this.setState({ dirty: false, saved: true }); writeJSON('aero.profile', { prefs: this.state.prefs, notifs: this.state.notifs, mfa: this.state.mfa, motion: this.state.motion }); setPillar(this.state.prefs.pillar); },
      discard: () => this.setState({ dirty: false, saved: false, prefs: { pillar: 'energy', coord: 'dd', units: 'metric', view: '3d' } }),
      prefs: [
        pref('pillar', 'Default pillar', 'Opens the command center on this pillar', [['energy', 'Energy'], ['agri', 'Agri'], ['rescue', 'Rescue']]),
        pref('coord', 'Coordinate format', prefs.coord === 'dd' ? 'e.g. 22.30010° N 70.80010° E' : 'e.g. 22°18\'00.4" N 70°48\'00.4" E', [['dd', 'Decimal'], ['dms', 'DMS']]),
        pref('units', 'Units', 'Altitude, distance and area', [['metric', 'Metric'], ['imperial', 'Imperial']]),
        pref('view', 'Default twin view', 'Camera used when a mission opens', [['3d', '3D'], ['top', 'Top']]),
      ],
      motionCls: motion ? 'on' : '',
      toggleMotion: () => this.setState({ motion: !this.state.motion, dirty: true, saved: false }),
      notifs: [
        ['crit', 'Critical detection', 'Hotspots, disease zones, persons found'],
        ['done', 'Mission processed', 'Inference and geo-mapping finished'],
        ['fail', 'Processing failed', 'Upload, telemetry or inference error'],
        ['maint', 'Aircraft maintenance due', 'Motor hours or service date reached'],
        ['weekly', 'Weekly summary', 'Digest of all pillars every Monday'],
      ].map(([k, name, hint]) => ({ name, hint, app: notifs[k][0] ? 'on' : '', mail: notifs[k][1] ? 'on' : '', tApp: tog(k, 0), tMail: tog(k, 1) })),
      mfaChip: mfa ? 'st-resolved' : 'st-warn',
      mfaLabel: mfa ? '2FA on' : '2FA off',
      mfaHint: mfa ? 'Authenticator app · recovery codes stored' : 'Recommended for operators who dispatch crews',
      mfaBtn: mfa ? 'Turn off' : 'Enable',
      mfaBtnCls: mfa ? 'btn-ghost' : 'btn-primary',
      toggleMfa: () => this.setState({ mfa: !this.state.mfa }),
      sessions: [
        ['This browser · [BROWSER / OS]', 'Rajkot, IN · approx. from IP', 'Now', 'st-resolved', 'sev-ok'],
        ['[DEVICE NAME]', '[CITY] · [BROWSER]', '2 days ago', 'st-off', 'dia-off'],
      ].map(([device, where, when, cls, dia]) => ({ device, where, when, cls, dia })),
    };
  }

  componentDidMount() {
    this._syncPillar(); this._alive = true; this._startClock(); this._boot(0); }

  componentWillUnmount() {
    this._alive = false;
    this._stopClock();
    if (this._raf) cancelAnimationFrame(this._raf);
  }

  _boot(tries) {
    if (!this._alive) return;
    const canvas = document.querySelector('[data-gl="badge"]');
    if (!canvas) { if (tries < 120) requestAnimationFrame(() => this._boot(tries + 1)); return; }
    this._loop([this._badgeScene(this._engine(), canvas)]);
  }

  // Identity medallion: counter-rotating hex rings and three pillar satellites.
  _badgeScene(K, canvas) {
    const R = K.renderer(canvas, [0.016, 0.043, 0.11]);
    if (!R) return null;
    const { Batch, COL, a } = K;
    const self = this;
    const D = this._data();
    const hexCol = [[0.36, 0.88, 1], [0.61, 0.88, 0.36], [1, 0.48, 0.3]];
    let clock = 0;
    return {
      frame(t, dt) {
        const asp = R.resize();
        clock += self._motion ? 0 : dt;
        const T = clock;
        const eye = [0, 6, 46];
        const M = K.camera(asp, eye, [0, 0, 0], 0.6);
        R.begin(M, eye, 30, 120);
        const ln = new Batch(), pts = new Batch();
        const hex = (r, rot, tilt, col, al, z) => {
          for (let k = 0; k < 6; k++) {
            const a1 = (k / 6) * Math.PI * 2 + rot, a2 = ((k + 1) / 6) * Math.PI * 2 + rot;
            const p = [Math.cos(a1) * r, Math.sin(a1) * r * Math.cos(tilt), z + Math.sin(a1) * r * Math.sin(tilt)];
            const q = [Math.cos(a2) * r, Math.sin(a2) * r * Math.cos(tilt), z + Math.sin(a2) * r * Math.sin(tilt)];
            ln.line(p[0], p[1], p[2], q[0], q[1], q[2], a(col, al));
          }
        };
        hex(13, T * 0.3, 0, COL.cyan, 0.9, 0);
        hex(15.5, -T * 0.2, 0, COL.blue, 0.5, -1);
        hex(18, T * 0.12, 0, COL.cyan, 0.25, -2);
        for (let k = 0; k < 36; k++) {
          const an = (k / 36) * Math.PI * 2 + T * 0.1, r1 = k % 6 === 0 ? 20 : 20.8;
          ln.line(Math.cos(an) * r1, Math.sin(an) * r1, -2, Math.cos(an) * 21.6, Math.sin(an) * 21.6, -2, a(COL.cyan, k % 6 === 0 ? 0.7 : 0.25));
        }
        ['energy', 'agri', 'rescue'].forEach((key, i) => {
          const an = T * 0.5 + (i * Math.PI * 2) / 3, c = hexCol[i];
          const x = Math.cos(an) * 24, y = Math.sin(an) * 9, z = Math.sin(an) * 6;
          pts.v(x, y, z, [c[0], c[1], c[2], 1]);
          for (let j = 1; j < 14; j++) {
            const b = an - j * 0.05;
            ln.line(Math.cos(b) * 24, Math.sin(b) * 9, Math.sin(b) * 6, Math.cos(b - 0.05) * 24, Math.sin(b - 0.05) * 9, Math.sin(b - 0.05) * 6, [c[0], c[1], c[2], 0.6 * (1 - j / 14)]);
          }
        });
        R.draw(ln, 'lines', 'add');
        R.draw(pts, 'points', 'add', 60);
      },
    };
  }



  render() {
    const v = this.renderVals();
    return (
      <div className="pg-settings-profile ds">
        <div className="app">
          <AppRail active="settings" />
          <TopBar crumbs={["Settings","Profile"]} pillars={v.pillars} />
          <main className="main">
            <div className="settings">
              <SettingsNav active="profile" />
              <div className="set-main">
                <div className="page-head">
                  <div>
                    <div className="kicker">
                      <i></i>
                      {"Settings · personal"}
                    </div>
                    <h1 className="h1" style={{ marginTop: "10px" }}>
                      {"Profile"}
                    </h1>
                  </div>
                  <div className="acts">
                    {v.dirty ? (
                      <>
                      <span className="dirty">
                        <i className="dia sev-warn"></i>
                        {"Unsaved changes"}
                      </span>
                      </>
                    ) : null}
                    <button className="btn btn-ghost" onClick={v.discard} disabled={v.clean}>
                      {"Discard"}
                    </button>
                    <button className="btn btn-primary" onClick={v.save} disabled={v.clean}>
                      {v.saveLabel}
                    </button>
                  </div>
                </div>
                <div className="set-cols">
                  <div className="scroll stack">
                    <section className="panel">
                      <div className="card-h">
                        <span className="lbl strong">
                          {"Personal details"}
                        </span>
                      </div>
                      <div className="card-b">
                        <div className="fgrid">
                          <label className="field">
                            <span className="lbl">
                              {"Display name"}
                            </span>
                            <span className="input">
                              <input type="text" placeholder="[FULL NAME]" onInput={v.touch} />
                            </span>
                          </label>
                          <label className="field">
                            <span className="lbl">
                              {"Callsign"}
                            </span>
                            <span className="input">
                              <input type="text" defaultValue="OPS-1" onInput={v.touch} />
                            </span>
                          </label>
                          <label className="field">
                            <span className="lbl">
                              {"Work email"}
                            </span>
                            <span className="input">
                              <input type="email" placeholder="[WORK EMAIL]" onInput={v.touch} />
                            </span>
                          </label>
                          <div className="field">
                            <span className="lbl">
                              {"Role"}
                            </span>
                            <span className="ro">
                              {"Operator · set by your admin"}
                            </span>
                          </div>
                          <div className="field">
                            <span className="lbl">
                              {"Timezone"}
                            </span>
                            <span className="ro">
                              {"Asia/Kolkata · IST (UTC+05:30)"}
                            </span>
                          </div>
                          <div className="field">
                            <span className="lbl">
                              {"Language"}
                            </span>
                            <span className="ro">
                              {"English"}
                            </span>
                          </div>
                        </div>
                      </div>
                    </section>
                    <section className="panel">
                      <div className="card-h">
                        <span className="lbl strong">
                          {"Preferences"}
                        </span>
                      </div>
                      {(v.prefs || []).map((p, $index) => (
                        <React.Fragment key={$index}>
                        <div className="srow">
                          <div>
                            <div className="srow-t">
                              {p?.name}
                            </div>
                            <div className="srow-s">
                              {p?.hint}
                            </div>
                          </div>
                          <div className="segs">
                            {(p?.opts || []).map((o, $index) => (
                              <React.Fragment key={$index}>
                              <button className={o?.cls} onClick={o?.pick}>
                                {o?.name}
                              </button>
                              </React.Fragment>
                            ))}
                          </div>
                        </div>
                        </React.Fragment>
                      ))}
                      <div className="srow">
                        <div>
                          <div className="srow-t">
                            {"Reduce motion"}
                          </div>
                          <div className="srow-s">
                            {"Pause auto-orbiting cameras and pulsing markers across 3D views"}
                          </div>
                        </div>
                        <button className={`tgl ${v.motionCls ?? ""}`} onClick={v.toggleMotion}>
                          <i></i>
                        </button>
                      </div>
                    </section>
                    <section className="panel">
                      <div className="card-h">
                        <span className="lbl strong">
                          {"Notifications"}
                        </span>
                        <span className="lbl">
                          {"SMS needs a gateway · not configured"}
                        </span>
                      </div>
                      <div className="card-b" style={{ padding: "8px 0 6px" }}>
                        <table className="matrix">
                          <thead>
                            <tr>
                              <th>
                                {"Event"}
                              </th>
                              <th>
                                {"In-app"}
                              </th>
                              <th>
                                {"Email"}
                              </th>
                              <th>
                                {"SMS"}
                              </th>
                            </tr>
                          </thead>
                          <tbody>
                            {(v.notifs || []).map((n, $index) => (
                              <React.Fragment key={$index}>
                              <tr>
                                <td>
                                  {n?.name}
                                  <em>
                                    {n?.hint}
                                  </em>
                                </td>
                                <td>
                                  <button className={`tgl ${n?.app ?? ""}`} onClick={n?.tApp}>
                                    <i></i>
                                  </button>
                                </td>
                                <td>
                                  <button className={`tgl ${n?.mail ?? ""}`} onClick={n?.tMail}>
                                    <i></i>
                                  </button>
                                </td>
                                <td>
                                  <button className="tgl" disabled={true}>
                                    <i></i>
                                  </button>
                                </td>
                              </tr>
                              </React.Fragment>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    </section>
                  </div>
                  <div className="scroll stack">
                    <section className="panel">
                      <div className="ident">
                        <canvas className="gl" data-gl="badge"></canvas>
                        <div className="ident-c">
                          <b>
                            {"RK"}
                          </b>
                          <span>
                            {"Operator · OPS-1"}
                          </span>
                        </div>
                      </div>
                      <div className="card-b">
                        <div className="kvg c3">
                          <div>
                            <span className="lbl">
                              {"Pillar access"}
                            </span>
                            <b>
                              {"All three"}
                            </b>
                          </div>
                          <div>
                            <span className="lbl">
                              {"Member since"}
                            </span>
                            <b>
                              {"[DATE]"}
                            </b>
                          </div>
                          <div>
                            <span className="lbl">
                              {"Last sign-in"}
                            </span>
                            <b>
                              {"Today · demo"}
                            </b>
                          </div>
                        </div>
                      </div>
                    </section>
                    <section className="panel">
                      <div className="card-h">
                        <span className="lbl strong">
                          {"Security"}
                        </span>
                        <span className={`chip ${v.mfaChip ?? ""}`}>
                          {v.mfaLabel}
                        </span>
                      </div>
                      <div className="srow" style={{ borderTop: "0", marginTop: "6px" }}>
                        <div>
                          <div className="srow-t">
                            {"Password"}
                          </div>
                          <div className="srow-s">
                            {"Last changed [DATE]"}
                          </div>
                        </div>
                        <button className="btn btn-ghost btn-sm" onClick={() => alert('Password Reset: A secure reset link has been dispatched to your email address.')}>
                          {"Change"}
                        </button>
                      </div>
                      <div className="srow">
                        <div>
                          <div className="srow-t">
                            {"Two-factor authentication"}
                          </div>
                          <div className="srow-s">
                            {v.mfaHint}
                          </div>
                        </div>
                        <button className={`btn ${v.mfaBtnCls ?? ""} btn-sm`} onClick={v.toggleMfa}>
                          {v.mfaBtn}
                        </button>
                      </div>
                      <div className="card-h" style={{ paddingTop: "12px" }}>
                        <span className="lbl">
                          {"Active sessions"}
                        </span>
                      </div>
                      {(v.sessions || []).map((s, $index) => (
                        <React.Fragment key={$index}>
                        <div className="li sess">
                          <i className={`dia ${s?.dia ?? ""}`}></i>
                          <span style={{ minWidth: "0" }}>
                            <span className="li-t" style={{ fontSize: "13.5px" }}>
                              {s?.device}
                            </span>
                            <span className="li-s">
                              {s?.where}
                            </span>
                          </span>
                          <span className={`chip ${s?.cls ?? ""}`}>
                            {s?.when}
                          </span>
                        </div>
                        </React.Fragment>
                      ))}
                      <div className="card-b">
                        <button className="btn btn-danger btn-sm" style={{ width: "100%" }} onClick={() => alert('Security update: All other active browser sessions have been invalidated.')}>
                          {"Sign out other sessions"}
                        </button>
                      </div>
                    </section>
                  </div>
                </div>
              </div>
            </div>
          </main>
        </div>
      </div>
    );
  }
}

export default View;
