'use client';
/* eslint-disable */
// Generated by scripts/convert-designs.mjs from design/landing-page/SettingsApiKeys.template.html — edit the design or the patches, then re-run.
import React from 'react';
import Base from './_base';
import { AppRail, TopBar, SettingsNav } from '@/components/chrome';
import { getPillar, setPillar, readJSON, writeJSON, signIn, signOut, saveSession, downloadFile } from '@/lib/store';
import { API_URL, pingApi, inferFile, submitRequest } from '@/lib/api';
import { sessionData } from '@/lib/session';
import './css/SettingsApiKeys.css';

class View extends Base {
  constructor(props) {
    super(props);
    this.state = {
      pillar: 'energy', tip: null, showCreate: false, created: false, newName: '', newScopes: ['infer:write'], expiry: '90d',
      revoked: [], hooksOn: ['critical'],
      keys: [
        { id: 'k1', name: 'Field upload station', mask: 'aero_demo_4f2a…••••', scopes: ['infer:write', 'missions:read'], last: '14 Sep 2026' },
        { id: 'k2', name: 'Reporting dashboard', mask: 'aero_demo_9c11…••••', scopes: ['reports:read'], last: '12 Sep 2026' },
        { id: 'k3', name: 'Telemetry bridge (test)', mask: 'aero_demo_07be…••••', scopes: ['telemetry:write'], last: 'Never' },
      ],
    };
  }

  renderVals() {
    const { pillar, tip, showCreate, created, newScopes, expiry, revoked, hooksOn, keys } = this.state;
    const counts = [120, 184, 96, 210, 260, 140, 60, 72, 310, 280, 344, 298, 356, 402];
    const max = 450, PX = 34, PW = 432, slot = PW / counts.length, py = (v) => 124 - (v / max) * 110;
    const SC = ['infer:write', 'missions:read', 'reports:read', 'telemetry:write'];
    return {
      pillars: this._pillarTabs(pillar, (k) => this.setState({ pillar: k })),
      keys: keys.map((k) => ({
        name: k.name, mask: k.mask, last: k.last, scopes: k.scopes.map((name) => ({ name })),
        status: revoked.indexOf(k.id) >= 0 ? 'Revoked' : 'Active', stCls: revoked.indexOf(k.id) >= 0 ? 'st-off' : 'st-resolved',
        revoked: revoked.indexOf(k.id) >= 0, revoke: () => this.setState({ revoked: this.state.revoked.concat(k.id) }),
      })),
      codeLines: [
        ['k4', '# Request'],
        ['k1', 'curl -X POST http://[API HOST]/api/v1/infer/energy \\'],
        ['k1', '     -F "file=@solar_01.jpg"'],
        ['k4', '# Response (shape from backend/main.py)'],
        ['k4', '{'],
        ['k2', '  "pillar": "energy",'],
        ['k2', '  "filename": "solar_01.jpg",'],
        ['k3', '  "telemetry": { "lat": 22.3001, "lng": 70.8001, "alt": 45.0, "heading": 90.0 },'],
        ['k3', '  "detections": [ { "class": "crack", "confidence": 0.91, "bbox_xyxy": [412, 228, 538, 341] } ],'],
        ['k3', '  "inference_time_ms": 38.4'],
        ['k4', '}'],
      ].map(([c, t]) => ({ c, t })),
      hooks: [
        ['critical', '[WEBHOOK URL]/aerolytics/critical', ['detection.critical']],
        ['reports', '[WEBHOOK URL]/aerolytics/reports', ['mission.completed', 'report.ready']],
      ].map(([key, url, events]) => ({
        url, events: events.map((name) => ({ name })), cls: hooksOn.indexOf(key) >= 0 ? 'on' : '',
        toggle: () => this.setState({ hooksOn: hooksOn.indexOf(key) >= 0 ? hooksOn.filter((x) => x !== key) : hooksOn.concat(key) }),
      })),
      usage: {
        grid: [0, 200, 400].map((v) => ({ y: py(v).toFixed(1), ty: (py(v) + 3).toFixed(1), label: String(v) })),
        bars: counts.map((v, i) => {
          const x = PX + slot * i + (slot - 16) / 2, on = tip && tip.i === i;
          return {
            x: x.toFixed(1), y: py(v).toFixed(1), h: (124 - py(v)).toFixed(1), hx: (PX + slot * i).toFixed(1), hw: slot.toFixed(1),
            hoverFill: on ? 'rgba(120,170,255,.1)' : 'transparent',
            hover: () => this.setState({ tip: { i, left: (14 + x + 8) + 'px', top: (8 + py(v)) + 'px', title: String(i + 1).padStart(2, '0') + ' Sep 2026', v } }),
          };
        }),
      },
      hasTip: !!tip,
      tip: tip || { left: '0px', top: '0px', title: '', v: '' },
      clearTip: () => this.setState({ tip: null }),
      ints: [
        ['WebSocket telemetry', 'Demo stream', 'st-warn', 'Streams pose and events to Live ops. Demo stream only.', 'View stream', false],
        ['MQTT gateway', 'Planned', 'st-off', 'Real aircraft telemetry via broker topics.', 'Configure', true],
        ['Email / SMTP', 'Not connected', 'st-off', 'Alert and scheduled report delivery.', 'Connect', false],
        ['PostGIS', 'Planned', 'st-off', 'Spatial store for sites, missions and detections.', 'Configure', true],
        ['Object storage', 'Planned', 'st-off', 'Frames, crops and annotated imagery.', 'Configure', true],
        ['Roboflow datasets', 'Linked in data.yaml', 'st-resolved', 'Training data sources for all three models.', 'View models', false],
      ].map(([name, status, cls, desc, action, planned]) => ({ name, status, cls, desc, action, planned })),
      showCreate, created, notCreated: !created,
      modalTitle: created ? 'Key created' : 'Create API key',
      openCreate: () => this.setState({ showCreate: true, created: false }),
      closeCreate: () => this.setState({ showCreate: false, created: false }),
      onName: (e) => this.setState({ newName: (e && e.target && e.target.value) || '' }),
      scopeOpts: SC.map((s) => ({ name: s, cls: newScopes.indexOf(s) >= 0 ? 'on' : '', toggle: () => this.setState({ newScopes: newScopes.indexOf(s) >= 0 ? newScopes.filter((x) => x !== s) : newScopes.concat(s) }) })),
      expiry: [['30d', '30 days'], ['90d', '90 days'], ['never', 'No expiry']].map(([k, name]) => ({ name, cls: expiry === k ? 'on' : '', pick: () => this.setState({ expiry: k }) })),
      newKey: 'aero_demo_[GENERATED ON SERVER]',
      create: () => this.setState({
        created: true,
        keys: this.state.keys.concat({ id: 'k' + (this.state.keys.length + 1), name: this.state.newName || 'Untitled key', mask: 'aero_demo_…••••', scopes: this.state.newScopes.length ? this.state.newScopes : ['missions:read'], last: 'Never' }),
      }),
    };
  }

  componentDidMount() {
    this._syncPillar(); this._alive = true; this._startClock(); }
  componentWillUnmount() { this._alive = false; this._stopClock(); }



  render() {
    const v = this.renderVals();
    return (
      <div className="pg-settings-api-keys ds">
        <div className="app">
          <AppRail active="settings" />
          <TopBar crumbs={["Settings","API keys"]} pillars={v.pillars} />
          <main className="main">
            <div className="settings">
              <SettingsNav active="api-keys" />
              <div className="set-main">
                <div className="page-head">
                  <div>
                    <div className="kicker">
                      <i></i>
                      {"Settings · developer"}
                    </div>
                    <h1 className="h1" style={{ marginTop: "10px" }}>
                      {"API keys & integrations"}
                    </h1>
                  </div>
                  <div className="acts">
                    <button className="btn btn-primary" onClick={v.openCreate}>
                      {"+ Create API key"}
                    </button>
                  </div>
                </div>
                <div className="set-cols">
                  <div className="scroll stack">
                    <section className="panel">
                      <div className="card-h">
                        <span className="lbl strong">
                          {"API keys"}
                        </span>
                        <span className="badge b-sim">
                          {"Sample keys · not valid"}
                        </span>
                      </div>
                      <div style={{ marginTop: "10px" }}>
                        <table className="tbl">
                          <thead>
                            <tr>
                              <th>
                                {"Name"}
                              </th>
                              <th>
                                {"Key"}
                              </th>
                              <th>
                                {"Scopes"}
                              </th>
                              <th>
                                {"Last used"}
                              </th>
                              <th>
                                {"Status"}
                              </th>
                              <th></th>
                            </tr>
                          </thead>
                          <tbody>
                            {(v.keys || []).map((k, $index) => (
                              <React.Fragment key={$index}>
                              <tr>
                                <td style={{ color: "#fff" }}>
                                  {k?.name}
                                </td>
                                <td>
                                  <span className="key">
                                    {k?.mask}
                                  </span>
                                </td>
                                <td>
                                  <span className="scopes">
                                    {(k?.scopes || []).map((s, $index) => (
                                      <React.Fragment key={$index}>
                                      <span className="chip">
                                        {s?.name}
                                      </span>
                                      </React.Fragment>
                                    ))}
                                  </span>
                                </td>
                                <td>
                                  {k?.last}
                                </td>
                                <td>
                                  <span className={`chip ${k?.stCls ?? ""}`}>
                                    {k?.status}
                                  </span>
                                </td>
                                <td>
                                  <button className="btn btn-danger btn-sm" onClick={k?.revoke} disabled={k?.revoked}>
                                    {"Revoke"}
                                  </button>
                                </td>
                              </tr>
                              </React.Fragment>
                            ))}
                          </tbody>
                        </table>
                      </div>
                      <div className="warnbox" style={{ margin: "12px 18px 16px" }}>
                        <i className="dia sev-warn"></i>
                        <span>
                          {"The current backend (backend/main.py) does not check API keys yet. Key enforcement is planned before any public endpoint goes live."}
                        </span>
                      </div>
                    </section>
                    <section className="panel">
                      <div className="card-h">
                        <span className="lbl strong">
                          {"Endpoint reference"}
                        </span>
                        <span className="chip st-resolved">
                          {"Implemented"}
                        </span>
                      </div>
                      <p className="card-p" style={{ padding: "0 18px 10px" }}>
                        {"Runs the pillar's YOLO model on one uploaded frame and returns detections with telemetry."}
                      </p>
                      <div className="code">
                        {(v.codeLines || []).map((l, $index) => (
                          <React.Fragment key={$index}>
                          <div>
                            <span className={l?.c}>
                              {l?.t}
                            </span>
                          </div>
                          </React.Fragment>
                        ))}
                      </div>
                    </section>
                    <section className="panel">
                      <div className="card-h">
                        <span className="lbl strong">
                          {"Webhooks"}
                        </span>
                        <button className="btn btn-ghost btn-sm" onClick={() => alert('Webhook Registration: Enter endpoint URL (e.g., https://api.yourdomain.com/webhooks/drone-telemetry)')}>
                          {"+ Add endpoint"}
                        </button>
                      </div>
                      <div style={{ marginTop: "10px" }}>
                        {(v.hooks || []).map((h, $index) => (
                          <React.Fragment key={$index}>
                          <div className="li wh">
                            <span style={{ minWidth: "0" }}>
                              <span className="li-t" style={{ fontSize: "13.5px", fontStyle: "normal", fontFamily: "'IBM Plex Mono', monospace", textTransform: "none" }}>
                                {h?.url}
                              </span>
                              <span className="scopes" style={{ marginTop: "6px" }}>
                                {(h?.events || []).map((e, $index) => (
                                  <React.Fragment key={$index}>
                                  <span className="chip">
                                    {e?.name}
                                  </span>
                                  </React.Fragment>
                                ))}
                              </span>
                            </span>
                            <span className="chip st-warn">
                              {"Not verified"}
                            </span>
                            <button className={`tgl ${h?.cls ?? ""}`} onClick={h?.toggle}>
                              <i></i>
                            </button>
                          </div>
                          </React.Fragment>
                        ))}
                      </div>
                    </section>
                  </div>
                  <div className="scroll stack">
                    <section className="panel">
                      <div className="card-h">
                        <span className="lbl strong">
                          {"API requests · last 14 days"}
                        </span>
                        <span className="badge b-sim">
                          {"Sample"}
                        </span>
                      </div>
                      <div className="chart">
                        <svg width="470" height="150" viewBox="0 0 470 150">
                          {(v.usage?.grid || []).map((g, $index) => (
                            <React.Fragment key={$index}>
                            <line x1="34" x2="466" y1={g?.y} y2={g?.y} stroke="rgba(120,170,255,.1)"></line>
                            <text className="ax" x="28" y={g?.ty} textAnchor="end">
                              {g?.label}
                            </text>
                            </React.Fragment>
                          ))}
                          <line x1="34" x2="466" y1="124" y2="124" stroke="rgba(120,170,255,.35)"></line>
                          {(v.usage?.bars || []).map((b, $index) => (
                            <React.Fragment key={$index}>
                            <g onMouseEnter={b?.hover} onMouseLeave={v.clearTip}>
                              <rect x={b?.hx} y="8" width={b?.hw} height="116" fill={b?.hoverFill}></rect>
                              <rect x={b?.x} y={b?.y} width="16" height={b?.h} fill="#3FB3E0"></rect>
                            </g>
                            </React.Fragment>
                          ))}
                          <text className="ax" x="34" y="142">
                            {"01 Sep"}
                          </text>
                          <text className="ax" x="466" y="142" textAnchor="end">
                            {"14 Sep"}
                          </text>
                        </svg>
                        {v.hasTip ? (
                          <>
                          <div className="tip" style={{ left: `${v.tip?.left ?? ""}`, top: `${v.tip?.top ?? ""}` }}>
                            <b>
                              {v.tip?.title}
                            </b>
                            {v.tip?.v}{" requests"}
                          </div>
                          </>
                        ) : null}
                      </div>
                    </section>
                    <section className="panel">
                      <div className="card-h">
                        <span className="lbl strong">
                          {"Integrations"}
                        </span>
                      </div>
                      <div className="ints">
                        {(v.ints || []).map((i, $index) => (
                          <React.Fragment key={$index}>
                          <div className="int">
                            <div className="int-top">
                              <b>
                                {i?.name}
                              </b>
                              <span className={`chip ${i?.cls ?? ""}`}>
                                {i?.status}
                              </span>
                            </div>
                            <span className="d">
                              {i?.desc}
                            </span>
                            <button className="btn btn-ghost btn-sm" disabled={i?.planned} style={{ marginTop: "4px" }}>
                              {i?.action}
                            </button>
                          </div>
                          </React.Fragment>
                        ))}
                      </div>
                    </section>
                  </div>
                </div>
              </div>
            </div>
            {v.showCreate ? (
              <>
              <div className="modal-bg">
                <section className="panel modal">
                  <div className="ph">
                    <span className="lbl strong">
                      {v.modalTitle}
                    </span>
                    <button className="btn btn-ghost btn-sm" onClick={v.closeCreate}>
                      {"Close"}
                    </button>
                  </div>
                  {v.notCreated ? (
                    <>
                    <div className="card-b">
                      <label className="field">
                        <span className="lbl">
                          {"Key name"}
                        </span>
                        <span className="input">
                          <input type="text" placeholder="e.g. Field upload station" onInput={v.onName} />
                        </span>
                      </label>
                      <div className="field" style={{ marginTop: "12px" }}>
                        <span className="lbl">
                          {"Scopes"}
                        </span>
                        <div className="scope-grid">
                          {(v.scopeOpts || []).map((s, $index) => (
                            <React.Fragment key={$index}>
                            <button className={`ck ${s?.cls ?? ""}`} onClick={s?.toggle}>
                              <i></i>
                              {s?.name}
                            </button>
                            </React.Fragment>
                          ))}
                        </div>
                      </div>
                      <div className="field" style={{ marginTop: "12px" }}>
                        <span className="lbl">
                          {"Expires"}
                        </span>
                        <div className="segs">
                          {(v.expiry || []).map((x, $index) => (
                            <React.Fragment key={$index}>
                            <button className={x?.cls} onClick={x?.pick}>
                              {x?.name}
                            </button>
                            </React.Fragment>
                          ))}
                        </div>
                      </div>
                      <button className="btn btn-primary" style={{ width: "100%", marginTop: "16px" }} onClick={v.create}>
                        {"Create key"}
                      </button>
                    </div>
                    </>
                  ) : null}
                  {v.created ? (
                    <>
                    <div className="card-b">
                      <div className="warnbox">
                        <i className="dia sev-warn"></i>
                        <span>
                          {"Copy this key now. It will not be shown again. This preview generates a placeholder, not a working key."}
                        </span>
                      </div>
                      <div className="newkey">
                        <span>
                          {v.newKey}
                        </span>
                        <button className="btn btn-ghost btn-sm" onClick={() => { navigator.clipboard?.writeText?.(v.newKey || ''); alert('API Key copied to clipboard!'); }}>
                          {"Copy"}
                        </button>
                      </div>
                      <button className="btn btn-go" style={{ width: "100%", marginTop: "14px" }} onClick={v.closeCreate}>
                        {"Done"}
                      </button>
                    </div>
                    </>
                  ) : null}
                </section>
              </div>
              </>
            ) : null}
          </main>
        </div>
      </div>
    );
  }
}

export default View;
