'use client';
/* eslint-disable */
// Generated by scripts/convert-designs.mjs from design/landing-page/SettingsOrganization.template.html — edit the design or the patches, then re-run.
import React from 'react';
import Base from './_base';
import { AppRail, TopBar, SettingsNav } from '@/components/chrome';
import { getPillar, setPillar, readJSON, writeJSON, signIn, signOut, saveSession, downloadFile } from '@/lib/store';
import { API_URL, pingApi, inferFile, submitRequest } from '@/lib/api';
import { sessionData } from '@/lib/session';
import './css/SettingsOrganization.css';

class View extends Base {
  constructor(props) {
    super(props);
    this.state = { pillar: 'energy', dirty: false, saved: false, enabled: { energy: true, agri: true, rescue: true }, ret: { frames: '1y', dets: '3y', reports: '3y' } };
    this._selSite = 'rsp';
    this._onAoPick = (key) => { this._selSite = key; this.setState({ sel: key }); };
    const saved = readJSON('aero.org', null);
    if (saved) Object.assign(this.state, saved);
  }

  renderVals() {
    const D = this._data();
    const { pillar, dirty, saved, enabled, ret } = this.state;
    const mark = () => ({ dirty: true, saved: false });
    return {
      pillars: this._pillarTabs(pillar, (k) => { const s = D.sites.find((x) => x.pillar === k); if (s) this._selSite = s.key; this.setState({ pillar: k }); }),
      dirty, clean: !dirty, saveLabel: saved ? 'Saved' : 'Save changes',
      touch: () => { if (!this.state.dirty) this.setState(mark()); },
      save: () => { this.setState({ dirty: false, saved: true }); writeJSON('aero.org', { enabled: this.state.enabled, ret: this.state.ret }); },
      pillarRows: ['energy', 'agri', 'rescue'].map((k) => ({
        name: D.P[k].name, long: D.P[k].long, color: D.P[k].color, model: D.P[k].model,
        sites: D.sites.filter((s) => s.pillar === k).length,
        cls: enabled[k] ? 'on' : '',
        toggle: () => this.setState(Object.assign({ enabled: Object.assign({}, this.state.enabled, { [k]: !this.state.enabled[k] }) }, mark())),
      })),
      retention: [
        ['frames', 'Raw frames', 'Original imagery and video', [['90d', '90 d'], ['1y', '1 yr'], ['3y', '3 yr']]],
        ['dets', 'Detections & telemetry', 'Normalized results and positions', [['1y', '1 yr'], ['3y', '3 yr'], ['forever', 'Keep']]],
        ['reports', 'Reports', 'Generated PDF and JSON', [['1y', '1 yr'], ['3y', '3 yr'], ['forever', 'Keep']]],
      ].map(([k, name, hint, opts]) => ({
        name, hint,
        opts: opts.map(([v, label]) => ({ name: label, cls: ret[k] === v ? 'on' : '', pick: () => this.setState(Object.assign({ ret: Object.assign({}, this.state.ret, { [k]: v }) }, mark())) })),
      })),
      reg: [['Operator permit', '[OPERATOR PERMIT NUMBER]'], ['Aircraft UINs', '[UIN LIST] · 3 registered aircraft'], ['Remote pilots', '[REMOTE PILOT CERTIFICATES]'], ['Airspace approvals', '[APPROVAL REFERENCES]']].map(([k, v]) => ({ k, v })),
    };
  }

  componentDidMount() {
    this._syncPillar(); this._alive = true; this._startClock(); this._boot(0); }

  componentWillUnmount() {
    this._alive = false;
    this._stopClock();
    if (this._raf) cancelAnimationFrame(this._raf);
    if (this._ao) this._ao.destroy();
  }

  _boot(tries) {
    if (!this._alive) return;
    const canvas = document.querySelector('[data-gl="ao"]');
    if (!canvas) { if (tries < 120) requestAnimationFrame(() => this._boot(tries + 1)); return; }
    this._ao = this._aoScene(this._engine(), canvas, document.querySelector('[data-gl-labels="ao"]'));
    this._loop([this._ao]);
  }



  render() {
    const v = this.renderVals();
    return (
      <div className="pg-settings-organization ds">
        <div className="app">
          <AppRail active="settings" />
          <TopBar crumbs={["Settings","Organization"]} pillars={v.pillars} />
          <main className="main">
            <div className="settings">
              <SettingsNav active="organization" />
              <div className="set-main">
                <div className="page-head">
                  <div>
                    <div className="kicker">
                      <i></i>
                      {"Settings · organization"}
                    </div>
                    <h1 className="h1" style={{ marginTop: "10px" }}>
                      {"Organization"}
                    </h1>
                  </div>
                  <div className="meta">
                    {"Admin access required to change these settings"}
                  </div>
                  <div className="acts">
                    {v.dirty ? (
                      <>
                      <span className="dirty">
                        <i className="dia sev-warn"></i>
                        {"Unsaved changes"}
                      </span>
                      </>
                    ) : null}
                    <button className="btn btn-primary" onClick={v.save} disabled={v.clean}>
                      {v.saveLabel}
                    </button>
                  </div>
                </div>
                <div className="set-cols">
                  <div className="scroll stack">
                    <section className="panel">
                      <div className="card-h">
                        <span className="lbl strong">
                          {"Organization details"}
                        </span>
                        <span className="chip st-new">
                          {"Pilot · golden demo"}
                        </span>
                      </div>
                      <div className="card-b">
                        <div className="fgrid">
                          <label className="field full">
                            <span className="lbl">
                              {"Legal name"}
                            </span>
                            <span className="input">
                              <input type="text" placeholder="[ORGANIZATION NAME]" onInput={v.touch} />
                            </span>
                          </label>
                          <label className="field">
                            <span className="lbl">
                              {"Short name"}
                            </span>
                            <span className="input">
                              <input type="text" placeholder="[SHORT NAME]" onInput={v.touch} />
                            </span>
                          </label>
                          <label className="field">
                            <span className="lbl">
                              {"Operations contact"}
                            </span>
                            <span className="input">
                              <input type="email" placeholder="[CONTACT EMAIL]" onInput={v.touch} />
                            </span>
                          </label>
                          <label className="field full">
                            <span className="lbl">
                              {"Registered address"}
                            </span>
                            <span className="input">
                              <input type="text" placeholder="[ADDRESS]" onInput={v.touch} />
                            </span>
                          </label>
                        </div>
                      </div>
                    </section>
                    <section className="panel">
                      <div className="card-h">
                        <span className="lbl strong">
                          {"Operating area"}
                        </span>
                        <span className="badge b-sim">
                          {"Approx. positions"}
                        </span>
                      </div>
                      <p className="card-p" style={{ padding: "0 18px" }}>
                        {"Sites and the area of operations define where missions can be planned."}
                      </p>
                      <div className="aomap" style={{ marginTop: "12px" }}>
                        <canvas className="gl" data-gl="ao"></canvas>
                        <div className="gl-labels" data-gl-labels="ao"></div>
                      </div>
                      <div className="card-b">
                        <div className="kvg c3">
                          <div>
                            <span className="lbl">
                              {"Region"}
                            </span>
                            <b>
                              {"Rajkot district, Gujarat"}
                            </b>
                          </div>
                          <div>
                            <span className="lbl">
                              {"Sites"}
                            </span>
                            <b>
                              {"6 · 3 pillars"}
                            </b>
                          </div>
                          <div>
                            <span className="lbl">
                              {"Boundary file"}
                            </span>
                            <b>
                              {"[AO BOUNDARY · GeoJSON]"}
                            </b>
                          </div>
                        </div>
                      </div>
                    </section>
                    <section className="panel">
                      <div className="card-h">
                        <span className="lbl strong">
                          {"Mission pillars"}
                        </span>
                        <span className="lbl">
                          {"Enabled for this organization"}
                        </span>
                      </div>
                      {(v.pillarRows || []).map((p, $index) => (
                        <React.Fragment key={$index}>
                        <div className="pill-t">
                          <i className="dia" style={{ background: `${p?.color ?? ""}` }}></i>
                          <div>
                            <div className="srow-t">
                              {p?.name}{" · "}{p?.long}
                            </div>
                            <div className="srow-s">
                              {p?.model}{" · "}{p?.sites}{" sites"}
                            </div>
                          </div>
                          <button className={`tgl ${p?.cls ?? ""}`} onClick={p?.toggle}>
                            <i></i>
                          </button>
                        </div>
                        </React.Fragment>
                      ))}
                    </section>
                  </div>
                  <div className="scroll stack">
                    <section className="panel">
                      <div className="card-h">
                        <span className="lbl strong">
                          {"Data residency & retention"}
                        </span>
                      </div>
                      <div className="srow" style={{ borderTop: "0", marginTop: "4px" }}>
                        <div>
                          <div className="srow-t">
                            {"Storage region"}
                          </div>
                          <div className="srow-s">
                            {"Where frames, detections and reports are stored"}
                          </div>
                        </div>
                        <span className="ro">
                          {"[REGION]"}
                        </span>
                      </div>
                      {(v.retention || []).map((r, $index) => (
                        <React.Fragment key={$index}>
                        <div className="ret">
                          <div>
                            <div className="srow-t">
                              {r?.name}
                            </div>
                            <div className="srow-s">
                              {r?.hint}
                            </div>
                          </div>
                          <div className="segs">
                            {(r?.opts || []).map((o, $index) => (
                              <React.Fragment key={$index}>
                              <button className={o?.cls} onClick={o?.pick}>
                                {o?.name}
                              </button>
                              </React.Fragment>
                            ))}
                          </div>
                        </div>
                        </React.Fragment>
                      ))}
                      <div className="srow">
                        <div>
                          <div className="srow-t">
                            {"Keep provenance labels on export"}
                          </div>
                          <div className="srow-s">
                            {"Simulated / manifest / EXIF labels are always included"}
                          </div>
                        </div>
                        <button className="tgl on" disabled={true}>
                          <i></i>
                        </button>
                      </div>
                    </section>
                    <section className="panel">
                      <div className="card-h">
                        <span className="lbl strong">
                          {"Report branding"}
                        </span>
                        <button className="btn btn-ghost btn-sm" onClick={() => alert('Brand Settings: Select SVG or PNG logo image for report header branding.')}>
                          {"Upload logo"}
                        </button>
                      </div>
                      <div className="card-b">
                        <div className="brand">
                          <div className="brand-tile dark">
                            <img src="/brand/logo-mark.png" alt="" />
                            <span>
                              {"App · dark"}
                            </span>
                          </div>
                          <div className="brand-tile light">
                            <img src="/brand/logo-mark.png" alt="" />
                            <b>
                              {"Aerolytics"}
                            </b>
                          </div>
                        </div>
                        <label className="field" style={{ marginTop: "12px" }}>
                          <span className="lbl">
                            {"Report footer"}
                          </span>
                          <span className="input">
                            <input type="text" placeholder="[REPORT FOOTER TEXT]" onInput={v.touch} />
                          </span>
                        </label>
                      </div>
                    </section>
                    <section className="panel">
                      <div className="card-h">
                        <span className="lbl strong">
                          {"Regulatory"}
                        </span>
                        <span className="badge b-sim">
                          {"Placeholders"}
                        </span>
                      </div>
                      {(v.reg || []).map((r, $index) => (
                        <React.Fragment key={$index}>
                        <div className="kvl-row">
                          <span>
                            {r?.k}
                          </span>
                          <b>
                            {r?.v}
                          </b>
                          <i></i>
                        </div>
                        </React.Fragment>
                      ))}
                      <div className="note">
                        {"Confirm current requirements with the aviation regulator before live operations"}
                      </div>
                    </section>
                    <section className="panel">
                      <div className="card-h">
                        <span className="lbl strong">
                          {"Plan & usage"}
                        </span>
                      </div>
                      <div className="card-b">
                        <div className="srow" style={{ padding: "8px 0", borderTop: "0" }}>
                          <div className="srow-t">
                            {"Seats"}
                          </div>
                          <div className="meter">
                            <span className="hbar">
                              <b style={{ width: "40%" }}></b>
                            </span>
                            <span className="mono" style={{ fontSize: "12px" }}>
                              {"4 / 10"}
                            </span>
                          </div>
                        </div>
                        <div className="srow" style={{ padding: "8px 0" }}>
                          <div className="srow-t">
                            {"Storage"}
                          </div>
                          <span className="mono muted" style={{ fontSize: "12px" }}>
                            {"Not metered in demo"}
                          </span>
                        </div>
                      </div>
                    </section>
                  </div>
                </div>
              </div>
            </div>
          </main>
        </div>
      </div>
    );
  }
}

export default View;
