'use client';
/* eslint-disable */
// Generated by scripts/convert-designs.mjs from design/landing-page/SignalLost.template.html — edit the design or the patches, then re-run.
import React from 'react';
import Base from './_base';
import { getPillar, setPillar, readJSON, writeJSON, signIn, signOut, saveSession, downloadFile } from '@/lib/store';
import { API_URL, pingApi, inferFile, submitRequest } from '@/lib/api';
import { sessionData } from '@/lib/session';
import './css/SignalLost.css';

class View extends Base {
  constructor(props) {
    super(props);
    this.state = { kind: props.variant === '500' ? '500' : '404' };
    this._kind = this.state.kind;
  }

  renderVals() {
    const { kind } = this.state;
    this._kind = kind;
    const V = {
      '404': {
        code: '404', codeCls: 'code', color: '#5CE1FF', kicker: 'Page not found', title: 'Signal lost.',
        body: 'The page you were tracking has gone off the map. It may have moved, or the link is out of date.',
        primary: 'Return to dashboard', secondary: 'Open mission log', badge: 'Link lost', badgeCls: 'badge b-man', link: 'No route',
        rows: [['Requested', typeof window !== 'undefined' ? window.location.pathname : '—'], ['Last route', '/dashboard'], ['Status', 'HTTP 404'], ['Time', 'now']],
      },
      '500': {
        code: '500', codeCls: 'code err', color: '#FF6A3D', kicker: 'Server error', title: 'Link failure.',
        body: 'Something failed on our side while loading this view. Your missions and reports are not affected. Try again in a moment.',
        primary: 'Try again', secondary: 'View system status', badge: 'Incident', badgeCls: 'badge b-crit', link: 'Link down',
        rows: [['Reference', 'ERR-' + (this.props.errorRef || '[REQUEST ID]')], ['Service', '[FAILING SERVICE]'], ['Status', 'HTTP 500'], ['Time', 'now']],
      },
    }[kind];
    V.rows = V.rows.map(([k, v]) => ({ k, v: v === 'now' ? new Date().toISOString().slice(11, 19) + ' UTC' : v }));
    return {
      v: V,
      primaryAct: () => { if (kind === '500') { if (this.props.reset) this.props.reset(); else window.location.reload(); } else this.go('/dashboard'); },
      secondaryAct: () => this.go(kind === '500' ? '/status' : '/missions'),
      variants: [['404', '404 · Not found'], ['500', '500 · Error']].map(([k, name]) => ({ name, cls: kind === k ? 'on' : '', pick: () => this.setState({ kind: k }) })),
    };
  }

  componentDidMount() {
    this._syncPillar(); this._alive = true; this._boot(0); }
  componentWillUnmount() { this._alive = false; if (this._raf) cancelAnimationFrame(this._raf); }

  _boot(tries) {
    if (!this._alive) return;
    const canvas = document.querySelector('[data-gl="lost"]');
    if (!canvas) { if (tries < 120) requestAnimationFrame(() => this._boot(tries + 1)); return; }
    this._loop([this._lostScene(this._engine(), canvas)]);
  }

  // Drifting aircraft over fogged terrain; the link to the ground station keeps dropping out.
  _lostScene(K, canvas) {
    const R = K.renderer(canvas, [0.008, 0.024, 0.06]);
    if (!R) return null;
    const { Batch, COL, a, lerp, smooth } = K;
    const self = this;
    const ground = (x, z) => 10 * Math.sin(x * 0.03 + 1.2) * Math.cos(z * 0.025) + 5 * Math.sin(x * 0.07 + z * 0.05) + 3 * Math.cos(z * 0.1);
    const tb = new Batch();
    for (let g = -200; g <= 200; g += 10) for (let u = -200; u < 200; u += 5) {
      const c = (h) => [lerp(0.12, 0.36, smooth(-10, 16, h)), lerp(0.24, 0.58, smooth(-10, 16, h)), lerp(0.55, 0.9, smooth(-10, 16, h)), 0.14 + 0.2 * smooth(-10, 16, h)];
      const h1 = ground(u, g), h2 = ground(u + 5, g), k1 = ground(g, u), k2 = ground(g, u + 5);
      tb.line(u, h1, g, u + 5, h2, g, c(h1), c(h2));
      tb.line(g, k1, u, g, k2, u + 5, c(k1), c(k2));
    }
    const terrain = new Float32Array(tb.a);
    const tower = [-40, ground(-40, 30), 30];
    return {
      frame(t) {
        const asp = R.resize();
        const err = self._kind === '500';
        const cy = 0.9 + t * 0.02, rad = 120 * Math.max(1, 1.3 / asp);
        const T = [18, 20, 0];
        const eye = [T[0] + rad * Math.cos(0.32) * Math.sin(cy), T[1] + rad * Math.sin(0.32), T[2] + rad * Math.cos(0.32) * Math.cos(cy)];
        const M = K.camera(asp, eye, T, 0.75);
        R.begin(M, eye, 60, 260);
        R.draw(terrain, 'lines', 'add');
        const ln = new Batch(), pts = new Batch();
        const dx = 30 + Math.sin(t * 0.37) * 8, dy = 30 + Math.sin(t * 0.8) * 2.5, dz = -6 + Math.cos(t * 0.29) * 7;
        const wob = Math.sin(t * 1.3) * 0.35;
        const tone = err ? COL.crit : COL.white;
        const flick = Math.sin(t * 23) > 0.3 && Math.sin(t * 3.1) > -0.4 ? 1 : 0.1;
        self._drawDrone(K, ln, dx, dy, dz, t * 0.4 + wob, 2.2, err ? 0 : t * (0.3 + 0.7 * flick), { color: a(tone, 0.4 + 0.6 * flick), rotor: err ? COL.crit : COL.blue });
        // ground station mast
        ln.line(tower[0], tower[1], tower[2], tower[0], tower[1] + 18, tower[2], a(COL.cyan, 0.8));
        ln.line(tower[0] - 4, tower[1], tower[2] - 4, tower[0], tower[1] + 18, tower[2], a(COL.cyan, 0.5));
        ln.line(tower[0] + 4, tower[1], tower[2] + 4, tower[0], tower[1] + 18, tower[2], a(COL.cyan, 0.5));
        for (let r = 1; r <= 3; r++) { const ph = (t * 0.5 + r / 3) % 1; ln.ring(tower[0], tower[1] + 18, tower[2], 2 + ph * 12, 24, a(COL.cyan, 0.4 * (1 - ph))); }
        // broken link: dashes that appear and vanish
        const top = [tower[0], tower[1] + 18, tower[2]], seg = 24;
        for (let k = 0; k < seg; k++) {
          const on = Math.sin(t * 6 + k * 1.7) > (err ? 0.4 : 0.1) && k % 2 === 0;
          if (!on) continue;
          const u1 = k / seg, u2 = (k + 0.6) / seg;
          ln.line(lerp(top[0], dx, u1), lerp(top[1], dy, u1), lerp(top[2], dz, u1), lerp(top[0], dx, u2), lerp(top[1], dy, u2), lerp(top[2], dz, u2), a(err ? COL.crit : COL.warn, 0.7 * (1 - u1 * 0.6)));
        }
        pts.v(dx, dy - 4, dz, a(err ? COL.crit : COL.cyan, 0.35 * flick));
        pts.v(top[0], top[1], top[2], a(COL.cyan, 0.9));
        R.draw(ln, 'lines', 'add');
        R.draw(pts, 'points', 'add', 80);
      },
    };
  }



  render() {
    const v = this.renderVals();
    return (
      <div className="pg-signal-lost ds">
        <div className="lost">
          <canvas className="gl" data-gl="lost"></canvas>
          <div className="shade"></div>
          <div className="noise"></div>
          <div className="scan"></div>
          <header className="top">
            <span className="lockup">
              <img src="/brand/logo-mark.png" alt="" />
              <b>
                {"Aerolytics"}
              </b>
            </span>
            <span className={v.v?.badgeCls}>
              {v.v?.badge}
            </span>
          </header>
          <section className="copy">
            <div className="kicker" style={{ color: `${v.v?.color ?? ""}` }}>
              <i></i>
              {v.v?.kicker}
            </div>
            <div className={v.v?.codeCls}>
              {v.v?.code}
            </div>
            <h1>
              {v.v?.title}
            </h1>
            <p>
              {v.v?.body}
            </p>
            <div className="acts">
              <button className="btn btn-primary" onClick={v.primaryAct}>
                {v.v?.primary}
              </button>
              <button className="btn btn-ghost" onClick={v.secondaryAct}>
                {v.v?.secondary}
              </button>
            </div>
          </section>
          <aside className="glass hud">
            <div className="hud-head" style={{ display: "flex", justifyContent: "space-between", marginBottom: "8px" }}>
              <span className="lbl strong">
                {"Last known position"}
              </span>
              <span className="chip" style={{ color: `${v.v?.color ?? ""}` }}>
                {v.v?.link}
              </span>
            </div>
            {(v.v?.rows || []).map((r, $index) => (
              <React.Fragment key={$index}>
              <div className="kvl-row">
                <span>
                  {r?.k}
                </span>
                <b>
                  {r?.v}
                </b>
                <i></i>
              </div>
              </React.Fragment>
            ))}
          </aside>
          <div className="variant">
            <span className="lbl">
              {"Variant"}
            </span>
            <div className="segs">
              {(v.variants || []).map((o, $index) => (
                <React.Fragment key={$index}>
                <button className={o?.cls} onClick={o?.pick}>
                  {o?.name}
                </button>
                </React.Fragment>
              ))}
            </div>
          </div>
        </div>
      </div>
    );
  }
}

export default View;
