'use client';
/* eslint-disable */
// Generated by scripts/convert-designs.mjs from design/landing-page/SiteDetail.template.html — edit the design or the patches, then re-run.
import React from 'react';
import Link from 'next/link';
import Base from './_base';
import { AppRail, TopBar } from '@/components/chrome';
import { getPillar, setPillar, readJSON, writeJSON, signIn, signOut, saveSession, downloadFile } from '@/lib/store';
import { API_URL, pingApi, inferFile, submitRequest } from '@/lib/api';
import { sessionData } from '@/lib/session';
import './css/SiteDetail.css';

class View extends Base {
  constructor(props) {
    super(props);
    this.state = { pillar: props.pillar || 'energy', view: 'orbit', selMission: null };
  }

  renderVals() {
    const D = this._data();
    const { pillar, view, selMission } = this.state;
    const pc = D.P[pillar];
    const siteKey = (this.props.id && D.sites.some((s) => s.key === this.props.id && s.pillar === pillar)) ? this.props.id : { energy: 'rsp', agri: 'kfb', rescue: 'ads' }[pillar];
    const site = D.sites.find((s) => s.key === siteKey);
    const crit = pc.dets.filter((q) => q.sev === 'crit').length, warn = pc.dets.length - crit;
    const max = Math.max(1, crit, warn);
    const history = D.missionsAll.filter((m) => m.siteKey === siteKey);
    const aircraft = { energy: 'QUAD-01', agri: 'QUAD-02', rescue: 'THERM-01' }[pillar];
    return {
      pillars: this._pillarTabs(pillar, (k) => { this.setState({ pillar: k, selMission: null }); if (this._twin) this._twin.setPillar(k); }),
      pc, site,
      critN: crit,
      views: [['orbit', '3D'], ['top', 'Top'], ['follow', 'Follow']].map(([k, name]) => ({ name, cls: view === k ? 'on' : '', pick: () => { this.setState({ view: k }); if (this._twin) this._twin.setView(k); } })),
      sevRows: [['Critical', crit, 'sev-crit', '#FF6A3D'], ['Warning', warn, 'sev-warn', '#FFB547']].map(([name, n, cls, color]) => ({ name, n, cls, color, w: (n / max) * 100 + '%' })),
      schedule: [
        [site.next === 'On call' ? '—' : site.next.slice(0, 2), site.next === 'On call' ? 'On call' : 'Sep', pillar === 'rescue' ? 'Standby sweep' : 'Routine inspection', aircraft + ' · 7 lanes · 42 m AGL', 'Planned', 'st-new'],
        ['05', 'Oct', pillar === 'agri' ? 'Disease follow-up · cells C-07, H-11' : pillar === 'rescue' ? 'Night thermal drill' : 'Re-inspect critical panels', aircraft + ' · targeted', 'Needs aircraft', 'st-warn'],
        ['19', 'Oct', 'Full-site survey', 'Aircraft TBD · full coverage', 'Draft', 'st-off'],
      ].map(([day, mon, title, detail, status, cls]) => ({ day, mon, title, detail, status, cls })),
      history: history.map((m) => ({
        id: m.id, date: m.date, tele: m.tele, det: m.det, covStr: m.coverage + '%',
        selCls: m.id === selMission ? 'sel' : '', pick: () => this.setState({ selMission: m.id }),
      })),
      details: [
        ['Owner', '[ORGANIZATION NAME]'], ['Boundary', 'Polygon · 6 vertices · approx.'], ['Centroid', site.lat + ', ' + site.lon],
        ['Elevation', '≈ 140 m · sample'], ['Airspace', '[AIRSPACE ZONE / PERMISSION]'], ['Access', '[SITE ACCESS NOTES]'],
      ].map(([k, v]) => ({ k, v })),
    };
  }

  componentDidMount() {
    this._syncPillar();
    this._alive = true;
    this._startClock();
    this._boot(0);
  }

  componentWillUnmount() {
    this._alive = false;
    this._stopClock();
    if (this._raf) cancelAnimationFrame(this._raf);
    if (this._twin) this._twin.destroy();
  }

  _boot(tries) {
    if (!this._alive) return;
    const canvas = document.querySelector('[data-gl="twin"]');
    if (!canvas) { if (tries < 120) requestAnimationFrame(() => this._boot(tries + 1)); return; }
    const hud = { lat: document.querySelector('[data-hud="lat"]'), lon: document.querySelector('[data-hud="lon"]') };
    this._twin = this._twinScene(this._engine(), canvas, {
      pillar: this.state.pillar, mode: 'overview', labelsEl: document.querySelector('[data-gl-labels="twin"]'),
      onPick: (id) => { if (this._twin) this._twin.select(id); },
      onHud: (h) => { if (hud.lat) hud.lat.textContent = h.lat; if (hud.lon) hud.lon.textContent = h.lon; },
    });
    this._loop([this._twin]);
  }



  render() {
    const v = this.renderVals();
    return (
      <div className="pg-site-detail ds">
        <div className="app">
          <AppRail active="sites" />
          <TopBar crumbs={["Sites","Site detail"]} pillars={v.pillars} />
          <main className="main">
            <div className="page">
              <div className="page-head">
                <div>
                  <div className="kicker" style={{ color: `${v.pc?.color ?? ""}` }}>
                    <i></i>
                    {"Site · "}{v.pc?.name}
                  </div>
                  <h1 className="h1" style={{ marginTop: "10px" }}>
                    {v.site?.name}
                  </h1>
                </div>
                <div className="meta">
                  {v.site?.lat}{" · "}{v.site?.lon}{" · approx. centroid"}
                </div>
                <div className="acts">
                  <Link className="btn btn-ghost" href={'/mission-planner'}>
                    {"Plan mission"}
                  </Link>
                  <Link className="btn btn-primary" href={'/missions/new'}>
                    {"+ New inspection"}
                  </Link>
                </div>
              </div>
              <div className="cols">
                <section className="panel">
                  <div className="ph">
                    <div className="ph-l">
                      <span className="lbl strong">
                        {"Site twin · latest mission "}{v.site?.lastMission}
                      </span>
                      <span className="badge b-sim">
                        {"Simulated telemetry"}
                      </span>
                    </div>
                    <div className="segs">
                      {(v.views || []).map((v, $index) => (
                        <React.Fragment key={$index}>
                        <button className={v?.cls} onClick={v?.pick}>
                          {v?.name}
                        </button>
                        </React.Fragment>
                      ))}
                    </div>
                  </div>
                  <div className="view3d">
                    <canvas className="gl" data-gl="twin"></canvas>
                    <div className="gl-labels" data-gl-labels="twin"></div>
                    <div className="ov ov-tl glass stats">
                      <div className="kvg">
                        <div>
                          <span className="lbl">
                            {"Area"}
                          </span>
                          <b>
                            {v.site?.area}
                          </b>
                        </div>
                        <div>
                          <span className="lbl">
                            {"Health"}
                          </span>
                          <b>
                            {v.site?.health}{"%"}
                          </b>
                        </div>
                        <div style={{ gridColumn: "1 / -1" }}>
                          <span className="lbl">
                            {"Assets"}
                          </span>
                          <b>
                            {v.site?.assets}
                          </b>
                        </div>
                      </div>
                    </div>
                    <div className="ov ov-bl readout">
                      {"DRONE "}
                      <b data-hud="lat">
                        {"22.30000° N"}
                      </b>
                      {" "}
                      <b data-hud="lon">
                        {"70.80000° E"}
                      </b>
                      {" "}
                      <span className="amber">
                        {"±APPROX."}
                      </span>
                    </div>
                    <div className="ov ov-br glass legend">
                      <span>
                        <i className="dia sev-crit"></i>
                        {"Critical"}
                      </span>
                      <span>
                        <i className="dia sev-warn"></i>
                        {"Warning"}
                      </span>
                      <span>
                        <svg width="22" height="4">
                          <line x1="0" y1="2" x2="22" y2="2" stroke="#FFB547" strokeWidth="2" strokeDasharray="4 3"></line>
                        </svg>
                        {"Simulated path"}
                      </span>
                    </div>
                  </div>
                </section>
                <div className="scroll stack">
                  <section className="panel">
                    <div className="ph">
                      <span className="lbl strong">
                        {"Open issues"}
                      </span>
                      <span className="badge b-crit">
                        {v.critN}{" critical"}
                      </span>
                    </div>
                    <div className="sev">
                      {(v.sevRows || []).map((r, $index) => (
                        <React.Fragment key={$index}>
                        <div className="sev-row">
                          <span>
                            <i className={`dia ${r?.cls ?? ""}`}></i>
                            {r?.name}
                          </span>
                          <div className="hbar">
                            <b style={{ width: `${r?.w ?? ""}`, background: `${r?.color ?? ""}` }}></b>
                          </div>
                          <b>
                            {r?.n}
                          </b>
                        </div>
                        </React.Fragment>
                      ))}
                      <div className="meta">
                        {"Oldest open item · 9 days · sample"}
                      </div>
                    </div>
                  </section>
                  <section className="panel">
                    <div className="ph">
                      <span className="lbl strong">
                        {"Inspection schedule"}
                      </span>
                      <button className="btn btn-ghost btn-sm" onClick={() => alert('Schedule Inspection Window: Select recurring flight plan frequency (Daily, Weekly, Monthly) for this site.')}>
                        {"+ Schedule"}
                      </button>
                    </div>
                    {(v.schedule || []).map((s, $index) => (
                      <React.Fragment key={$index}>
                      <div className="li sched">
                        <div className="date">
                          <b>
                            {s?.day}
                          </b>
                          <span>
                            {s?.mon}
                          </span>
                        </div>
                        <div style={{ minWidth: "0" }}>
                          <span className="li-t" style={{ fontSize: "14px" }}>
                            {s?.title}
                          </span>
                          <span className="li-s">
                            {s?.detail}
                          </span>
                        </div>
                        <span className={`chip ${s?.cls ?? ""}`}>
                          {s?.status}
                        </span>
                      </div>
                      </React.Fragment>
                    ))}
                  </section>
                  <section className="panel">
                    <div className="ph">
                      <span className="lbl strong">
                        {"Mission history"}
                      </span>
                      <Link className="btn btn-ghost btn-sm" href={'/missions'}>
                        {"All →"}
                      </Link>
                    </div>
                    {(v.history || []).map((h, $index) => (
                      <React.Fragment key={$index}>
                      <button className={`li hist ${h?.selCls ?? ""}`} onClick={h?.pick}>
                        <span style={{ minWidth: "0" }}>
                          <span className="li-t" style={{ fontSize: "14px" }}>
                            {h?.id}
                          </span>
                          <span className="li-s">
                            {h?.date}{" · "}{h?.tele}
                          </span>
                        </span>
                        <span className="hbar">
                          <b style={{ width: `${h?.covStr ?? ""}` }}></b>
                        </span>
                        <em>
                          {h?.det}
                        </em>
                      </button>
                      </React.Fragment>
                    ))}
                  </section>
                  <section className="panel">
                    <div className="ph">
                      <span className="lbl strong">
                        {"Site details"}
                      </span>
                    </div>
                    {(v.details || []).map((d, $index) => (
                      <React.Fragment key={$index}>
                      <div className="kvl-row">
                        <span>
                          {d?.k}
                        </span>
                        <b>
                          {d?.v}
                        </b>
                        <i></i>
                      </div>
                      </React.Fragment>
                    ))}
                    <div className="note">
                      {"Bracketed values are placeholders to fill in"}
                    </div>
                  </section>
                </div>
              </div>
            </div>
          </main>
        </div>
      </div>
    );
  }
}

export default View;
