'use client';
/* eslint-disable */
// Generated by scripts/convert-designs.mjs from design/landing-page/Solutions.template.html — edit the design or the patches, then re-run.
import React from 'react';
import Link from 'next/link';
import Base from './_base';
import { MkNav, MkFoot } from '@/components/chrome';
import { getPillar, setPillar, readJSON, writeJSON, signIn, signOut, saveSession, downloadFile } from '@/lib/store';
import { API_URL, pingApi, inferFile, submitRequest } from '@/lib/api';
import { sessionData } from '@/lib/session';
import './css/Solutions.css';

class View extends Base {
  constructor(props) {
    super(props);
    this.state = { pillar: props.pillar || 'energy' };
  }

  // Model facts copied from models/training/*/data.yaml, args.yaml and results.csv (final epoch).
  _facts() {
    return {
      energy: {
        h1a: 'Every panel,', h1b: 'inspected to the row.', weights: 'solar_best.pt', epochs: 15,
        lede: 'Find cracked, soiled and covered panels across an entire PV plant from one flight, each finding pinned to its row and panel.',
        m: [0.636, 0.372, 0.719, 0.573], split: [1880, 310, 90], classes: ['cover', 'crack', 'dust', 'normal'], dataset: 'Roboflow solar-panel v3 · private',
        flowTitle: 'One flight over the array.',
        steps: [['Plan', 'Lanes follow panel rows at 40–45 m with enough overlap to see every module.'], ['Fly & upload', 'RGB frames, plus thermal when fitted, upload with EXIF GPS or a flight manifest.'], ['Detect', 'solar_best.pt flags cracks, dust and cover obstructions with a confidence score.'], ['Act', 'Critical panels are assigned to crews and tracked until resolved.']],
        limits: ['Hotspot detection needs a radiometric thermal payload; the current model reads RGB defects.', 'Precision and recall are validation-split figures from 15 epochs, not field-verified accuracy.'],
      },
      agri: {
        h1a: 'See disease', h1b: 'before it spreads.', weights: 'agri_best.pt', epochs: 15,
        lede: 'Spot leaf rust, blight, blast and brown spots early, see where they cluster, and estimate the affected area.',
        m: [0.766, 0.449, 0.759, 0.708], split: [2770, 331, 332], classes: ['Blast', 'brownspots', 'leaf blight', 'leaf rust', 'others'], dataset: 'Roboflow crop-disease v1 · CC BY 4.0',
        flowTitle: 'One sweep over the field.',
        steps: [['Plan', 'A block is covered in parallel lanes; multispectral payloads fly lower for detail.'], ['Fly & upload', 'Frames upload with EXIF GPS; files without it are matched to the manifest.'], ['Detect', 'agri_best.pt classifies disease symptoms per frame and marks affected cells.'], ['Act', 'Zones are prioritised for scouting or spraying, and re-flown to track spread.']],
        limits: ['The NDVI-style view is a visual aid, not a calibrated vegetation index.', 'Affected-area estimates depend on positions, which are approximate without RTK.'],
      },
      rescue: {
        h1a: 'Find people', h1b: 'through the dark.', weights: 'thermal_best.pt', epochs: 15,
        lede: 'Scan disaster zones with thermal cameras, detect people through darkness and debris, and put every signature on the responders’ map.',
        m: [0.879, 0.455, 0.885, 0.824], split: [2008, 287, 571], classes: ['person'], dataset: 'Roboflow drone-thermal v4 · private',
        flowTitle: 'One sweep over the search area.',
        steps: [['Plan', 'Search lanes are flown low and slow over the response zone.'], ['Fly & stream', 'Thermal frames upload during or after the flight, with position from the aircraft or manifest.'], ['Detect', 'thermal_best.pt marks each person with a confidence score.'], ['Act', 'Targets are dispatched, confirmed and logged for the after-action report.']],
        limits: ['The model detects people only; vehicle detection is planned.', 'A detection is a lead for responders, not a confirmed find.'],
      },
    };
  }

  renderVals() {
    const D = this._data();
    const { pillar } = this.state;
    const P = D.P[pillar], F = this._facts()[pillar];
    const [map50, map5095, prec, rec] = F.m;
    return {
      p: Object.assign({ key: pillar, name: P.name, color: P.color }, F),
      tabs: ['energy', 'agri', 'rescue'].map((k) => ({
        idx: D.P[k].idx, name: D.P[k].name, color: D.P[k].color, cls: k === pillar ? 'on' : '',
        pick: () => { this.setState({ pillar: k }); if (this._twin) this._twin.setPillar(k); window.history.replaceState(null, '', '/solutions/' + k); },
      })),
      metrics: [
        ['mAP50', map50.toFixed(3), 'Validation split'],
        ['mAP50-95', map5095.toFixed(3), 'Stricter IoU range'],
        ['Precision', prec.toFixed(3), 'Share of boxes that were right'],
        ['Recall', rec.toFixed(3), 'Share of objects found'],
        ['Train images', F.split[0].toLocaleString('en-US'), F.split[1] + ' val · ' + F.split[2] + ' test'],
        ['Base model', 'v8n', 'YOLOv8 nano · 640 px'],
      ].map(([k, v, note]) => ({ k, v, note })),
      classes: F.classes.map((name) => ({ name })),
      steps: F.steps.map(([t, b], i) => ({ n: String(i + 1).padStart(2, '0'), t, b })),
      outs: [
        ['Inspection dossier', 'Frame crop, confidence, location and status for every finding.'],
        ['3D digital twin', 'Findings on a model of the site, with flight path and coverage.'],
        ['PDF & JSON report', 'Built from the session data, with the provenance statement included.'],
      ].map(([t, b]) => ({ t, b, thumb: P.thumb })),
      limits: F.limits.map((t) => ({ t })),
    };
  }

  componentDidMount() {
    this._syncPillar(); this._alive = true; this._boot(0); }
  componentWillUnmount() { this._alive = false; if (this._raf) cancelAnimationFrame(this._raf); if (this._twin) this._twin.destroy(); }

  _boot(tries) {
    if (!this._alive) return;
    const canvas = document.querySelector('[data-gl="twin"]');
    if (!canvas) { if (tries < 120) requestAnimationFrame(() => this._boot(tries + 1)); return; }
    this._twin = this._twinScene(this._engine(), canvas, { pillar: this.state.pillar, mode: 'overview', labelsEl: document.querySelector('[data-gl-labels="twin"]') });
    this._loop([this._twin]);
  }



  render() {
    const v = this.renderVals();
    return (
      <div className="pg-solutions ds">
        <div className="mk">
          <MkNav active="solutions" />
          <section className="hero">
            <canvas className="gl" data-gl="twin"></canvas>
            <div className="gl-labels" data-gl-labels="twin"></div>
            <div className="mk-shade"></div>
            <div className="hero-copy">
              <div className="kicker" style={{ color: `${v.p?.color ?? ""}` }}>
                <i></i>
                {"Solutions · "}{v.p?.name}
              </div>
              <h1 className="mk-h1">
                {v.p?.h1a}
                <br />
                <span style={{ color: `${v.p?.color ?? ""}` }}>
                  {v.p?.h1b}
                </span>
              </h1>
              <p className="mk-lede">
                {v.p?.lede}
              </p>
              <div className="mk-cta">
                <Link className="btn btn-primary" href={'/contact'}>
                  {"Request a "}{v.p?.name}{" pilot"}
                </Link>
                <Link className="btn btn-ghost" href={'/demo'}>
                  {"See it in the demo"}
                </Link>
              </div>
            </div>
            <div className="ptabs">
              {(v.tabs || []).map((t, $index) => (
                <React.Fragment key={$index}>
                <button className={`ptab ${t?.cls ?? ""}`} style={{ color: `${t?.color ?? ""}` }} onClick={t?.pick}>
                  <small>
                    {t?.idx}
                  </small>
                  <span>
                    {t?.name}
                  </span>
                </button>
                </React.Fragment>
              ))}
            </div>
            <div className="route readout">
              {"ROUTE "}
              <b>
                {"/solutions/"}{v.p?.key}
              </b>
              {" · "}
              <span className="amber">
                {"SIMULATED TWIN"}
              </span>
            </div>
          </section>
          <section className="mk-sec">
            <div className="kicker">
              <i></i>
              {"01 / Model card"}
            </div>
            <h2 className="mk-h2">
              {"Measured, not promised."}
            </h2>
            <p className="mk-p">
              {"Numbers below come from the training run of "}
              <span className="mono" style={{ color: "#fff" }}>
                {v.p?.weights}
              </span>
              {", scored on its validation split after "}{v.p?.epochs}{" epochs. They are not field accuracy."}
            </p>
            <div className="panel card-model">
              {(v.metrics || []).map((m, $index) => (
                <React.Fragment key={$index}>
                <div className="mc">
                  <span className="lbl">
                    {m?.k}
                  </span>
                  <b>
                    {m?.v}
                  </b>
                  <em>
                    {m?.note}
                  </em>
                </div>
                </React.Fragment>
              ))}
            </div>
            <div className="model-meta">
              <span className="lbl" style={{ marginRight: "6px" }}>
                {"Classes"}
              </span>
              {(v.classes || []).map((c, $index) => (
                <React.Fragment key={$index}>
                <span className="chip" style={{ color: "#CFDAEE" }}>
                  {c?.name}
                </span>
                </React.Fragment>
              ))}
              <span className="chip st-off">
                {"Dataset · "}{v.p?.dataset}
              </span>
            </div>
          </section>
          <section className="mk-sec">
            <div className="kicker">
              <i></i>
              {"02 / How a mission runs"}
            </div>
            <h2 className="mk-h2">
              {v.p?.flowTitle}
            </h2>
            <div className="steps">
              {(v.steps || []).map((s, $index) => (
                <React.Fragment key={$index}>
                <div className="panel step">
                  <div className="n" style={{ color: `${v.p?.color ?? ""}` }}>
                    {s?.n}
                  </div>
                  <h3>
                    {s?.t}
                  </h3>
                  <p>
                    {s?.b}
                  </p>
                </div>
                </React.Fragment>
              ))}
            </div>
          </section>
          <section className="mk-sec">
            <div className="kicker">
              <i></i>
              {"03 / What operators get"}
            </div>
            <h2 className="mk-h2">
              {"From detection to decision."}
            </h2>
            <div className="outs">
              {(v.outs || []).map((o, $index) => (
                <React.Fragment key={$index}>
                <div className="panel out">
                  <div className={`thumb ${o?.thumb ?? ""}`}>
                    <span className="bbox"></span>
                  </div>
                  <h3>
                    {o?.t}
                  </h3>
                  <p>
                    {o?.b}
                  </p>
                </div>
                </React.Fragment>
              ))}
            </div>
            <div className="limits">
              {(v.limits || []).map((l, $index) => (
                <React.Fragment key={$index}>
                <div className="warnbox">
                  <i className="dia sev-warn"></i>
                  <span>
                    {l?.t}
                  </span>
                </div>
                </React.Fragment>
              ))}
            </div>
          </section>
          <MkFoot />
        </div>
      </div>
    );
  }
}

export default View;
