'use client';
/* eslint-disable */
// Generated by scripts/convert-designs.mjs from design/landing-page/Status.template.html — edit the design or the patches, then re-run.
import React from 'react';
import Base from './_base';
import { AppRail, TopBar } from '@/components/chrome';
import { getPillar, setPillar, readJSON, writeJSON, signIn, signOut, saveSession, downloadFile } from '@/lib/store';
import { API_URL, pingApi, inferFile, submitRequest } from '@/lib/api';
import { sessionData } from '@/lib/session';
import './css/Status.css';

class View extends Base {
  constructor(props) {
    super(props);
    this.state = { pillar: 'energy', sf: 'all', sel: 'infer' };
    this._sel = 'infer';
  }

  _services() {
    return [
      { key: 'web', name: 'Web app', desc: 'Command center you are using now', st: 'op', node: [0, 0, 26] },
      { key: 'drone', name: 'Drone telemetry source', desc: 'Golden-demo flight manifest (backend/telemetry.py)', st: 'demo', node: [-44, 6, -14] },
      { key: 'ingest', name: 'Telemetry ingest · WebSocket', desc: 'Live stream endpoint · demo stream only', st: 'demo', node: [-26, 0, -6] },
      { key: 'infer', name: 'Inference API · FastAPI', desc: 'POST /api/v1/infer/{pillar} · ' + API_URL, st: this.state && this.state.api === true ? 'op' : this.state && this.state.api === false ? 'down' : 'demo', node: [-6, 4, -2] },
      { key: 'm-energy', name: 'Model · solar_best.pt', desc: 'Weights present · not benchmarked', st: 'demo', node: [-10, 14, -14] },
      { key: 'm-agri', name: 'Model · agri_best.pt', desc: 'Weights present · not benchmarked', st: 'demo', node: [-2, 16, -18] },
      { key: 'm-rescue', name: 'Model · thermal_best.pt', desc: 'Weights present · not benchmarked', st: 'demo', node: [6, 14, -14] },
      { key: 'geo', name: 'Normalize & geo-map', desc: 'Detections → site coordinates', st: 'op', node: [14, 0, 4] },
      { key: 'report', name: 'Report export', desc: 'PDF / JSON from session payload', st: 'demo', node: [30, 2, 16] },
      { key: 'mqtt', name: 'MQTT gateway', desc: 'Real aircraft telemetry', st: 'planned', node: [-44, -2, 12] },
      { key: 'postgis', name: 'PostGIS database', desc: 'Sites, missions, detections', st: 'planned', node: [24, -8, -16] },
      { key: 'storage', name: 'Object storage', desc: 'Frames and annotated imagery', st: 'planned', node: [36, -4, -2] },
    ];
  }

  renderVals() {
    const { pillar, sf, sel } = this.state;
    const all = this._services();
    const meta = { op: ['Operational', '#7BE3A0'], demo: ['Demo mode', '#FFB547'], planned: ['Planned', '#62738F'], down: ['Unreachable', '#FF6A3D'] };
    const list = all.filter((s) => sf === 'all' || s.st === sf);
    const cur = all.find((s) => s.key === sel) || all[0];
    this._sel = cur.key;
    const count = (k) => all.filter((s) => s.st === k).length;
    return {
      pillars: this._pillarTabs(pillar, (k) => this.setState({ pillar: k })),
      filters: [['all', 'All'], ['op', 'Up'], ['demo', 'Demo'], ['planned', 'Planned']].map(([k, name]) => ({ name, cls: sf === k ? 'on' : '', pick: () => this.setState({ sf: k }) })),
      summary: [['Services', all.length, '#fff'], ['Operational', count('op'), '#7BE3A0'], ['Demo mode', count('demo'), '#FFB547'], ['Planned', count('planned'), '#9FB0CC']].map(([k, n, color]) => ({ k, n, color })),
      services: list.map((s) => ({
        name: s.name, desc: s.desc, status: meta[s.st][0], color: meta[s.st][1],
        cells: Array.from({ length: 30 }, (_, i) => ({ i })), stripCls: s.st === 'op' ? 'strip live' : 'strip',
        hist: s.st === 'planned' ? 'not deployed' : 'today only',
        selCls: s.key === cur.key ? 'sel' : '', pick: () => this.setState({ sel: s.key }),
      })),
      selName: cur.name,
    };
  }

  componentDidMount() {
    this._syncPillar(); this._alive = true; this._startClock(); this._boot(0); pingApi().then((ok) => { if (this._alive) this.setState({ api: ok }); }); }

  componentWillUnmount() {
    this._alive = false;
    this._stopClock();
    if (this._raf) cancelAnimationFrame(this._raf);
    if (this._topo) this._topo.destroy();
  }

  _boot(tries) {
    if (!this._alive) return;
    const canvas = document.querySelector('[data-gl="topo"]');
    if (!canvas) { if (tries < 120) requestAnimationFrame(() => this._boot(tries + 1)); return; }
    this._topo = this._topoScene(this._engine(), canvas, document.querySelector('[data-gl-labels="topo"]'));
    this._loop([this._topo]);
  }

  // 3D service topology with packets travelling along live edges.
  _topoScene(K, canvas, labelsEl) {
    const R = K.renderer(canvas, [0.016, 0.043, 0.11]);
    if (!R) return null;
    const { Batch, COL, a, lerp, clamp } = K;
    const self = this;
    const svcs = this._services();
    const by = {};
    svcs.forEach((s) => { by[s.key] = s; });
    const EDGES = [['drone', 'ingest'], ['ingest', 'infer'], ['infer', 'm-energy'], ['infer', 'm-agri'], ['infer', 'm-rescue'], ['infer', 'geo'], ['geo', 'web'], ['geo', 'report'], ['report', 'web'], ['mqtt', 'ingest'], ['geo', 'postgis'], ['infer', 'storage']];
    const col = (st) => (st === 'op' ? COL.green : st === 'demo' ? COL.warn : [0.38, 0.45, 0.56, 1]);
    const tags = {};
    svcs.forEach((s) => {
      if (!labelsEl) return;
      const el = document.createElement('div');
      el.className = 'gl-tag';
      el.style.color = s.st === 'op' ? '#7BE3A0' : s.st === 'demo' ? '#FFB547' : '#7F90AD';
      el.textContent = s.name.split(' · ')[s.key.indexOf('m-') === 0 ? 1 : 0];
      labelsEl.appendChild(el);
      tags[s.key] = el;
    });
    const grid = new Batch();
    for (let g = -60; g <= 60; g += 6) { grid.line(g, -14, -40, g, -14, 40, [0.3, 0.55, 1, 0.06]); grid.line(-60, -14, g * 0.66, 60, -14, g * 0.66, [0.3, 0.55, 1, 0.06]); }
    const gridArr = new Float32Array(grid.a);
    let drag = null, yaw = 0.35, pitch = 0.45, zoomT = [0, 2, 0];
    const onDown = (e) => { drag = { x: e.clientX, y: e.clientY, yaw, pitch }; };
    const onMove = (e) => { if (!drag) return; yaw = drag.yaw - (e.clientX - drag.x) * 0.005; pitch = clamp(drag.pitch + (e.clientY - drag.y) * 0.004, 0, 1.3); };
    const onUp = () => { drag = null; };
    canvas.addEventListener('pointerdown', onDown);
    window.addEventListener('pointermove', onMove);
    window.addEventListener('pointerup', onUp);

    return {
      destroy() { canvas.removeEventListener('pointerdown', onDown); window.removeEventListener('pointermove', onMove); window.removeEventListener('pointerup', onUp); },
      frame(t, dt) {
        const asp = R.resize();
        const sel = by[self._sel] || svcs[0];
        zoomT = [lerp(zoomT[0], sel.node[0] * 0.4, dt * 2), lerp(zoomT[1], 2 + sel.node[1] * 0.4, dt * 2), lerp(zoomT[2], sel.node[2] * 0.4, dt * 2)];
        const cy = yaw + (drag ? 0 : Math.sin(t * 0.12) * 0.35), rad = 110 * Math.max(1, 1.2 / asp);
        const eye = [zoomT[0] + rad * Math.cos(pitch) * Math.sin(cy), zoomT[1] + rad * Math.sin(pitch), zoomT[2] + rad * Math.cos(pitch) * Math.cos(cy)];
        const M = K.camera(asp, eye, zoomT, 0.7);
        R.begin(M, eye, 80, 260);
        R.draw(gridArr, 'lines', 'add');
        const ln = new Batch(), pts = new Batch(), fill = new Batch();
        EDGES.forEach(([f, g], i) => {
          const A = by[f].node, B = by[g].node, live = by[f].st !== 'planned' && by[g].st !== 'planned';
          const hot = f === sel.key || g === sel.key;
          const c = live ? (hot ? COL.cyan : [0.36, 0.6, 0.9, 1]) : [0.38, 0.45, 0.56, 1];
          if (live) ln.line(...A, ...B, a(c, hot ? 0.8 : 0.35));
          else for (let k = 0; k < 10; k += 2) ln.line(lerp(A[0], B[0], k / 10), lerp(A[1], B[1], k / 10), lerp(A[2], B[2], k / 10), lerp(A[0], B[0], (k + 1) / 10), lerp(A[1], B[1], (k + 1) / 10), lerp(A[2], B[2], (k + 1) / 10), a(c, 0.4));
          if (live) for (let p = 0; p < 3; p++) {
            const u = (t * 0.45 + i * 0.13 + p / 3) % 1;
            pts.v(lerp(A[0], B[0], u), lerp(A[1], B[1], u), lerp(A[2], B[2], u), a(hot ? COL.cyan : COL.white, 0.9));
          }
        });
        svcs.forEach((s) => {
          const [x, y, z] = s.node, c = col(s.st), on = s.key === sel.key, r = on ? 3.2 : 2.2;
          const hex = Array.from({ length: 6 }, (_, k) => { const an = (k / 6) * Math.PI * 2 + t * (on ? 0.6 : 0.15); return [x + Math.cos(an) * r, y, z + Math.sin(an) * r]; });
          for (let k = 0; k < 6; k++) {
            ln.line(...hex[k], ...hex[(k + 1) % 6], a(c, 0.95));
            ln.line(hex[k][0], y - 1.2, hex[k][2], hex[(k + 1) % 6][0], y - 1.2, hex[(k + 1) % 6][2], a(c, 0.4));
            ln.line(...hex[k], hex[k][0], y - 1.2, hex[k][2], a(c, 0.3));
            fill.tri([x, y, z], hex[k], hex[(k + 1) % 6], a(c, on ? 0.3 : 0.12));
          }
          ln.line(x, y - 1.2, z, x, -14, z, a(c, 0.12));
          if (on) { const ph = (t * 0.7) % 1; ln.ring(x, y, z, r + ph * 7, 30, a(COL.cyan, 0.7 * (1 - ph))); }
          const sp = K.project(M, x, y + 4, z, R.w, R.h), el = tags[s.key];
          if (el) {
            if (sp) { el.style.opacity = on ? '1' : '0.8'; el.className = on ? 'gl-tag sel' : 'gl-tag'; el.style.transform = 'translate(' + sp[0].toFixed(1) + 'px,' + sp[1].toFixed(1) + 'px) translate(-50%,-100%)'; }
            else el.style.opacity = '0';
          }
        });
        R.draw(fill, 'tris', 'alpha');
        R.draw(ln, 'lines', 'add');
        R.draw(pts, 'points', 'add', 26);
      },
    };
  }



  render() {
    const v = this.renderVals();
    return (
      <div className="pg-status ds">
        <div className="app">
          <AppRail active="none" />
          <TopBar crumbs={["System","Status"]} pillars={v.pillars} />
          <main className="main">
            <div className="page">
              <div className="page-head">
                <div>
                  <div className="kicker" style={{ color: "#FFB547" }}>
                    <i></i>
                    {"System status"}
                  </div>
                  <h1 className="h1" style={{ marginTop: "10px" }}>
                    {"Demo mode · core services up"}
                  </h1>
                </div>
                <div className="meta">
                  {"Last checked "}
                  <span data-clock="utc">
                    {"--:--:-- UTC"}
                  </span>
                </div>
                <div className="acts">
                  <div className="segs">
                    {(v.filters || []).map((f, $index) => (
                      <React.Fragment key={$index}>
                      <button className={f?.cls} onClick={f?.pick}>
                        {f?.name}
                      </button>
                      </React.Fragment>
                    ))}
                  </div>
                  <button className="btn btn-ghost" onClick={() => alert('Subscribed! Operational status alerts & downtime notifications will be sent to your registered email.')}>
                    {"Subscribe to updates"}
                  </button>
                </div>
              </div>
              <div className="cols">
                <section className="panel">
                  <div className="summary">
                    {(v.summary || []).map((s, $index) => (
                      <React.Fragment key={$index}>
                      <div>
                        <span className="lbl">
                          {s?.k}
                        </span>
                        <b style={{ color: `${s?.color ?? ""}` }}>
                          {s?.n}
                        </b>
                      </div>
                      </React.Fragment>
                    ))}
                  </div>
                  <div className="scroll" style={{ flex: "1" }}>
                    {(v.services || []).map((s, $index) => (
                      <React.Fragment key={$index}>
                      <button className={`li svc ${s?.selCls ?? ""}`} onClick={s?.pick}>
                        <i className="dia" style={{ background: `${s?.color ?? ""}` }}></i>
                        <span style={{ minWidth: "0" }}>
                          <span className="li-t" style={{ fontSize: "14px" }}>
                            {s?.name}
                          </span>
                          <span className="li-s">
                            {s?.desc}
                          </span>
                        </span>
                        <span>
                          <span className={s?.stripCls}>
                            {(s?.cells || []).map((c, $index) => (
                              <React.Fragment key={$index}>
                              <i></i>
                              </React.Fragment>
                            ))}
                          </span>
                          <span className="strip-lbl">
                            <span>
                              {"30 d"}
                            </span>
                            <span>
                              {s?.hist}
                            </span>
                          </span>
                        </span>
                        <span style={{ textAlign: "right" }}>
                          <span className="chip" style={{ color: `${s?.color ?? ""}` }}>
                            {s?.status}
                          </span>
                        </span>
                      </button>
                      </React.Fragment>
                    ))}
                  </div>
                  <div className="note">
                    {"Uptime history needs monitoring to be connected · hatched cells mean no data, not downtime"}
                  </div>
                </section>
                <div className="right">
                  <section className="panel">
                    <div className="ph">
                      <div className="ph-l">
                        <span className="lbl strong">
                          {"Data flow"}
                        </span>
                        <span className="badge b-sim">
                          {"Packets simulated"}
                        </span>
                      </div>
                      <span className="lbl">
                        {v.selName}
                      </span>
                    </div>
                    <div className="view3d">
                      <canvas className="gl" data-gl="topo"></canvas>
                      <div className="gl-labels" data-gl-labels="topo"></div>
                      <div className="ov ov-bl glass legend">
                        <span>
                          <i className="dia" style={{ background: "#7BE3A0" }}></i>
                          {"Operational"}
                        </span>
                        <span>
                          <i className="dia" style={{ background: "#FFB547" }}></i>
                          {"Demo / simulated"}
                        </span>
                        <span>
                          <i className="dia" style={{ background: "#62738F" }}></i>
                          {"Planned"}
                        </span>
                      </div>
                    </div>
                  </section>
                  <section className="panel">
                    <div className="ph">
                      <span className="lbl strong">
                        {"Incidents"}
                      </span>
                      <span className="lbl">
                        {"Last 30 days"}
                      </span>
                    </div>
                    <div className="inc">
                      <b>
                        {"No incidents recorded"}
                      </b>
                      {"Incident history starts once uptime monitoring and alerting are connected. Planned maintenance: "}
                      <span className="mono" style={{ color: "#CFDAEE" }}>
                        {"[MAINTENANCE WINDOW]"}
                      </span>
                    </div>
                  </section>
                </div>
              </div>
            </div>
          </main>
        </div>
      </div>
    );
  }
}

export default View;
