// Generated by scripts/gen-routes.mjs
import ViewHost from '@/components/ViewHost';

export const metadata = { title: "Mission planner" };

export default function Page() {
  return <ViewHost view="MissionPlanner" {...{}} />;
}
